In [2]:
import pandas as pd

In [3]:
dados = pd.read_csv("/home/youx/youxlab-treino-git/dadosDiciplina/aula26exercicios/GasPricesinBrazil_2004-2019.csv",sep=';')
dados

,Unnamed: 0,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,...,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO
0,0,2004-05-09,2004-05-15,CENTRO OESTE,DISTRITO FEDERAL,ETANOL HIDRATADO,127,R$/l,1.288,0.016,...,1.350,0.463,0.012,0.825,0.11,0.4201,0.9666,0.133,5,2004
1,1,2004-05-09,2004-05-15,CENTRO OESTE,GOIAS,ETANOL HIDRATADO,387,R$/l,1.162,0.114,...,1.449,0.399,0.098,0.763,0.088,0.5013,1.05,0.115,5,2004
2,2,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO,ETANOL HIDRATADO,192,R$/l,1.389,0.097,...,1.760,0.419,0.070,0.97,0.095,0.5614,1.161,0.098,5,2004
3,3,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO DO SUL,ETANOL HIDRATADO,162,R$/l,1.262,0.070,...,1.509,0.432,0.055,0.83,0.119,0.5991,1.22242,0.143,5,2004
4,4,2004-05-09,2004-05-15,NORDESTE,ALAGOAS,ETANOL HIDRATADO,103,R$/l,1.181,0.078,...,1.400,0.24,0.066,0.941,0.077,0.7441,1.0317,0.082,5,2004
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
106818,106818,2019-06-23,2019-06-29,NORDESTE,RIO GRANDE DO NORTE,GNV,7,R$/m3,3.574,0.065,...,3.690,0.818,0.018,2.756,0,2.756,2.756,0,6,2019
106819,106819,2019-06-23,2019-06-29,SUL,RIO GRANDE DO SUL,GNV,23,R$/m3,3.401,0.129,...,3.789,0.95,0.038,2.451,0.402,1.9842,2.8661,0.164,6,2019
106820,106820,2019-06-23,2019-06-29,SUL,SANTA CATARINA,GNV,24,R$/m3,2.912,0.190,...,3.499,0.914,0.065,1.998,0,1.9981,1.9981,0,6,2019
106821,106821,2019-06-23,2019-06-29,SUDESTE,SAO PAULO,GNV,52,R$/m3,3.020,0.229,...,3.490,0.646,0.076,2.374,0.165,2.0179,2.5093,0.07,6,2019
106822,106822,2019-06-23,2019-06-29,NORDESTE,SERGIPE,GNV,4,R$/m3,3.697,0.005,...,3.699,1.179,0.001,2.518,0,2.5175,2.5175,0,6,2019

In [4]:
dados.query('ANO != 2019')
df = dados.query('ANO != 2019')
df

,Unnamed: 0,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,...,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO
0,0,2004-05-09,2004-05-15,CENTRO OESTE,DISTRITO FEDERAL,ETANOL HIDRATADO,127,R$/l,1.288,0.016,...,1.350,0.463,0.012,0.825,0.11,0.4201,0.9666,0.133,5,2004
1,1,2004-05-09,2004-05-15,CENTRO OESTE,GOIAS,ETANOL HIDRATADO,387,R$/l,1.162,0.114,...,1.449,0.399,0.098,0.763,0.088,0.5013,1.05,0.115,5,2004
2,2,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO,ETANOL HIDRATADO,192,R$/l,1.389,0.097,...,1.760,0.419,0.070,0.97,0.095,0.5614,1.161,0.098,5,2004
3,3,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO DO SUL,ETANOL HIDRATADO,162,R$/l,1.262,0.070,...,1.509,0.432,0.055,0.83,0.119,0.5991,1.22242,0.143,5,2004
4,4,2004-05-09,2004-05-15,NORDESTE,ALAGOAS,ETANOL HIDRATADO,103,R$/l,1.181,0.078,...,1.400,0.24,0.066,0.941,0.077,0.7441,1.0317,0.082,5,2004
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
103064,103064,2018-12-30,2019-01-05,NORDESTE,RIO GRANDE DO NORTE,GNV,10,R$/m3,3.465,0.060,...,3.590,0.759,0.017,2.706,0,2.7059,2.7059,0,12,2018
103065,103065,2018-12-30,2019-01-05,SUL,RIO GRANDE DO SUL,GNV,16,R$/m3,3.402,0.103,...,3.499,1.296,0.030,2.106,0.249,1.8775,2.3724,0.118,12,2018
103066,103066,2018-12-30,2019-01-05,SUL,SANTA CATARINA,GNV,15,R$/m3,2.944,0.124,...,3.199,0.67,0.042,2.274,0.283,1.8738,2.274,0.124,12,2018
103067,103067,2018-12-30,2019-01-05,SUDESTE,SAO PAULO,GNV,41,R$/m3,2.353,0.451,...,3.429,0.467,0.192,1.886,0.25,1.64,2.332,0.133,12,2018
103068,103068,2018-12-30,2019-01-05,NORDESTE,SERGIPE,GNV,2,R$/m3,3.649,0.000,...,3.649,-,0.000,-,-,-,-,-,12,2018

In [11]:
#df_produtos = df.groupby('PRODUTO')['REGIÃO'].value_counts()   
df_produtos = df.groupby(['PRODUTO','REGIÃO']).value_counts()
df_produtos

PRODUTO           REGIÃO        Unnamed: 0  DATA INICIAL  DATA FINAL  ESTADO              NÚMERO DE POSTOS PESQUISADOS  UNIDADE DE MEDIDA  PREÇO MÉDIO REVENDA  DESVIO PADRÃO REVENDA  PREÇO MÍNIMO REVENDA  PREÇO MÁXIMO REVENDA  MARGEM MÉDIA REVENDA  COEF DE VARIAÇÃO REVENDA  PREÇO MÉDIO DISTRIBUIÇÃO  DESVIO PADRÃO DISTRIBUIÇÃO  PREÇO MÍNIMO DISTRIBUIÇÃO  PREÇO MÁXIMO DISTRIBUIÇÃO  COEF DE VARIAÇÃO DISTRIBUIÇÃO  MÊS  ANO
ETANOL HIDRATADO  CENTRO OESTE  0           2004-05-09    2004-05-15  DISTRITO FEDERAL    127                           R$/l               1.288                0.016                  1.190                 1.350                 0.463                 0.012                     0.825                     0.11                        0.4201                     0.9666                     0.133                          5    2004    1
                                1           2004-05-09    2004-05-15  GOIAS               387                           R$/l               1.162                0.114                  0.890                 1.449                 0.399                 0.098                     0.763                     0.088                       0.5013                     1.05                       0.115                          5    2004    1
                                2           2004-05-09    2004-05-15  MATO GROSSO         192                           R$/l               1.389                0.097                  1.180                 1.760                 0.419                 0.070                     0.97                      0.095                       0.5614                     1.161                      0.098                          5    2004    1
                                3           2004-05-09    2004-05-15  MATO GROSSO DO SUL  162                           R$/l               1.262                0.070                  1.090                 1.509                 0.432                 0.055                     0.83                      0.119                       0.5991                     1.22242                    0.143                          5    2004    1
                                27          2004-05-16    2004-05-22  DISTRITO FEDERAL    144                           R$/l               1.271                0.039                  1.060                 1.300                 0.448                 0.031                     0.823                     0.111                       0.4094                     1.1931                     0.135                          5    2004    1
                                                                                                                                                                                                                                                                                                                                                                                                                                          ..
ÓLEO DIESEL S10   SUL           102843      2018-12-23    2018-12-29  RIO GRANDE DO SUL   297                           R$/l               3.515                0.194                  3.079                 3.999                 0.535                 0.055                     2.98                      0.126                       2.72                       3.415                      0.042                          12   2018    1
                                102846      2018-12-23    2018-12-29  SANTA CATARINA      213                           R$/l               3.446                0.176                  3.090                 4.059                 0.439                 0.051                     3.007                     0.127                       2.761                      3.311                      0.042                          12   2018    1
                                102989      2018-12-30    2019-01-05  PARANA              282                           R$/l               3.313                0.168                  3.040                 3.859                 0.47                  0.051                     2.843                     0.104                       2.645                      3.0539                     0.037                          12   2018    1
                                102994      2018-12-30    2019-01-05  RIO GRANDE DO SUL   302                           R$/l               3.490                0.196                  2.999                 3.999                 0.542                 0.056                     2.948                     0.133                       2.72                       3.2415                     0.045                          12   2018    1
                                102997      2018-12-30    2019-01-05  SANTA CATARINA      206                           R$/l               3.416                0.175                  3.099                 3.998                 0.432                 0.051                     2.984                     0.119                       2.761                      3.269                      0.04                           12   2018    1
Name: count, Length: 103069, dtype: int64

In [17]:
df_2018 = df.query('PRODUTO in ["GASOLINA COMUM"] and ESTADO == "SAO PAULO" and ANO == 2018') #DÚVIDA
df_2018.head(10)

,Unnamed: 0,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,...,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO
95351,95351,2018-01-07,2018-01-13,SUDESTE,SAO PAULO,GASOLINA COMUM,1641,R$/l,3.988,0.156,...,4.599,0.411,0.039,3.577,0.104,2.99,3.951,0.029,1,2018
95502,95502,2018-01-14,2018-01-20,SUDESTE,SAO PAULO,GASOLINA COMUM,1648,R$/l,4.002,0.155,...,4.499,0.412,0.039,3.59,0.102,2.99,3.9014,0.028,1,2018
95654,95654,2018-01-21,2018-01-27,SUDESTE,SAO PAULO,GASOLINA COMUM,1648,R$/l,4.006,0.160,...,4.899,0.41,0.040,3.596,0.102,2.99,3.9014,0.028,1,2018
95806,95806,2018-01-28,2018-02-03,SUDESTE,SAO PAULO,GASOLINA COMUM,1644,R$/l,4.019,0.156,...,4.699,0.423,0.039,3.596,0.107,2.924,3.9537,0.03,1,2018
95958,95958,2018-02-04,2018-02-10,SUDESTE,SAO PAULO,GASOLINA COMUM,1646,R$/l,4.004,0.157,...,4.597,0.416,0.039,3.588,0.102,2.99,3.9537,0.028,2,2018
96109,96109,2018-02-11,2018-02-17,SUDESTE,SAO PAULO,GASOLINA COMUM,1640,R$/l,4.014,0.153,...,4.599,0.444,0.038,3.57,0.097,2.99,3.8899,0.027,2,2018
96259,96259,2018-02-18,2018-02-24,SUDESTE,SAO PAULO,GASOLINA COMUM,1637,R$/l,4.008,0.161,...,4.899,0.445,0.040,3.563,0.097,2.99,3.891,0.027,2,2018
96411,96411,2018-02-25,2018-03-03,SUDESTE,SAO PAULO,GASOLINA COMUM,1638,R$/l,3.992,0.164,...,4.899,0.422,0.041,3.57,0.106,2.99,3.9549,0.03,2,2018
96563,96563,2018-03-04,2018-03-10,SUDESTE,SAO PAULO,GASOLINA COMUM,1637,R$/l,3.970,0.161,...,4.699,0.387,0.041,3.583,0.11,2.99,4.0687,0.031,3,2018
96715,96715,2018-03-11,2018-03-17,SUDESTE,SAO PAULO,GASOLINA COMUM,1644,R$/l,4.003,0.155,...,4.699,0.41,0.039,3.593,0.104,2.99,4.259,0.029,3,2018

In [7]:
df_2018.describe()

,Unnamed: 0,NÚMERO DE POSTOS PESQUISADOS,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,PREÇO MÁXIMO REVENDA,COEF DE VARIAÇÃO REVENDA,MÊS,ANO
count,52.000000,52.000000,52.000000,52.000000,52.000000,52.000000,52.000000,52.000000,52.0
mean,99196.096154,1610.211538,4.202769,0.175500,3.671500,4.975750,0.041750,6.615385,2018.0
std,2279.595314,213.627432,0.180672,0.017955,0.163808,0.211198,0.003965,3.470627,0.0
min,95351.000000,102.000000,3.970000,0.150000,3.369000,4.499000,0.034000,1.000000,2018.0
25%,97281.250000,1639.000000,4.008000,0.159750,3.499000,4.899000,0.039000,4.000000,2018.0
50%,99196.500000,1642.000000,4.202000,0.173000,3.679000,4.999000,0.040000,7.000000,2018.0
75%,101116.250000,1644.000000,4.336250,0.189000,3.784000,5.099000,0.044000,9.250000,2018.0
max,103025.000000,1649.000000,4.512000,0.216000,3.969000,5.299000,0.051000,12.000000,2018.0

In [16]:
df_estanol_e_gasolina = df.query('PRODUTO in ["GASOLINA COMUM", "ETANOL HIDRATADO"] and ESTADO == "SAO PAULO" and ANO == 2018')  #DÚVIDA
df_estanol_e_gasolina

,Unnamed: 0,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,...,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO
95270,95270,2018-01-07,2018-01-13,SUDESTE,SAO PAULO,ETANOL HIDRATADO,1664,R$/l,2.833,0.139,...,3.399,0.338,0.049,2.495,0.092,2.1842,2.8833,0.037,1,2018
95351,95351,2018-01-07,2018-01-13,SUDESTE,SAO PAULO,GASOLINA COMUM,1641,R$/l,3.988,0.156,...,4.599,0.411,0.039,3.577,0.104,2.99,3.951,0.029,1,2018
95421,95421,2018-01-14,2018-01-20,SUDESTE,SAO PAULO,ETANOL HIDRATADO,1661,R$/l,2.868,0.134,...,3.399,0.331,0.047,2.537,0.087,2.26,2.8471,0.034,1,2018
95502,95502,2018-01-14,2018-01-20,SUDESTE,SAO PAULO,GASOLINA COMUM,1648,R$/l,4.002,0.155,...,4.499,0.412,0.039,3.59,0.102,2.99,3.9014,0.028,1,2018
95573,95573,2018-01-21,2018-01-27,SUDESTE,SAO PAULO,ETANOL HIDRATADO,1662,R$/l,2.874,0.135,...,3.399,0.324,0.047,2.55,0.095,1.69,2.9722,0.037,1,2018
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102724,102724,2018-12-16,2018-12-22,SUDESTE,SAO PAULO,GASOLINA COMUM,1637,R$/l,4.129,0.201,...,5.099,0.49,0.049,3.639,0.11,3.35,3.9892,0.03,12,2018
102793,102793,2018-12-23,2018-12-29,SUDESTE,SAO PAULO,ETANOL HIDRATADO,1662,R$/l,2.644,0.163,...,3.699,0.305,0.062,2.339,0.094,2.0067,2.7443,0.04,12,2018
102874,102874,2018-12-23,2018-12-29,SUDESTE,SAO PAULO,GASOLINA COMUM,1641,R$/l,4.129,0.201,...,4.999,0.484,0.049,3.645,0.107,3.35,3.9892,0.029,12,2018
102944,102944,2018-12-30,2019-01-05,SUDESTE,SAO PAULO,ETANOL HIDRATADO,1661,R$/l,2.643,0.161,...,3.699,0.303,0.061,2.34,0.097,1.9072,2.7957,0.041,12,2018
103025,103025,2018-12-30,2019-01-05,SUDESTE,SAO PAULO,GASOLINA COMUM,1643,R$/l,4.113,0.201,...,4.999,0.503,0.049,3.61,0.1,3.35,3.9585,0.028,12,2018

In [9]:
df_estanol_e_gasolina['PREÇO MÉDIO REVENDA'].describe().to_frame()

       PREÇO MÉDIO REVENDA
count           104.000000
mean              3.457337
std               0.766239
min               2.393000
25%               2.726000
50%               3.431000
75%               4.199000
max               4.512000

In [10]:
df_estanol_e_gasolina.groupby('PRODUTO')['PREÇO MÉDIO REVENDA'].describe()

,count,mean,std,min,25%,50%,75%,max
PRODUTO,,,,,,,,
ETANOL HIDRATADO,52.0,2.711904,0.141365,2.393,2.6315,2.720,2.83825,2.892
GASOLINA COMUM,52.0,4.202769,0.180672,3.970,4.0080,4.202,4.33625,4.512