In [104]:
import pandas as pd
df = pd.read_csv('/home/youx/projeto-git/youxlab-treino-git/dados/exercicio-vendas/exercicio_vendas.csv')
df.dropna(inplace=True)
df.head()
del df['Unnamed: 0']
df

    Região     Produtos  Vendas
0    Leste  Eletrônicos  8196.0
2    Norte     Perfumes  7443.0
3    Leste        Papel  7306.0
4    Leste     Perfumes  5696.0
5    Oeste     Perfumes  5901.0
..     ...          ...     ...
195    Sul    Vestuário  1162.0
196    Sul    Alimentos  2256.0
197  Oeste    Alimentos  7960.0
198  Norte    Alimentos  5261.0
199  Leste  Eletrônicos  5405.0

[180 rows x 3 columns]

In [105]:
grupos = df.groupby(['Região', 'Produtos']).mean().reset_index()
grupos

   Região     Produtos       Vendas
0   Leste    Alimentos  5384.222222
1   Leste  Eletrônicos  5246.000000
2   Leste        Papel  5141.916667
3   Leste     Perfumes  6584.333333
4   Leste    Vestuário  5963.625000
5   Norte    Alimentos  6339.000000
6   Norte  Eletrônicos  4072.222222
7   Norte        Papel  4042.333333
8   Norte     Perfumes  4770.250000
9   Norte    Vestuário  5299.230769
10  Oeste    Alimentos  5509.000000
11  Oeste  Eletrônicos  3866.133333
12  Oeste        Papel  5480.636364
13  Oeste     Perfumes  7480.250000
14  Oeste    Vestuário  4809.615385
15    Sul    Alimentos  3944.285714
16    Sul  Eletrônicos  5149.833333
17    Sul        Papel  6118.727273
18    Sul     Perfumes  3409.000000
19    Sul    Vestuário  5614.250000

In [106]:
def nota(vendas):
    if vendas < 3000:
        return 'Baixa'
    elif 3000 <= vendas <= 7000:
        return 'Média'
    else:
        return 'Alta' 
      
df['Faixa de Vendas'] = df['Vendas'].apply(nota)
df

    Região     Produtos  Vendas Faixa de Vendas
0    Leste  Eletrônicos  8196.0            Alta
2    Norte     Perfumes  7443.0            Alta
3    Leste        Papel  7306.0            Alta
4    Leste     Perfumes  5696.0           Média
5    Oeste     Perfumes  5901.0           Média
..     ...          ...     ...             ...
195    Sul    Vestuário  1162.0           Baixa
196    Sul    Alimentos  2256.0           Baixa
197  Oeste    Alimentos  7960.0            Alta
198  Norte    Alimentos  5261.0           Média
199  Leste  Eletrônicos  5405.0           Média

[180 rows x 4 columns]

In [107]:
produtos_regiao = df.groupby(['Região', 'Faixa de Vendas'])['Produtos'].value_counts()
produtos_regiao

Região  Faixa de Vendas  Produtos
Leste   Alta             Eletrônicos    5
                         Vestuário      4
                         Alimentos      3
                         Papel          3
                         Perfumes       3
        Baixa            Eletrônicos    3
                         Papel          3
                         Alimentos      1
                         Perfumes       1
                         Vestuário      1
        Média            Papel          6
                         Alimentos      5
                         Eletrônicos    5
                         Vestuário      3
                         Perfumes       2
Norte   Alta             Vestuário      4
                         Perfumes       3
                         Alimentos      2
                         Eletrônicos    1
        Baixa            Vestuário      5
                         Eletrônicos    4
                         Perfumes       3
                         Papel          2
                         Alimentos      1
        Média            Perfumes       6
                         Eletrônicos    4
                         Papel          4
                         Vestuário      4
                         Alimentos      1
Oeste   Alta             Papel          5
                         Alimentos      2
                         Eletrônicos    2
                         Perfumes       2
                         Vestuário      2
        Baixa            Eletrônicos    7
                         Vestuário      3
                         Papel          2
                         Alimentos      1
        Média            Vestuário      8
                         Eletrônicos    6
                         Papel          4
                         Alimentos      2
                         Perfumes       2
Sul     Alta             Papel          6
                         Eletrônicos    5
                         Vestuário      4
                         Alimentos      1
        Baixa            Alimentos      3
                         Papel          3
                         Eletrônicos    2
                         Vestuário      2
                         Perfumes       1
        Média            Eletrônicos    5
                         Alimentos      3
                         Papel          2
                         Vestuário      2
                         Perfumes       1
Name: count, dtype: int64

In [108]:
baixa = df.query('`Faixa de Vendas` == "Baixa"').reset_index()
baixa

    index Região     Produtos  Vendas Faixa de Vendas
0       6  Norte    Vestuário  2906.0           Baixa
1       7  Norte     Perfumes   637.0           Baixa
2       9    Sul     Perfumes  1941.0           Baixa
3      16  Oeste  Eletrônicos  2468.0           Baixa
4      25    Sul        Papel   953.0           Baixa
5      28  Oeste  Eletrônicos   674.0           Baixa
6      29  Oeste  Eletrônicos  1248.0           Baixa
7      35  Norte    Vestuário  2591.0           Baixa
8      39  Leste  Eletrônicos   104.0           Baixa
9      43  Oeste    Vestuário   976.0           Baixa
10     52  Leste    Vestuário   735.0           Baixa
11     53  Oeste  Eletrônicos  1793.0           Baixa
12     57  Norte    Vestuário   930.0           Baixa
13     63  Norte  Eletrônicos  2938.0           Baixa
14     64  Leste  Eletrônicos  1250.0           Baixa
15     66  Oeste    Alimentos  2031.0           Baixa
16     68  Oeste        Papel  1764.0           Baixa
17     69    Sul    Alimentos  1181.0           Baixa
18     70    Sul        Papel   612.0           Baixa
19     73    Sul  Eletrônicos   659.0           Baixa
20     79  Oeste  Eletrônicos   680.0           Baixa
21     87  Norte        Papel  2844.0           Baixa
22     90  Oeste    Vestuário  2241.0           Baixa
23     99  Norte        Papel  2949.0           Baixa
24    102    Sul    Alimentos  2589.0           Baixa
25    107  Oeste  Eletrônicos  2939.0           Baixa
26    112  Oeste  Eletrônicos   951.0           Baixa
27    113    Sul        Papel  1787.0           Baixa
28    119  Norte    Vestuário  2838.0           Baixa
29    125  Oeste    Vestuário  1166.0           Baixa
30    132  Norte  Eletrônicos  2182.0           Baixa
31    136  Norte    Alimentos   517.0           Baixa
32    141  Norte  Eletrônicos   925.0           Baixa
33    145  Leste        Papel   512.0           Baixa
34    148  Norte  Eletrônicos   828.0           Baixa
35    152  Norte     Perfumes  2604.0           Baixa
36    154  Norte    Vestuário  2886.0           Baixa
37    155    Sul    Vestuário  1222.0           Baixa
38    160  Leste  Eletrônicos  2243.0           Baixa
39    171  Norte     Perfumes   828.0           Baixa
40    174  Oeste        Papel   798.0           Baixa
41    176  Leste     Perfumes   495.0           Baixa
42    181  Leste        Papel  2602.0           Baixa
43    182    Sul  Eletrônicos   817.0           Baixa
44    183  Leste        Papel  2882.0           Baixa
45    194  Leste    Alimentos  1267.0           Baixa
46    195    Sul    Vestuário  1162.0           Baixa
47    196    Sul    Alimentos  2256.0           Baixa

In [111]:
medio = df.query('`Faixa de Vendas` == "Média"').reset_index()
medio

    index Região     Produtos  Vendas Faixa de Vendas
0       4  Leste     Perfumes  5696.0           Média
1       5  Oeste     Perfumes  5901.0           Média
2       8  Leste        Papel  6086.0           Média
3      12  Leste        Papel  5725.0           Média
4      13  Leste    Alimentos  3050.0           Média
..    ...    ...          ...     ...             ...
70    189    Sul  Eletrônicos  4591.0           Média
71    191  Leste    Alimentos  5688.0           Média
72    193  Leste    Alimentos  3736.0           Média
73    198  Norte    Alimentos  5261.0           Média
74    199  Leste  Eletrônicos  5405.0           Média

[75 rows x 5 columns]

In [112]:
alta = df.query('`Faixa de Vendas` == "Alta"')
alta

    Região     Produtos  Vendas Faixa de Vendas
0    Leste  Eletrônicos  8196.0            Alta
2    Norte     Perfumes  7443.0            Alta
3    Leste        Papel  7306.0            Alta
10   Leste    Vestuário  8816.0            Alta
11   Leste    Vestuário  7071.0            Alta
14   Oeste    Alimentos  8092.0            Alta
18   Oeste        Papel  8273.0            Alta
20     Sul        Papel  9263.0            Alta
23   Oeste    Vestuário  9458.0            Alta
32   Oeste        Papel  7609.0            Alta
44   Oeste  Eletrônicos  9283.0            Alta
45   Oeste        Papel  7127.0            Alta
47   Leste  Eletrônicos  7066.0            Alta
48     Sul    Alimentos  7179.0            Alta
49     Sul        Papel  8087.0            Alta
54   Leste     Perfumes  9974.0            Alta
56   Oeste  Eletrônicos  8411.0            Alta
59   Norte    Alimentos  9661.0            Alta
60   Leste    Alimentos  9032.0            Alta
61   Leste        Papel  8408.0            Alta
65     Sul    Vestuário  7660.0            Alta
71     Sul    Vestuário  7905.0            Alta
75     Sul        Papel  7504.0            Alta
78   Leste  Eletrônicos  9762.0            Alta
80   Leste        Papel  7104.0            Alta
81   Oeste    Vestuário  8230.0            Alta
86     Sul    Vestuário  7353.0            Alta
94     Sul  Eletrônicos  9927.0            Alta
95     Sul  Eletrônicos  7521.0            Alta
100  Leste  Eletrônicos  7490.0            Alta
101    Sul  Eletrônicos  7005.0            Alta
104    Sul    Vestuário  9307.0            Alta
105    Sul        Papel  9640.0            Alta
108    Sul        Papel  8627.0            Alta
116  Norte    Vestuário  9860.0            Alta
122    Sul        Papel  8102.0            Alta
126    Sul  Eletrônicos  7823.0            Alta
131  Norte    Vestuário  9045.0            Alta
133  Norte     Perfumes  9067.0            Alta
135  Norte    Alimentos  9917.0            Alta
137  Norte    Vestuário  8406.0            Alta
138  Leste     Perfumes  8908.0            Alta
142  Oeste        Papel  7768.0            Alta
144  Oeste     Perfumes  9808.0            Alta
146  Leste    Vestuário  7643.0            Alta
147  Leste  Eletrônicos  7687.0            Alta
149  Oeste        Papel  7264.0            Alta
150  Leste    Vestuário  8967.0            Alta
161  Norte     Perfumes  9979.0            Alta
163  Oeste     Perfumes  7457.0            Alta
175    Sul  Eletrônicos  7286.0            Alta
177  Leste     Perfumes  7500.0            Alta
178  Norte  Eletrônicos  8182.0            Alta
188  Leste    Alimentos  7366.0            Alta
190  Leste    Alimentos  7292.0            Alta
192  Norte    Vestuário  7751.0            Alta
197  Oeste    Alimentos  7960.0            Alta