In [2]:
import pandas as pd
dados = pd.read_csv('/home/youx/youxlab-treino-git/aulas_dados/datasets/GasPricesinBrazil_2004-2019_preprocessado_final.csv')
dados

,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO
0,2004-05-09,2004-05-15,CENTRO OESTE,DISTRITO FEDERAL,ETANOL HIDRATADO,127,R$/l,1.288,0.016,1.190,1.350,0.463,0.012,0.825,0.110,0.4201,0.96660,0.133,5,2004
1,2004-05-09,2004-05-15,CENTRO OESTE,GOIAS,ETANOL HIDRATADO,387,R$/l,1.162,0.114,0.890,1.449,0.399,0.098,0.763,0.088,0.5013,1.05000,0.115,5,2004
2,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO,ETANOL HIDRATADO,192,R$/l,1.389,0.097,1.180,1.760,0.419,0.070,0.970,0.095,0.5614,1.16100,0.098,5,2004
3,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO DO SUL,ETANOL HIDRATADO,162,R$/l,1.262,0.070,1.090,1.509,0.432,0.055,0.830,0.119,0.5991,1.22242,0.143,5,2004
4,2004-05-09,2004-05-15,NORDESTE,ALAGOAS,ETANOL HIDRATADO,103,R$/l,1.181,0.078,1.050,1.400,0.240,0.066,0.941,0.077,0.7441,1.03170,0.082,5,2004
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
103387,2019-06-23,2019-06-29,NORDESTE,RIO GRANDE DO NORTE,GNV,7,R$/m3,3.574,0.065,3.499,3.690,0.818,0.018,2.756,0.000,2.7560,2.75600,0.000,6,2019
103388,2019-06-23,2019-06-29,SUL,RIO GRANDE DO SUL,GNV,23,R$/m3,3.401,0.129,3.230,3.789,0.950,0.038,2.451,0.402,1.9842,2.86610,0.164,6,2019
103389,2019-06-23,2019-06-29,SUL,SANTA CATARINA,GNV,24,R$/m3,2.912,0.190,2.699,3.499,0.914,0.065,1.998,0.000,1.9981,1.99810,0.000,6,2019
103390,2019-06-23,2019-06-29,SUDESTE,SAO PAULO,GNV,52,R$/m3,3.020,0.229,2.699,3.490,0.646,0.076,2.374,0.165,2.0179,2.50930,0.070,6,2019
103391,2019-06-23,2019-06-29,NORDESTE,SERGIPE,GNV,4,R$/m3,3.697,0.005,3.689,3.699,1.179,0.001,2.518,0.000,2.5175,2.51750,0.000,6,2019

In [6]:
#7.1
df = pd.DataFrame(dados)
grupo = df.groupby('PRODUTO')
grupo

In [7]:
grupo['REGIÃO'].value_counts().to_frame()

                               count
PRODUTO          REGIÃO
ETANOL HIDRATADO NORDESTE       7046
                 NORTE          5177
                 SUDESTE        3137
                 CENTRO OESTE   3122
                 SUL            2353
GASOLINA COMUM   NORDESTE       7063
                 NORTE          5464
                 SUDESTE        3140
                 CENTRO OESTE   3134
                 SUL            2354
GLP              NORDESTE       6410
                 NORTE          5327
                 SUDESTE        3137
                 CENTRO OESTE   3098
                 SUL            2343
GNV              NORDESTE       5176
                 SUDESTE        2841
                 SUL            1899
                 CENTRO OESTE    847
                 NORTE           243
ÓLEO DIESEL      NORDESTE       7061
                 NORTE          5465
                 SUDESTE        3140
                 CENTRO OESTE   3134
                 SUL            2354
ÓLEO DIESEL S10  NORDESTE       3032
                 NORTE          2324
                 SUDESTE        1349
                 CENTRO OESTE   1210
                 SUL            1012

In [23]:
df_gasolina_etanol_2018 = df.query('(PRODUTO == "GASOLINA COMUM" or PRODUTO == "ETANOL HIDRATADO") and ESTADO == "SAO PAULO"')
df_gasolina_etanol_2018

,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO
23,2004-05-09,2004-05-15,SUDESTE,SAO PAULO,ETANOL HIDRATADO,4047,R$/l,0.768,0.085,0.590,1.150,0.198,0.111,0.570,0.056,0.42710,1.4123,0.098,5,2004
50,2004-05-16,2004-05-22,SUDESTE,SAO PAULO,ETANOL HIDRATADO,4066,R$/l,0.766,0.083,0.590,1.150,0.190,0.108,0.576,0.050,0.43204,0.9724,0.087,5,2004
77,2004-05-23,2004-05-29,SUDESTE,SAO PAULO,ETANOL HIDRATADO,4077,R$/l,0.823,0.071,0.620,1.199,0.209,0.086,0.614,0.063,0.34951,1.4120,0.103,5,2004
104,2004-05-30,2004-06-05,SUDESTE,SAO PAULO,ETANOL HIDRATADO,4073,R$/l,0.887,0.075,0.639,1.359,0.216,0.085,0.671,0.075,0.33980,1.0669,0.112,5,2004
131,2004-06-06,2004-06-12,SUDESTE,SAO PAULO,ETANOL HIDRATADO,4082,R$/l,0.894,0.071,0.669,1.199,0.205,0.079,0.689,0.072,0.47797,1.0669,0.104,6,2004
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
103058,2019-06-09,2019-06-15,SUDESTE,SAO PAULO,GASOLINA COMUM,1643,R$/l,4.210,0.177,3.759,4.992,0.425,0.042,3.785,0.096,3.52000,4.1007,0.025,6,2019
103123,2019-06-16,2019-06-22,SUDESTE,SAO PAULO,ETANOL HIDRATADO,1661,R$/l,2.593,0.182,2.169,3.899,0.323,0.070,2.270,0.103,1.95990,2.6680,0.045,6,2019
103204,2019-06-16,2019-06-22,SUDESTE,SAO PAULO,GASOLINA COMUM,1635,R$/l,4.168,0.177,3.679,5.199,0.443,0.042,3.725,0.096,3.50200,4.0892,0.026,6,2019
103269,2019-06-23,2019-06-29,SUDESTE,SAO PAULO,ETANOL HIDRATADO,1662,R$/l,2.557,0.185,2.159,3.899,0.296,0.072,2.261,0.102,1.93350,2.6680,0.045,6,2019
103350,2019-06-23,2019-06-29,SUDESTE,SAO PAULO,GASOLINA COMUM,1644,R$/l,4.142,0.183,3.769,4.999,0.429,0.044,3.713,0.097,3.52000,4.0892,0.026,6,2019

In [16]:
#7.2
df_gasolina_2018 = df.query('PRODUTO == "GASOLINA COMUM" and ESTADO == "SAO PAULO"')
df_gasolina_2018.head()

,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO
12003,2004-05-09,2004-05-15,SUDESTE,SAO PAULO,GASOLINA COMUM,4107,R$/l,1.891,0.101,1.570,2.399,0.235,0.053,1.656,0.064,1.38,1.9440,0.039,5,2004
12030,2004-05-16,2004-05-22,SUDESTE,SAO PAULO,GASOLINA COMUM,4133,R$/l,1.888,0.101,1.540,2.220,0.233,0.053,1.655,0.063,1.38,1.9319,0.038,5,2004
12057,2004-05-23,2004-05-29,SUDESTE,SAO PAULO,GASOLINA COMUM,4139,R$/l,1.894,0.095,1.570,2.399,0.234,0.050,1.660,0.065,1.39,1.9291,0.039,5,2004
12084,2004-05-30,2004-06-05,SUDESTE,SAO PAULO,GASOLINA COMUM,4139,R$/l,1.912,0.094,1.529,2.199,0.235,0.049,1.677,0.068,1.39,1.9733,0.041,5,2004
12111,2004-06-06,2004-06-12,SUDESTE,SAO PAULO,GASOLINA COMUM,4138,R$/l,1.919,0.088,1.580,2.399,0.231,0.046,1.688,0.063,1.41,2.0946,0.037,6,2004

In [26]:
df_gasolina_etanol_2018.head()

,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO
23,2004-05-09,2004-05-15,SUDESTE,SAO PAULO,ETANOL HIDRATADO,4047,R$/l,0.768,0.085,0.590,1.150,0.198,0.111,0.570,0.056,0.42710,1.4123,0.098,5,2004
50,2004-05-16,2004-05-22,SUDESTE,SAO PAULO,ETANOL HIDRATADO,4066,R$/l,0.766,0.083,0.590,1.150,0.190,0.108,0.576,0.050,0.43204,0.9724,0.087,5,2004
77,2004-05-23,2004-05-29,SUDESTE,SAO PAULO,ETANOL HIDRATADO,4077,R$/l,0.823,0.071,0.620,1.199,0.209,0.086,0.614,0.063,0.34951,1.4120,0.103,5,2004
104,2004-05-30,2004-06-05,SUDESTE,SAO PAULO,ETANOL HIDRATADO,4073,R$/l,0.887,0.075,0.639,1.359,0.216,0.085,0.671,0.075,0.33980,1.0669,0.112,5,2004
131,2004-06-06,2004-06-12,SUDESTE,SAO PAULO,ETANOL HIDRATADO,4082,R$/l,0.894,0.071,0.669,1.199,0.205,0.079,0.689,0.072,0.47797,1.0669,0.104,6,2004

In [17]:
df_gasolina_2018.shape

(785, 20)

In [27]:
df_gasolina_etanol_2018['PREÇO MÉDIO REVENDA'].describe().to_frame()

       PREÇO MÉDIO REVENDA
count          1570.000000
mean              2.323946
std               0.776569
min               0.766000
25%               1.791500
50%               2.399000
75%               2.706750
max               4.512000

In [31]:
df_gasolina_etanol_2018.groupby('PRODUTO')['PREÇO MÉDIO REVENDA'].describe()

                  count      mean       std    min    25%    50%    75%    max
PRODUTO
ETANOL HIDRATADO  785.0  1.802243  0.539164  0.766  1.303  1.791  2.179  2.986
GASOLINA COMUM    785.0  2.845648  0.609221  1.888  2.411  2.638  3.177  4.512