In [42]:
import pandas as pd
dados = pd.read_csv(r"/home/youx/youxlab-treino-git/aula.ipynb/GasPricesinBrazil_2004-2019_preprocessado (1).csv")
df = dados.query('ANO != 2019')
df

,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO
0,2004-05-09,2004-05-15,CENTRO OESTE,DISTRITO FEDERAL,ETANOL HIDRATADO,127,R$/l,1.288,0.016,1.190,1.350,0.463,0.012,0.825,0.11,0.4201,0.9666,0.133,5,2004
1,2004-05-09,2004-05-15,CENTRO OESTE,GOIAS,ETANOL HIDRATADO,387,R$/l,1.162,0.114,0.890,1.449,0.399,0.098,0.763,0.088,0.5013,1.05,0.115,5,2004
2,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO,ETANOL HIDRATADO,192,R$/l,1.389,0.097,1.180,1.760,0.419,0.070,0.97,0.095,0.5614,1.161,0.098,5,2004
3,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO DO SUL,ETANOL HIDRATADO,162,R$/l,1.262,0.070,1.090,1.509,0.432,0.055,0.83,0.119,0.5991,1.22242,0.143,5,2004
4,2004-05-09,2004-05-15,NORDESTE,ALAGOAS,ETANOL HIDRATADO,103,R$/l,1.181,0.078,1.050,1.400,0.24,0.066,0.941,0.077,0.7441,1.0317,0.082,5,2004
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
103064,2018-12-30,2019-01-05,NORDESTE,RIO GRANDE DO NORTE,GNV,10,R$/m3,3.465,0.060,3.370,3.590,0.759,0.017,2.706,0,2.7059,2.7059,0,12,2018
103065,2018-12-30,2019-01-05,SUL,RIO GRANDE DO SUL,GNV,16,R$/m3,3.402,0.103,3.199,3.499,1.296,0.030,2.106,0.249,1.8775,2.3724,0.118,12,2018
103066,2018-12-30,2019-01-05,SUL,SANTA CATARINA,GNV,15,R$/m3,2.944,0.124,2.790,3.199,0.67,0.042,2.274,0.283,1.8738,2.274,0.124,12,2018
103067,2018-12-30,2019-01-05,SUDESTE,SAO PAULO,GNV,41,R$/m3,2.353,0.451,1.999,3.429,0.467,0.192,1.886,0.25,1.64,2.332,0.133,12,2018
103068,2018-12-30,2019-01-05,NORDESTE,SERGIPE,GNV,2,R$/m3,3.649,0.000,3.649,3.649,-,0.000,-,-,-,-,-,12,2018

In [48]:
grupos= df.groupby('PRODUTO')
grupos

In [46]:
grupos['REGIÃO'].value_counts().to_frame()

                               count
PRODUTO          REGIÃO
ETANOL HIDRATADO NORDESTE       6839
                 NORTE          5244
                 CENTRO OESTE   3040
                 SUDESTE        3040
                 SUL            2279
GASOLINA COMUM   NORDESTE       6840
                 NORTE          5319
                 CENTRO OESTE   3040
                 SUDESTE        3040
                 SUL            2280
GLP              NORDESTE       6836
                 NORTE          5319
                 SUDESTE        3039
                 CENTRO OESTE   3037
                 SUL            2280
GNV              NORDESTE       5398
                 SUDESTE        3036
                 SUL            2269
                 CENTRO OESTE   1493
                 NORTE           444
ÓLEO DIESEL      NORDESTE       6840
                 NORTE          5319
                 CENTRO OESTE   3040
                 SUDESTE        3040
                 SUL            2280
ÓLEO DIESEL S10  NORDESTE       2814
                 NORTE          2184
                 SUDESTE        1252
                 CENTRO OESTE   1249
                 SUL             939

In [ ]:
#Como os preços da gasolina comum variaram no ano de 2018
gas2018= dados.query('PRODUTO == "GASOLINA COMUM" and ESTADO == "SAO PAULO" and ANO == 2018')
gas2018.head()

,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO
95351,2018-01-07,2018-01-13,SUDESTE,SAO PAULO,GASOLINA COMUM,1641,R$/l,3.988,0.156,3.499,4.599,0.411,0.039,3.577,0.104,2.99,3.951,0.029,1,2018
95502,2018-01-14,2018-01-20,SUDESTE,SAO PAULO,GASOLINA COMUM,1648,R$/l,4.002,0.155,3.549,4.499,0.412,0.039,3.59,0.102,2.99,3.9014,0.028,1,2018
95654,2018-01-21,2018-01-27,SUDESTE,SAO PAULO,GASOLINA COMUM,1648,R$/l,4.006,0.160,3.499,4.899,0.41,0.040,3.596,0.102,2.99,3.9014,0.028,1,2018
95806,2018-01-28,2018-02-03,SUDESTE,SAO PAULO,GASOLINA COMUM,1644,R$/l,4.019,0.156,3.579,4.699,0.423,0.039,3.596,0.107,2.924,3.9537,0.03,1,2018
95958,2018-02-04,2018-02-10,SUDESTE,SAO PAULO,GASOLINA COMUM,1646,R$/l,4.004,0.157,3.579,4.597,0.416,0.039,3.588,0.102,2.99,3.9537,0.028,2,2018

In [65]:
gas2018.describe()
gas2018['PREÇO MÉDIO REVENDA'].describe()

count    52.000000
mean      4.202769
std       0.180672
min       3.970000
25%       4.008000
50%       4.202000
75%       4.336250
max       4.512000
Name: PREÇO MÉDIO REVENDA, dtype: float64

In [ ]:
#Como os preços de Gasolina Comum e do Etanol em São Paulo variaram em 2018
gas_etanol2018= dados.query('PRODUTO in ["GASOLINA COMUM", "ETANOL HIDRATADO"] and ESTADO == "SAO PAULO" and ANO == 2018')
gas_etanol2018

,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO
95270,2018-01-07,2018-01-13,SUDESTE,SAO PAULO,ETANOL HIDRATADO,1664,R$/l,2.833,0.139,2.449,3.399,0.338,0.049,2.495,0.092,2.1842,2.8833,0.037,1,2018
95351,2018-01-07,2018-01-13,SUDESTE,SAO PAULO,GASOLINA COMUM,1641,R$/l,3.988,0.156,3.499,4.599,0.411,0.039,3.577,0.104,2.99,3.951,0.029,1,2018
95421,2018-01-14,2018-01-20,SUDESTE,SAO PAULO,ETANOL HIDRATADO,1661,R$/l,2.868,0.134,2.399,3.399,0.331,0.047,2.537,0.087,2.26,2.8471,0.034,1,2018
95502,2018-01-14,2018-01-20,SUDESTE,SAO PAULO,GASOLINA COMUM,1648,R$/l,4.002,0.155,3.549,4.499,0.412,0.039,3.59,0.102,2.99,3.9014,0.028,1,2018
95573,2018-01-21,2018-01-27,SUDESTE,SAO PAULO,ETANOL HIDRATADO,1662,R$/l,2.874,0.135,2.399,3.399,0.324,0.047,2.55,0.095,1.69,2.9722,0.037,1,2018
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102724,2018-12-16,2018-12-22,SUDESTE,SAO PAULO,GASOLINA COMUM,1637,R$/l,4.129,0.201,3.699,5.099,0.49,0.049,3.639,0.11,3.35,3.9892,0.03,12,2018
102793,2018-12-23,2018-12-29,SUDESTE,SAO PAULO,ETANOL HIDRATADO,1662,R$/l,2.644,0.163,2.149,3.699,0.305,0.062,2.339,0.094,2.0067,2.7443,0.04,12,2018
102874,2018-12-23,2018-12-29,SUDESTE,SAO PAULO,GASOLINA COMUM,1641,R$/l,4.129,0.201,3.699,4.999,0.484,0.049,3.645,0.107,3.35,3.9892,0.029,12,2018
102944,2018-12-30,2019-01-05,SUDESTE,SAO PAULO,ETANOL HIDRATADO,1661,R$/l,2.643,0.161,2.259,3.699,0.303,0.061,2.34,0.097,1.9072,2.7957,0.041,12,2018
103025,2018-12-30,2019-01-05,SUDESTE,SAO PAULO,GASOLINA COMUM,1643,R$/l,4.113,0.201,3.599,4.999,0.503,0.049,3.61,0.1,3.35,3.9585,0.028,12,2018

In [96]:
gas_etanol2018.describe()
gas_etanol2018['PREÇO MÉDIO REVENDA'].describe().to_frame()

       PREÇO MÉDIO REVENDA
count           104.000000
mean              3.457337
std               0.766239
min               2.393000
25%               2.726000
50%               3.431000
75%               4.199000
max               4.512000

In [97]:
gas_etanol2018.groupby('PRODUTO')['PREÇO MÉDIO REVENDA'].describe()

,count,mean,std,min,25%,50%,75%,max
PRODUTO,,,,,,,,
ETANOL HIDRATADO,52.0,2.711904,0.141365,2.393,2.6315,2.720,2.83825,2.892
GASOLINA COMUM,52.0,4.202769,0.180672,3.970,4.0080,4.202,4.33625,4.512