In [1]:
import pandas as pd

In [5]:
dados=pd.read_csv('GasPricesinBrazil_2004-2019_preprocessado_final.csv') 
dados

,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO
0,2004-05-09,2004-05-15,CENTRO OESTE,DISTRITO FEDERAL,ETANOL HIDRATADO,127,R$/l,1.288,0.016,1.190,1.350,0.463,0.012,0.825,0.110,0.4201,0.96660,0.133,5,2004
1,2004-05-09,2004-05-15,CENTRO OESTE,GOIAS,ETANOL HIDRATADO,387,R$/l,1.162,0.114,0.890,1.449,0.399,0.098,0.763,0.088,0.5013,1.05000,0.115,5,2004
2,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO,ETANOL HIDRATADO,192,R$/l,1.389,0.097,1.180,1.760,0.419,0.070,0.970,0.095,0.5614,1.16100,0.098,5,2004
3,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO DO SUL,ETANOL HIDRATADO,162,R$/l,1.262,0.070,1.090,1.509,0.432,0.055,0.830,0.119,0.5991,1.22242,0.143,5,2004
4,2004-05-09,2004-05-15,NORDESTE,ALAGOAS,ETANOL HIDRATADO,103,R$/l,1.181,0.078,1.050,1.400,0.240,0.066,0.941,0.077,0.7441,1.03170,0.082,5,2004
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
103387,2019-06-23,2019-06-29,NORDESTE,RIO GRANDE DO NORTE,GNV,7,R$/m3,3.574,0.065,3.499,3.690,0.818,0.018,2.756,0.000,2.7560,2.75600,0.000,6,2019
103388,2019-06-23,2019-06-29,SUL,RIO GRANDE DO SUL,GNV,23,R$/m3,3.401,0.129,3.230,3.789,0.950,0.038,2.451,0.402,1.9842,2.86610,0.164,6,2019
103389,2019-06-23,2019-06-29,SUL,SANTA CATARINA,GNV,24,R$/m3,2.912,0.190,2.699,3.499,0.914,0.065,1.998,0.000,1.9981,1.99810,0.000,6,2019
103390,2019-06-23,2019-06-29,SUDESTE,SAO PAULO,GNV,52,R$/m3,3.020,0.229,2.699,3.490,0.646,0.076,2.374,0.165,2.0179,2.50930,0.070,6,2019
103391,2019-06-23,2019-06-29,NORDESTE,SERGIPE,GNV,4,R$/m3,3.697,0.005,3.689,3.699,1.179,0.001,2.518,0.000,2.5175,2.51750,0.000,6,2019

In [6]:
dados.query('ANO != 2019')

,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO
0,2004-05-09,2004-05-15,CENTRO OESTE,DISTRITO FEDERAL,ETANOL HIDRATADO,127,R$/l,1.288,0.016,1.190,1.350,0.463,0.012,0.825,0.110,0.4201,0.96660,0.133,5,2004
1,2004-05-09,2004-05-15,CENTRO OESTE,GOIAS,ETANOL HIDRATADO,387,R$/l,1.162,0.114,0.890,1.449,0.399,0.098,0.763,0.088,0.5013,1.05000,0.115,5,2004
2,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO,ETANOL HIDRATADO,192,R$/l,1.389,0.097,1.180,1.760,0.419,0.070,0.970,0.095,0.5614,1.16100,0.098,5,2004
3,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO DO SUL,ETANOL HIDRATADO,162,R$/l,1.262,0.070,1.090,1.509,0.432,0.055,0.830,0.119,0.5991,1.22242,0.143,5,2004
4,2004-05-09,2004-05-15,NORDESTE,ALAGOAS,ETANOL HIDRATADO,103,R$/l,1.181,0.078,1.050,1.400,0.240,0.066,0.941,0.077,0.7441,1.03170,0.082,5,2004
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99734,2018-12-30,2019-01-05,SUDESTE,RIO DE JANEIRO,GNV,122,R$/m3,3.080,0.262,2.798,3.999,0.699,0.085,2.381,0.161,2.1670,2.86970,0.068,12,2018
99735,2018-12-30,2019-01-05,NORDESTE,RIO GRANDE DO NORTE,GNV,10,R$/m3,3.465,0.060,3.370,3.590,0.759,0.017,2.706,0.000,2.7059,2.70590,0.000,12,2018
99736,2018-12-30,2019-01-05,SUL,RIO GRANDE DO SUL,GNV,16,R$/m3,3.402,0.103,3.199,3.499,1.296,0.030,2.106,0.249,1.8775,2.37240,0.118,12,2018
99737,2018-12-30,2019-01-05,SUL,SANTA CATARINA,GNV,15,R$/m3,2.944,0.124,2.790,3.199,0.670,0.042,2.274,0.283,1.8738,2.27400,0.124,12,2018
99738,2018-12-30,2019-01-05,SUDESTE,SAO PAULO,GNV,41,R$/m3,2.353,0.451,1.999,3.429,0.467,0.192,1.886,0.250,1.6400,2.33200,0.133,12,2018

In [7]:
grupos= dados.groupby('PRODUTO')
grupos

In [9]:
grupos['REGIÃO'].value_counts().to_frame()

                               count
PRODUTO          REGIÃO
ETANOL HIDRATADO NORDESTE       7046
                 NORTE          5177
                 SUDESTE        3137
                 CENTRO OESTE   3122
                 SUL            2353
GASOLINA COMUM   NORDESTE       7063
                 NORTE          5464
                 SUDESTE        3140
                 CENTRO OESTE   3134
                 SUL            2354
GLP              NORDESTE       6410
                 NORTE          5327
                 SUDESTE        3137
                 CENTRO OESTE   3098
                 SUL            2343
GNV              NORDESTE       5176
                 SUDESTE        2841
                 SUL            1899
                 CENTRO OESTE    847
                 NORTE           243
ÓLEO DIESEL      NORDESTE       7061
                 NORTE          5465
                 SUDESTE        3140
                 CENTRO OESTE   3134
                 SUL            2354
ÓLEO DIESEL S10  NORDESTE       3032
                 NORTE          2324
                 SUDESTE        1349
                 CENTRO OESTE   1210
                 SUL            1012

In [10]:
(dados['PRODUTO'] =='GASOLINA COMUM') & (dados['ESTADO']=='SAO PAULO')

0         False
1         False
2         False
3         False
4         False
          ...
103387    False
103388    False
103389    False
103390    False
103391    False
Length: 103392, dtype: bool

In [12]:
gasolina_sp_2018=dados.query('PRODUTO== "GASOLINA COMUM" and ESTADO== "SAO PAULO" and ANO ==2018')
gasolina_sp_2018.head()

,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO
92319,2018-01-07,2018-01-13,SUDESTE,SAO PAULO,GASOLINA COMUM,1641,R$/l,3.988,0.156,3.499,4.599,0.411,0.039,3.577,0.104,2.990,3.9510,0.029,1,2018
92465,2018-01-14,2018-01-20,SUDESTE,SAO PAULO,GASOLINA COMUM,1648,R$/l,4.002,0.155,3.549,4.499,0.412,0.039,3.590,0.102,2.990,3.9014,0.028,1,2018
92610,2018-01-21,2018-01-27,SUDESTE,SAO PAULO,GASOLINA COMUM,1648,R$/l,4.006,0.160,3.499,4.899,0.410,0.040,3.596,0.102,2.990,3.9014,0.028,1,2018
92755,2018-01-28,2018-02-03,SUDESTE,SAO PAULO,GASOLINA COMUM,1644,R$/l,4.019,0.156,3.579,4.699,0.423,0.039,3.596,0.107,2.924,3.9537,0.030,1,2018
92901,2018-02-04,2018-02-10,SUDESTE,SAO PAULO,GASOLINA COMUM,1646,R$/l,4.004,0.157,3.579,4.597,0.416,0.039,3.588,0.102,2.990,3.9537,0.028,2,2018

In [13]:
gasolina_sp_2018.shape

(52, 20)

In [14]:
gasolina_sp_2018.describe()

,NÚMERO DE POSTOS PESQUISADOS,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO
count,52.000000,52.000000,52.000000,52.000000,52.000000,52.000000,52.000000,52.000000,52.000000,52.00000,52.000000,52.000000,52.000000,52.0
mean,1610.211538,4.202769,0.175500,3.671500,4.975750,0.442481,0.041750,3.760288,0.109654,3.31295,4.139454,0.029096,6.615385,2018.0
std,213.627432,0.180672,0.017955,0.163808,0.211198,0.063271,0.003965,0.163664,0.010712,0.26684,0.195897,0.002460,3.470627,0.0
min,102.000000,3.970000,0.150000,3.369000,4.499000,0.366000,0.034000,3.563000,0.087000,2.92400,3.887500,0.023000,1.000000,2018.0
25%,1639.000000,4.008000,0.159750,3.499000,4.899000,0.404500,0.039000,3.620250,0.102000,2.99000,3.965775,0.028000,4.000000,2018.0
50%,1642.000000,4.202000,0.173000,3.679000,4.999000,0.421500,0.040000,3.756500,0.108000,3.35000,4.095500,0.029000,7.000000,2018.0
75%,1644.000000,4.336250,0.189000,3.784000,5.099000,0.470250,0.044000,3.862250,0.116250,3.53250,4.259000,0.030000,9.250000,2018.0
max,1649.000000,4.512000,0.216000,3.969000,5.299000,0.640000,0.051000,4.085000,0.144000,3.76000,4.551000,0.037000,12.000000,2018.0

In [ ]:
gasolina_sp_2018['PREÇO MÉDIO REVENDA'].describe().to_frame

count    52.000000
mean      4.202769
std       0.180672
min       3.970000
25%       4.008000
50%       4.202000
75%       4.336250
max       4.512000
Name: PREÇO MÉDIO REVENDA, dtype: float64

In [18]:
dados.query('(PRODUTO== "GASOLINA COMUM" or PRODUTO =="ETANOL HIDRATADO") and ESTADO== "SAO PAULO" and ANO ==2018')

,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO
92238,2018-01-07,2018-01-13,SUDESTE,SAO PAULO,ETANOL HIDRATADO,1664,R$/l,2.833,0.139,2.449,3.399,0.338,0.049,2.495,0.092,2.1842,2.8833,0.037,1,2018
92319,2018-01-07,2018-01-13,SUDESTE,SAO PAULO,GASOLINA COMUM,1641,R$/l,3.988,0.156,3.499,4.599,0.411,0.039,3.577,0.104,2.9900,3.9510,0.029,1,2018
92384,2018-01-14,2018-01-20,SUDESTE,SAO PAULO,ETANOL HIDRATADO,1661,R$/l,2.868,0.134,2.399,3.399,0.331,0.047,2.537,0.087,2.2600,2.8471,0.034,1,2018
92465,2018-01-14,2018-01-20,SUDESTE,SAO PAULO,GASOLINA COMUM,1648,R$/l,4.002,0.155,3.549,4.499,0.412,0.039,3.590,0.102,2.9900,3.9014,0.028,1,2018
92529,2018-01-21,2018-01-27,SUDESTE,SAO PAULO,ETANOL HIDRATADO,1662,R$/l,2.874,0.135,2.399,3.399,0.324,0.047,2.550,0.095,1.6900,2.9722,0.037,1,2018
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99410,2018-12-16,2018-12-22,SUDESTE,SAO PAULO,GASOLINA COMUM,1637,R$/l,4.129,0.201,3.699,5.099,0.490,0.049,3.639,0.110,3.3500,3.9892,0.030,12,2018
99472,2018-12-23,2018-12-29,SUDESTE,SAO PAULO,ETANOL HIDRATADO,1662,R$/l,2.644,0.163,2.149,3.699,0.305,0.062,2.339,0.094,2.0067,2.7443,0.040,12,2018
99553,2018-12-23,2018-12-29,SUDESTE,SAO PAULO,GASOLINA COMUM,1641,R$/l,4.129,0.201,3.699,4.999,0.484,0.049,3.645,0.107,3.3500,3.9892,0.029,12,2018
99617,2018-12-30,2019-01-05,SUDESTE,SAO PAULO,ETANOL HIDRATADO,1661,R$/l,2.643,0.161,2.259,3.699,0.303,0.061,2.340,0.097,1.9072,2.7957,0.041,12,2018
99698,2018-12-30,2019-01-05,SUDESTE,SAO PAULO,GASOLINA COMUM,1643,R$/l,4.113,0.201,3.599,4.999,0.503,0.049,3.610,0.100,3.3500,3.9585,0.028,12,2018

In [ ]:
dados.query(('PRODUTO == "GASOLINA COMUM" or PRODUTO == "ETANOL HIDRATADO"') and ESTADO == "SAO PAULO" and ANO ==2018')

TokenError: ('EOF in multi-line statement', (2, 0))

In [21]:
lista_de_estados=["GASOLINA COMUM","ETANOL HIDRATADO"]
dados.query('PRODUTO in @lista_de_estados and ESTADO=="SAO PAULO" and==2018')

SyntaxError: Python keyword not valid identifier in numexpr query (<unknown>, line 1)