# Importando pandas

In [5]:
import pandas as pd

In [3]:
#carregando data sets corretamente usando o separado usando ";"
data = pd.read_csv('/home/youx/workspace-git/youxlab-treino-git/curso_dados/data.sets/ipynb.xave/GasPricesinBrazil_2004-2019.csv', sep=';') 
data

,Unnamed: 0,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,...,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO
0,0,2004-05-09,2004-05-15,CENTRO OESTE,DISTRITO FEDERAL,ETANOL HIDRATADO,127,R$/l,1.288,0.016,...,1.350,0.463,0.012,0.825,0.11,0.4201,0.9666,0.133,5,2004
1,1,2004-05-09,2004-05-15,CENTRO OESTE,GOIAS,ETANOL HIDRATADO,387,R$/l,1.162,0.114,...,1.449,0.399,0.098,0.763,0.088,0.5013,1.05,0.115,5,2004
2,2,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO,ETANOL HIDRATADO,192,R$/l,1.389,0.097,...,1.760,0.419,0.070,0.97,0.095,0.5614,1.161,0.098,5,2004
3,3,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO DO SUL,ETANOL HIDRATADO,162,R$/l,1.262,0.070,...,1.509,0.432,0.055,0.83,0.119,0.5991,1.22242,0.143,5,2004
4,4,2004-05-09,2004-05-15,NORDESTE,ALAGOAS,ETANOL HIDRATADO,103,R$/l,1.181,0.078,...,1.400,0.24,0.066,0.941,0.077,0.7441,1.0317,0.082,5,2004
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
106818,106818,2019-06-23,2019-06-29,NORDESTE,RIO GRANDE DO NORTE,GNV,7,R$/m3,3.574,0.065,...,3.690,0.818,0.018,2.756,0,2.756,2.756,0,6,2019
106819,106819,2019-06-23,2019-06-29,SUL,RIO GRANDE DO SUL,GNV,23,R$/m3,3.401,0.129,...,3.789,0.95,0.038,2.451,0.402,1.9842,2.8661,0.164,6,2019
106820,106820,2019-06-23,2019-06-29,SUL,SANTA CATARINA,GNV,24,R$/m3,2.912,0.190,...,3.499,0.914,0.065,1.998,0,1.9981,1.9981,0,6,2019
106821,106821,2019-06-23,2019-06-29,SUDESTE,SAO PAULO,GNV,52,R$/m3,3.020,0.229,...,3.490,0.646,0.076,2.374,0.165,2.0179,2.5093,0.07,6,2019
106822,106822,2019-06-23,2019-06-29,NORDESTE,SERGIPE,GNV,4,R$/m3,3.697,0.005,...,3.699,1.179,0.001,2.518,0,2.5175,2.5175,0,6,2019

In [4]:
# carregando a data sets com apenas 7 linhas 
data.head(7)

,Unnamed: 0,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,...,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO
0,0,2004-05-09,2004-05-15,CENTRO OESTE,DISTRITO FEDERAL,ETANOL HIDRATADO,127,R$/l,1.288,0.016,...,1.350,0.463,0.012,0.825,0.11,0.4201,0.9666,0.133,5,2004
1,1,2004-05-09,2004-05-15,CENTRO OESTE,GOIAS,ETANOL HIDRATADO,387,R$/l,1.162,0.114,...,1.449,0.399,0.098,0.763,0.088,0.5013,1.05,0.115,5,2004
2,2,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO,ETANOL HIDRATADO,192,R$/l,1.389,0.097,...,1.760,0.419,0.070,0.97,0.095,0.5614,1.161,0.098,5,2004
3,3,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO DO SUL,ETANOL HIDRATADO,162,R$/l,1.262,0.070,...,1.509,0.432,0.055,0.83,0.119,0.5991,1.22242,0.143,5,2004
4,4,2004-05-09,2004-05-15,NORDESTE,ALAGOAS,ETANOL HIDRATADO,103,R$/l,1.181,0.078,...,1.400,0.24,0.066,0.941,0.077,0.7441,1.0317,0.082,5,2004
5,5,2004-05-09,2004-05-15,NORDESTE,BAHIA,ETANOL HIDRATADO,408,R$/l,1.383,0.132,...,2.050,0.426,0.095,0.957,0.128,0.5686,1.35,0.134,5,2004
6,6,2004-05-09,2004-05-15,NORDESTE,CEARA,ETANOL HIDRATADO,278,R$/l,1.453,0.218,...,1.950,0.353,0.150,1.1,0.068,0.7332,1.294,0.062,5,2004

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 106823 entries, 0 to 106822
Data columns (total 21 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   Unnamed: 0                     106823 non-null  int64
 1   DATA INICIAL                   106823 non-null  object
 2   DATA FINAL                     106823 non-null  object
 3   REGIÃO                         106823 non-null  object
 4   ESTADO                         106823 non-null  object
 5   PRODUTO                        106823 non-null  object
 6   NÚMERO DE POSTOS PESQUISADOS   106823 non-null  int64
 7   UNIDADE DE MEDIDA              106823 non-null  object
 8   PREÇO MÉDIO REVENDA            106823 non-null  float64
 9   DESVIO PADRÃO REVENDA          106823 non-null  float64
 10  PREÇO MÍNIMO REVENDA           106823 non-null  float64
 11  PREÇO MÁXIMO REVENDA           106823 non-null  float64
 12  MARGEM MÉDIA REVENDA           106823 non-null  object
 13  COEF DE VARIAÇÃO REVENDA       106823 non-null  float64
 14  PREÇO MÉDIO DISTRIBUIÇÃO       106823 non-null  object
 15  DESVIO PADRÃO DISTRIBUIÇÃO     106823 non-null  object
 16  PREÇO MÍNIMO DISTRIBUIÇÃO      106823 non-null  object
 17  PREÇO MÁXIMO DISTRIBUIÇÃO      106823 non-null  object
 18  COEF DE VARIAÇÃO DISTRIBUIÇÃO  106823 non-null  object
 19  MÊS                            106823 non-null  int64
 20  ANO                            106823 non-null  int64
dtypes: float64(5), int64(4), object(12)
memory usage: 17.1+ MB

# Data Frame

In [6]:
type(data)

pandas.core.frame.DataFrame

<p>Podemos acessar as dimensões para o dataFrame</p>

In [7]:
data.shape

(106823, 21)

In [8]:
print(f'O dataFrame possui {data.shape[0]} linhas/observações e {data.shape[1]} colunas/atributos')

O dataFrame possui 106823 linhas/observações e 21 colunas/atributos

### Criando um dataFrame

In [9]:
# index , nomedojog , nome , ano de lancamento
# 0          Zelda  Link     1998
# 1          God    Kratos   2003
# 2          Mario  Luigi    1999
jogos_df = pd.DataFrame({
    'nomedojog' : ['Zelda ocarina of time','god of war','Mario Bros'],
    'nomedopers' : ['Link' , 'Kratos' , 'Luigi'],
    'Anolançado' : [1998, 2003, 1999],
    'eh_bom' : [True,True,False]
})

In [10]:
jogos_df

               nomedojog nomedopers  Anolançado  eh_bom
0  Zelda ocarina of time       Link        1998    True
1             god of war     Kratos        2003    True
2             Mario Bros      Luigi        1999   False

In [11]:
jogos_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   nomedojog   3 non-null      object
 1   nomedopers  3 non-null      object
 2   Anolançado  3 non-null      int64
 3   eh_bom      3 non-null      bool
dtypes: bool(1), int64(1), object(2)
memory usage: 203.0+ bytes

<h3>Renomeando os data frames</h3>

In [12]:
jogos_df.columns

Index(['nomedojog', 'nomedopers', 'Anolançado', 'eh_bom'], dtype='object')

<p>Original</p>

In [13]:
jogos_df

               nomedojog nomedopers  Anolançado  eh_bom
0  Zelda ocarina of time       Link        1998    True
1             god of war     Kratos        2003    True
2             Mario Bros      Luigi        1999   False

<p>Renomeando com a cópia do original</p>

In [14]:
jogos_df_renomados = jogos_df.rename(columns={
    'nomedojog' : 'Jogo',
    'nomedopers': 'Personagem',
    'Anolançado' : 'Lançamento',
    'eh_bom' : 'Bom' 
})

In [15]:
jogos_df_renomados

                    Jogo Personagem  Lançamento    Bom
0  Zelda ocarina of time       Link        1998   True
1             god of war     Kratos        2003   True
2             Mario Bros      Luigi        1999  False

<p>Alterando o original</p>

In [16]:
jogos_df.rename(columns={
    'nomedojog' : 'Jogo',
    'nomedopers': 'Personagem',
    'Anolançado' : 'Lançamento',
    'eh_bom' : 'Bom'
    },
    # para alterar o dataframe original use o paramêtro "inplace=True"
    inplace=True)

In [17]:
jogos_df

                    Jogo Personagem  Lançamento    Bom
0  Zelda ocarina of time       Link        1998   True
1             god of war     Kratos        2003   True
2             Mario Bros      Luigi        1999  False

<p>Renomeando com listas</p>

In [18]:
jogos_df.columns

Index(['Jogo', 'Personagem', 'Lançamento', 'Bom'], dtype='object')

In [19]:
jogos_df.columns = ['JOGOS' , 'PERSONAGEM' , 'LANÇAMENTO','BOM']

In [20]:
jogos_df

                   JOGOS PERSONAGEM  LANÇAMENTO    BOM
0  Zelda ocarina of time       Link        1998   True
1             god of war     Kratos        2003   True
2             Mario Bros      Luigi        1999  False

<h1>Series</h1>

In [21]:
data.head()

,Unnamed: 0,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,...,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO
0,0,2004-05-09,2004-05-15,CENTRO OESTE,DISTRITO FEDERAL,ETANOL HIDRATADO,127,R$/l,1.288,0.016,...,1.350,0.463,0.012,0.825,0.11,0.4201,0.9666,0.133,5,2004
1,1,2004-05-09,2004-05-15,CENTRO OESTE,GOIAS,ETANOL HIDRATADO,387,R$/l,1.162,0.114,...,1.449,0.399,0.098,0.763,0.088,0.5013,1.05,0.115,5,2004
2,2,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO,ETANOL HIDRATADO,192,R$/l,1.389,0.097,...,1.760,0.419,0.070,0.97,0.095,0.5614,1.161,0.098,5,2004
3,3,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO DO SUL,ETANOL HIDRATADO,162,R$/l,1.262,0.070,...,1.509,0.432,0.055,0.83,0.119,0.5991,1.22242,0.143,5,2004
4,4,2004-05-09,2004-05-15,NORDESTE,ALAGOAS,ETANOL HIDRATADO,103,R$/l,1.181,0.078,...,1.400,0.24,0.066,0.941,0.077,0.7441,1.0317,0.082,5,2004

In [22]:
type(data["ESTADO"])

pandas.core.series.Series

In [23]:
# Só e possivel fazer desse tipo se não conter caracteres inválidas como _ , . etc
type(data.ESTADO)

pandas.core.series.Series

In [24]:
# pode pegar um atribuito pela indexação dele como o exemplo abaixo 
data.iloc[1]

Unnamed: 0                                      1
DATA INICIAL                           2004-05-09
DATA FINAL                             2004-05-15
REGIÃO                               CENTRO OESTE
ESTADO                                      GOIAS
PRODUTO                          ETANOL HIDRATADO
NÚMERO DE POSTOS PESQUISADOS                  387
UNIDADE DE MEDIDA                            R$/l
PREÇO MÉDIO REVENDA                         1.162
DESVIO PADRÃO REVENDA                       0.114
PREÇO MÍNIMO REVENDA                         0.89
PREÇO MÁXIMO REVENDA                        1.449
MARGEM MÉDIA REVENDA                        0.399
COEF DE VARIAÇÃO REVENDA                    0.098
PREÇO MÉDIO DISTRIBUIÇÃO                    0.763
DESVIO PADRÃO DISTRIBUIÇÃO                  0.088
PREÇO MÍNIMO DISTRIBUIÇÃO                  0.5013
PREÇO MÁXIMO DISTRIBUIÇÃO                    1.05
COEF DE VARIAÇÃO DISTRIBUIÇÃO               0.115
MÊS                                             5
ANO                                          2004
Name: 1, dtype: object

<p>Criando series</p>

In [25]:
pd.Series([5.5 , 6.3 , 2.3])

0    5.5
1    6.3
2    2.3
dtype: float64

<p>Renomeando as series pelo indices</p>

In [26]:
pd.Series([5.5 , 6.3 , 9.3] , index=['Prova 1' , 'Prova 2' , 'Projeto'] , name='Notas do Júlio')

Prova 1    5.5
Prova 2    6.3
Projeto    9.3
Name: Notas do Júlio, dtype: float64

<h1>Atribuindo dados</h1>

In [27]:
data.head()

,Unnamed: 0,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,...,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO
0,0,2004-05-09,2004-05-15,CENTRO OESTE,DISTRITO FEDERAL,ETANOL HIDRATADO,127,R$/l,1.288,0.016,...,1.350,0.463,0.012,0.825,0.11,0.4201,0.9666,0.133,5,2004
1,1,2004-05-09,2004-05-15,CENTRO OESTE,GOIAS,ETANOL HIDRATADO,387,R$/l,1.162,0.114,...,1.449,0.399,0.098,0.763,0.088,0.5013,1.05,0.115,5,2004
2,2,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO,ETANOL HIDRATADO,192,R$/l,1.389,0.097,...,1.760,0.419,0.070,0.97,0.095,0.5614,1.161,0.098,5,2004
3,3,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO DO SUL,ETANOL HIDRATADO,162,R$/l,1.262,0.070,...,1.509,0.432,0.055,0.83,0.119,0.5991,1.22242,0.143,5,2004
4,4,2004-05-09,2004-05-15,NORDESTE,ALAGOAS,ETANOL HIDRATADO,103,R$/l,1.181,0.078,...,1.400,0.24,0.066,0.941,0.077,0.7441,1.0317,0.082,5,2004

In [28]:
# faça uma copia

In [29]:
data_copy_bkp = data['PRODUTO'].copy()

In [30]:
data_copy_bkp

0         ETANOL HIDRATADO
1         ETANOL HIDRATADO
2         ETANOL HIDRATADO
3         ETANOL HIDRATADO
4         ETANOL HIDRATADO
                ...
106818                 GNV
106819                 GNV
106820                 GNV
106821                 GNV
106822                 GNV
Name: PRODUTO, Length: 106823, dtype: object

In [31]:
# atribuindo em listas ou series no caso
nrows , ncolum = data.shape
nrows , ncolum

(106823, 21)

In [32]:
novos_produtos = [f'Produtos {i}' for i in range(nrows)]
novos_produtos

['Produtos 0',
 'Produtos 1',
 'Produtos 2',
 'Produtos 3',
 'Produtos 4',
 'Produtos 5',
 'Produtos 6',
 'Produtos 7',
 'Produtos 8',
 'Produtos 9',
 'Produtos 10',
 'Produtos 11',
 'Produtos 12',
 'Produtos 13',
 'Produtos 14',
 'Produtos 15',
 'Produtos 16',
 'Produtos 17',
 'Produtos 18',
 'Produtos 19',
 'Produtos 20',
 'Produtos 21',
 'Produtos 22',
 'Produtos 23',
 'Produtos 24',
 'Produtos 25',
 'Produtos 26',
 'Produtos 27',
 'Produtos 28',
 'Produtos 29',
 'Produtos 30',
 'Produtos 31',
 'Produtos 32',
 'Produtos 33',
 'Produtos 34',
 'Produtos 35',
 'Produtos 36',
 'Produtos 37',
 'Produtos 38',
 'Produtos 39',
 'Produtos 40',
 'Produtos 41',
 'Produtos 42',
 'Produtos 43',
 'Produtos 44',
 'Produtos 45',
 'Produtos 46',
 'Produtos 47',
 'Produtos 48',
 'Produtos 49',
 'Produtos 50',
 'Produtos 51',
 'Produtos 52',
 'Produtos 53',
 'Produtos 54',
 'Produtos 55',
 'Produtos 56',
 'Produtos 57',
 'Produtos 58',
 'Produtos 59',
 'Produtos 60',
 'Produtos 61',
 'Produtos 62',
 'Produtos 63',
 'Produtos 64',
 'Produtos 65',
 'Produtos 66',
 'Produtos 67',
 'Produtos 68',
 'Produtos 69',
 'Produtos 70',
 'Produtos 71',
 'Produtos 72',
 'Produtos 73',
 'Produtos 74',
 'Produtos 75',
 'Produtos 76',
 'Produtos 77',
 'Produtos 78',
 'Produtos 79',
 'Produtos 80',
 'Produtos 81',
 'Produtos 82',
 'Produtos 83',
 'Produtos 84',
 'Produtos 85',
 'Produtos 86',
 'Produtos 87',
 'Produtos 88',
 'Produtos 89',
 'Produtos 90',
 'Produtos 91',
 'Produtos 92',
 'Produtos 93',
 'Produtos 94',
 'Produtos 95',
 'Produtos 96',
 'Produtos 97',
 'Produtos 98',
 'Produtos 99',
 'Produtos 100',
 'Produtos 101',
 'Produtos 102',
 'Produtos 103',
 'Produtos 104',
 'Produtos 105',
 'Produtos 106',
 'Produtos 107',
 'Produtos 108',
 'Produtos 109',
 'Produtos 110',
 'Produtos 111',
 'Produtos 112',
 'Produtos 113',
 'Produtos 114',
 'Produtos 115',
 'Produtos 116',
 'Produtos 117',
 'Produtos 118',
 'Produtos 119',
 'Produtos 120',
 'Produtos 121',
 'Produtos 122',
 'Produtos 123',
 'Produtos 124',
 'Produtos 125',
 'Produtos 126',
 'Produtos 127',
 'Produtos 128',
 'Produtos 129',
 'Produtos 130',
 'Produtos 131',
 'Produtos 132',
 'Produtos 133',
 'Produtos 134',
 'Produtos 135',
 'Produtos 136',
 'Produtos 137',
 'Produtos 138',
 'Produtos 139',
 'Produtos 140',
 'Produtos 141',
 'Produtos 142',
 'Produtos 143',
 'Produtos 144',
 'Produtos 145',
 'Produtos 146',
 'Produtos 147',
 'Produtos 148',
 'Produtos 149',
 'Produtos 150',
 'Produtos 151',
 'Produtos 152',
 'Produtos 153',
 'Produtos 154',
 'Produtos 155',
 'Produtos 156',
 'Produtos 157',
 'Produtos 158',
 'Produtos 159',
 'Produtos 160',
 'Produtos 161',
 'Produtos 162',
 'Produtos 163',
 'Produtos 164',
 'Produtos 165',
 'Produtos 166',
 'Produtos 167',
 'Produtos 168',
 'Produtos 169',
 'Produtos 170',
 'Produtos 171',
 'Produtos 172',
 'Produtos 173',
 'Produtos 174',
 'Produtos 175',
 'Produtos 176',
 'Produtos 177',
 'Produtos 178',
 'Produtos 179',
 'Produtos 180',
 'Produtos 181',
 'Produtos 182',
 'Produtos 183',
 'Produtos 184',
 'Produtos 185',
 'Produtos 186',
 'Produtos 187',
 'Produtos 188',
 'Produtos 189',
 'Produtos 190',
 'Produtos 191',
 'Produtos 192',
 'Produtos 193',
 'Produtos 194',
 'Produtos 195',
 'Produtos 196',
 'Produtos 197',
 'Produtos 198',
 'Produtos 199',
 'Produtos 200',
 'Produtos 201',
 'Produtos 202',
 'Produtos 203',
 'Produtos 204',
 'Produtos 205',
 'Produtos 206',
 'Produtos 207',
 'Produtos 208',
 'Produtos 209',
 'Produtos 210',
 'Produtos 211',
 'Produtos 212',
 'Produtos 213',
 'Produtos 214',
 'Produtos 215',
 'Produtos 216',
 'Produtos 217',
 'Produtos 218',
 'Produtos 219',
 'Produtos 220',
 'Produtos 221',
 'Produtos 222',
 'Produtos 223',
 'Produtos 224',
 'Produtos 225',
 'Produtos 226',
 'Produtos 227',
 'Produtos 228',
 'Produtos 229',
 'Produtos 230',
 'Produtos 231',
 'Produtos 232',
 'Produtos 233',
 'Produtos 234',
 'Produtos 235',
 'Produtos 236',
 'Produtos 237',
 'Produtos 238',
 'Produtos 239',
 'Produtos 240',
 'Produtos 241',
 'Produtos 242',
 'Produtos 243',
 'Produtos 244',
 'Produtos 245',
 'Produtos 246',
 'Produtos 247',
 'Produtos 248',
 'Produtos 249',
 'Produtos 250',
 'Produtos 251',
 'Produtos 252',
 'Produtos 253',
 'Produtos 254',
 'Produtos 255',
 'Produtos 256',
 'Produtos 257',
 'Produtos 258',
 'Produtos 259',
 'Produtos 260',
 'Produtos 261',
 'Produtos 262',
 'Produtos 263',
 'Produtos 264',
 'Produtos 265',
 'Produtos 266',
 'Produtos 267',
 'Produtos 268',
 'Produtos 269',
 'Produtos 270',
 'Produtos 271',
 'Produtos 272',
 'Produtos 273',
 'Produtos 274',
 'Produtos 275',
 'Produtos 276',
 'Produtos 277',
 'Produtos 278',
 'Produtos 279',
 'Produtos 280',
 'Produtos 281',
 'Produtos 282',
 'Produtos 283',
 'Produtos 284',
 'Produtos 285',
 'Produtos 286',
 'Produtos 287',
 'Produtos 288',
 'Produtos 289',
 'Produtos 290',
 'Produtos 291',
 'Produtos 292',
 'Produtos 293',
 'Produtos 294',
 'Produtos 295',
 'Produtos 296',
 'Produtos 297',
 'Produtos 298',
 'Produtos 299',
 'Produtos 300',
 'Produtos 301',
 'Produtos 302',
 'Produtos 303',
 'Produtos 304',
 'Produtos 305',
 'Produtos 306',
 'Produtos 307',
 'Produtos 308',
 'Produtos 309',
 'Produtos 310',
 'Produtos 311',
 'Produtos 312',
 'Produtos 313',
 'Produtos 314',
 'Produtos 315',
 'Produtos 316',
 'Produtos 317',
 'Produtos 318',
 'Produtos 319',
 'Produtos 320',
 'Produtos 321',
 'Produtos 322',
 'Produtos 323',
 'Produtos 324',
 'Produtos 325',
 'Produtos 326',
 'Produtos 327',
 'Produtos 328',
 'Produtos 329',
 'Produtos 330',
 'Produtos 331',
 'Produtos 332',
 'Produtos 333',
 'Produtos 334',
 'Produtos 335',
 'Produtos 336',
 'Produtos 337',
 'Produtos 338',
 'Produtos 339',
 'Produtos 340',
 'Produtos 341',
 'Produtos 342',
 'Produtos 343',
 'Produtos 344',
 'Produtos 345',
 'Produtos 346',
 'Produtos 347',
 'Produtos 348',
 'Produtos 349',
 'Produtos 350',
 'Produtos 351',
 'Produtos 352',
 'Produtos 353',
 'Produtos 354',
 'Produtos 355',
 'Produtos 356',
 'Produtos 357',
 'Produtos 358',
 'Produtos 359',
 'Produtos 360',
 'Produtos 361',
 'Produtos 362',
 'Produtos 363',
 'Produtos 364',
 'Produtos 365',
 'Produtos 366',
 'Produtos 367',
 'Produtos 368',
 'Produtos 369',
 'Produtos 370',
 'Produtos 371',
 'Produtos 372',
 'Produtos 373',
 'Produtos 374',
 'Produtos 375',
 'Produtos 376',
 'Produtos 377',
 'Produtos 378',
 'Produtos 379',
 'Produtos 380',
 'Produtos 381',
 'Produtos 382',
 'Produtos 383',
 'Produtos 384',
 'Produtos 385',
 'Produtos 386',
 'Produtos 387',
 'Produtos 388',
 'Produtos 389',
 'Produtos 390',
 'Produtos 391',
 'Produtos 392',
 'Produtos 393',
 'Produtos 394',
 'Produtos 395',
 'Produtos 396',
 'Produtos 397',
 'Produtos 398',
 'Produtos 399',
 'Produtos 400',
 'Produtos 401',
 'Produtos 402',
 'Produtos 403',
 'Produtos 404',
 'Produtos 405',
 'Produtos 406',
 'Produtos 407',
 'Produtos 408',
 'Produtos 409',
 'Produtos 410',
 'Produtos 411',
 'Produtos 412',
 'Produtos 413',
 'Produtos 414',
 'Produtos 415',
 'Produtos 416',
 'Produtos 417',
 'Produtos 418',
 'Produtos 419',
 'Produtos 420',
 'Produtos 421',
 'Produtos 422',
 'Produtos 423',
 'Produtos 424',
 'Produtos 425',
 'Produtos 426',
 'Produtos 427',
 'Produtos 428',
 'Produtos 429',
 'Produtos 430',
 'Produtos 431',
 'Produtos 432',
 'Produtos 433',
 'Produtos 434',
 'Produtos 435',
 'Produtos 436',
 'Produtos 437',
 'Produtos 438',
 'Produtos 439',
 'Produtos 440',
 'Produtos 441',
 'Produtos 442',
 'Produtos 443',
 'Produtos 444',
 'Produtos 445',
 'Produtos 446',
 'Produtos 447',
 'Produtos 448',
 'Produtos 449',
 'Produtos 450',
 'Produtos 451',
 'Produtos 452',
 'Produtos 453',
 'Produtos 454',
 'Produtos 455',
 'Produtos 456',
 'Produtos 457',
 'Produtos 458',
 'Produtos 459',
 'Produtos 460',
 'Produtos 461',
 'Produtos 462',
 'Produtos 463',
 'Produtos 464',
 'Produtos 465',
 'Produtos 466',
 'Produtos 467',
 'Produtos 468',
 'Produtos 469',
 'Produtos 470',
 'Produtos 471',
 'Produtos 472',
 'Produtos 473',
 'Produtos 474',
 'Produtos 475',
 'Produtos 476',
 'Produtos 477',
 'Produtos 478',
 'Produtos 479',
 'Produtos 480',
 'Produtos 481',
 'Produtos 482',
 'Produtos 483',
 'Produtos 484',
 'Produtos 485',
 'Produtos 486',
 'Produtos 487',
 'Produtos 488',
 'Produtos 489',
 'Produtos 490',
 'Produtos 491',
 'Produtos 492',
 'Produtos 493',
 'Produtos 494',
 'Produtos 495',
 'Produtos 496',
 'Produtos 497',
 'Produtos 498',
 'Produtos 499',
 'Produtos 500',
 'Produtos 501',
 'Produtos 502',
 'Produtos 503',
 'Produtos 504',
 'Produtos 505',
 'Produtos 506',
 'Produtos 507',
 'Produtos 508',
 'Produtos 509',
 'Produtos 510',
 'Produtos 511',
 'Produtos 512',
 'Produtos 513',
 'Produtos 514',
 'Produtos 515',
 'Produtos 516',
 'Produtos 517',
 'Produtos 518',
 'Produtos 519',
 'Produtos 520',
 'Produtos 521',
 'Produtos 522',
 'Produtos 523',
 'Produtos 524',
 'Produtos 525',
 'Produtos 526',
 'Produtos 527',
 'Produtos 528',
 'Produtos 529',
 'Produtos 530',
 'Produtos 531',
 'Produtos 532',
 'Produtos 533',
 'Produtos 534',
 'Produtos 535',
 'Produtos 536',
 'Produtos 537',
 'Produtos 538',
 'Produtos 539',
 'Produtos 540',
 'Produtos 541',
 'Produtos 542',
 'Produtos 543',
 'Produtos 544',
 'Produtos 545',
 'Produtos 546',
 'Produtos 547',
 'Produtos 548',
 'Produtos 549',
 'Produtos 550',
 'Produtos 551',
 'Produtos 552',
 'Produtos 553',
 'Produtos 554',
 'Produtos 555',
 'Produtos 556',
 'Produtos 557',
 'Produtos 558',
 'Produtos 559',
 'Produtos 560',
 'Produtos 561',
 'Produtos 562',
 'Produtos 563',
 'Produtos 564',
 'Produtos 565',
 'Produtos 566',
 'Produtos 567',
 'Produtos 568',
 'Produtos 569',
 'Produtos 570',
 'Produtos 571',
 'Produtos 572',
 'Produtos 573',
 'Produtos 574',
 'Produtos 575',
 'Produtos 576',
 'Produtos 577',
 'Produtos 578',
 'Produtos 579',
 'Produtos 580',
 'Produtos 581',
 'Produtos 582',
 'Produtos 583',
 'Produtos 584',
 'Produtos 585',
 'Produtos 586',
 'Produtos 587',
 'Produtos 588',
 'Produtos 589',
 'Produtos 590',
 'Produtos 591',
 'Produtos 592',
 'Produtos 593',
 'Produtos 594',
 'Produtos 595',
 'Produtos 596',
 'Produtos 597',
 'Produtos 598',
 'Produtos 599',
 'Produtos 600',
 'Produtos 601',
 'Produtos 602',
 'Produtos 603',
 'Produtos 604',
 'Produtos 605',
 'Produtos 606',
 'Produtos 607',
 'Produtos 608',
 'Produtos 609',
 'Produtos 610',
 'Produtos 611',
 'Produtos 612',
 'Produtos 613',
 'Produtos 614',
 'Produtos 615',
 'Produtos 616',
 'Produtos 617',
 'Produtos 618',
 'Produtos 619',
 'Produtos 620',
 'Produtos 621',
 'Produtos 622',
 'Produtos 623',
 'Produtos 624',
 'Produtos 625',
 'Produtos 626',
 'Produtos 627',
 'Produtos 628',
 'Produtos 629',
 'Produtos 630',
 'Produtos 631',
 'Produtos 632',
 'Produtos 633',
 'Produtos 634',
 'Produtos 635',
 'Produtos 636',
 'Produtos 637',
 'Produtos 638',
 'Produtos 639',
 'Produtos 640',
 'Produtos 641',
 'Produtos 642',
 'Produtos 643',
 'Produtos 644',
 'Produtos 645',
 'Produtos 646',
 'Produtos 647',
 'Produtos 648',
 'Produtos 649',
 'Produtos 650',
 'Produtos 651',
 'Produtos 652',
 'Produtos 653',
 'Produtos 654',
 'Produtos 655',
 'Produtos 656',
 'Produtos 657',
 'Produtos 658',
 'Produtos 659',
 'Produtos 660',
 'Produtos 661',
 'Produtos 662',
 'Produtos 663',
 'Produtos 664',
 'Produtos 665',
 'Produtos 666',
 'Produtos 667',
 'Produtos 668',
 'Produtos 669',
 'Produtos 670',
 'Produtos 671',
 'Produtos 672',
 'Produtos 673',
 'Produtos 674',
 'Produtos 675',
 'Produtos 676',
 'Produtos 677',
 'Produtos 678',
 'Produtos 679',
 'Produtos 680',
 'Produtos 681',
 'Produtos 682',
 'Produtos 683',
 'Produtos 684',
 'Produtos 685',
 'Produtos 686',
 'Produtos 687',
 'Produtos 688',
 'Produtos 689',
 'Produtos 690',
 'Produtos 691',
 'Produtos 692',
 'Produtos 693',
 'Produtos 694',
 'Produtos 695',
 'Produtos 696',
 'Produtos 697',
 'Produtos 698',
 'Produtos 699',
 'Produtos 700',
 'Produtos 701',
 'Produtos 702',
 'Produtos 703',
 'Produtos 704',
 'Produtos 705',
 'Produtos 706',
 'Produtos 707',
 'Produtos 708',
 'Produtos 709',
 'Produtos 710',
 'Produtos 711',
 'Produtos 712',
 'Produtos 713',
 'Produtos 714',
 'Produtos 715',
 'Produtos 716',
 'Produtos 717',
 'Produtos 718',
 'Produtos 719',
 'Produtos 720',
 'Produtos 721',
 'Produtos 722',
 'Produtos 723',
 'Produtos 724',
 'Produtos 725',
 'Produtos 726',
 'Produtos 727',
 'Produtos 728',
 'Produtos 729',
 'Produtos 730',
 'Produtos 731',
 'Produtos 732',
 'Produtos 733',
 'Produtos 734',
 'Produtos 735',
 'Produtos 736',
 'Produtos 737',
 'Produtos 738',
 'Produtos 739',
 'Produtos 740',
 'Produtos 741',
 'Produtos 742',
 'Produtos 743',
 'Produtos 744',
 'Produtos 745',
 'Produtos 746',
 'Produtos 747',
 'Produtos 748',
 'Produtos 749',
 'Produtos 750',
 'Produtos 751',
 'Produtos 752',
 'Produtos 753',
 'Produtos 754',
 'Produtos 755',
 'Produtos 756',
 'Produtos 757',
 'Produtos 758',
 'Produtos 759',
 'Produtos 760',
 'Produtos 761',
 'Produtos 762',
 'Produtos 763',
 'Produtos 764',
 'Produtos 765',
 'Produtos 766',
 'Produtos 767',
 'Produtos 768',
 'Produtos 769',
 'Produtos 770',
 'Produtos 771',
 'Produtos 772',
 'Produtos 773',
 'Produtos 774',
 'Produtos 775',
 'Produtos 776',
 'Produtos 777',
 'Produtos 778',
 'Produtos 779',
 'Produtos 780',
 'Produtos 781',
 'Produtos 782',
 'Produtos 783',
 'Produtos 784',
 'Produtos 785',
 'Produtos 786',
 'Produtos 787',
 'Produtos 788',
 'Produtos 789',
 'Produtos 790',
 'Produtos 791',
 'Produtos 792',
 'Produtos 793',
 'Produtos 794',
 'Produtos 795',
 'Produtos 796',
 'Produtos 797',
 'Produtos 798',
 'Produtos 799',
 'Produtos 800',
 'Produtos 801',
 'Produtos 802',
 'Produtos 803',
 'Produtos 804',
 'Produtos 805',
 'Produtos 806',
 'Produtos 807',
 'Produtos 808',
 'Produtos 809',
 'Produtos 810',
 'Produtos 811',
 'Produtos 812',
 'Produtos 813',
 'Produtos 814',
 'Produtos 815',
 'Produtos 816',
 'Produtos 817',
 'Produtos 818',
 'Produtos 819',
 'Produtos 820',
 'Produtos 821',
 'Produtos 822',
 'Produtos 823',
 'Produtos 824',
 'Produtos 825',
 'Produtos 826',
 'Produtos 827',
 'Produtos 828',
 'Produtos 829',
 'Produtos 830',
 'Produtos 831',
 'Produtos 832',
 'Produtos 833',
 'Produtos 834',
 'Produtos 835',
 'Produtos 836',
 'Produtos 837',
 'Produtos 838',
 'Produtos 839',
 'Produtos 840',
 'Produtos 841',
 'Produtos 842',
 'Produtos 843',
 'Produtos 844',
 'Produtos 845',
 'Produtos 846',
 'Produtos 847',
 'Produtos 848',
 'Produtos 849',
 'Produtos 850',
 'Produtos 851',
 'Produtos 852',
 'Produtos 853',
 'Produtos 854',
 'Produtos 855',
 'Produtos 856',
 'Produtos 857',
 'Produtos 858',
 'Produtos 859',
 'Produtos 860',
 'Produtos 861',
 'Produtos 862',
 'Produtos 863',
 'Produtos 864',
 'Produtos 865',
 'Produtos 866',
 'Produtos 867',
 'Produtos 868',
 'Produtos 869',
 'Produtos 870',
 'Produtos 871',
 'Produtos 872',
 'Produtos 873',
 'Produtos 874',
 'Produtos 875',
 'Produtos 876',
 'Produtos 877',
 'Produtos 878',
 'Produtos 879',
 'Produtos 880',
 'Produtos 881',
 'Produtos 882',
 'Produtos 883',
 'Produtos 884',
 'Produtos 885',
 'Produtos 886',
 'Produtos 887',
 'Produtos 888',
 'Produtos 889',
 'Produtos 890',
 'Produtos 891',
 'Produtos 892',
 'Produtos 893',
 'Produtos 894',
 'Produtos 895',
 'Produtos 896',
 'Produtos 897',
 'Produtos 898',
 'Produtos 899',
 'Produtos 900',
 'Produtos 901',
 'Produtos 902',
 'Produtos 903',
 'Produtos 904',
 'Produtos 905',
 'Produtos 906',
 'Produtos 907',
 'Produtos 908',
 'Produtos 909',
 'Produtos 910',
 'Produtos 911',
 'Produtos 912',
 'Produtos 913',
 'Produtos 914',
 'Produtos 915',
 'Produtos 916',
 'Produtos 917',
 'Produtos 918',
 'Produtos 919',
 'Produtos 920',
 'Produtos 921',
 'Produtos 922',
 'Produtos 923',
 'Produtos 924',
 'Produtos 925',
 'Produtos 926',
 'Produtos 927',
 'Produtos 928',
 'Produtos 929',
 'Produtos 930',
 'Produtos 931',
 'Produtos 932',
 'Produtos 933',
 'Produtos 934',
 'Produtos 935',
 'Produtos 936',
 'Produtos 937',
 'Produtos 938',
 'Produtos 939',
 'Produtos 940',
 'Produtos 941',
 'Produtos 942',
 'Produtos 943',
 'Produtos 944',
 'Produtos 945',
 'Produtos 946',
 'Produtos 947',
 'Produtos 948',
 'Produtos 949',
 'Produtos 950',
 'Produtos 951',
 'Produtos 952',
 'Produtos 953',
 'Produtos 954',
 'Produtos 955',
 'Produtos 956',
 'Produtos 957',
 'Produtos 958',
 'Produtos 959',
 'Produtos 960',
 'Produtos 961',
 'Produtos 962',
 'Produtos 963',
 'Produtos 964',
 'Produtos 965',
 'Produtos 966',
 'Produtos 967',
 'Produtos 968',
 'Produtos 969',
 'Produtos 970',
 'Produtos 971',
 'Produtos 972',
 'Produtos 973',
 'Produtos 974',
 'Produtos 975',
 'Produtos 976',
 'Produtos 977',
 'Produtos 978',
 'Produtos 979',
 'Produtos 980',
 'Produtos 981',
 'Produtos 982',
 'Produtos 983',
 'Produtos 984',
 'Produtos 985',
 'Produtos 986',
 'Produtos 987',
 'Produtos 988',
 'Produtos 989',
 'Produtos 990',
 'Produtos 991',
 'Produtos 992',
 'Produtos 993',
 'Produtos 994',
 'Produtos 995',
 'Produtos 996',
 'Produtos 997',
 'Produtos 998',
 'Produtos 999',
 ...]

In [33]:
data['PRODUTO'] = novos_produtos
data.PRODUTO

0              Produtos 0
1              Produtos 1
2              Produtos 2
3              Produtos 3
4              Produtos 4
               ...
106818    Produtos 106818
106819    Produtos 106819
106820    Produtos 106820
106821    Produtos 106821
106822    Produtos 106822
Name: PRODUTO, Length: 106823, dtype: object

In [34]:
data.head()

,Unnamed: 0,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,...,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO
0,0,2004-05-09,2004-05-15,CENTRO OESTE,DISTRITO FEDERAL,Produtos 0,127,R$/l,1.288,0.016,...,1.350,0.463,0.012,0.825,0.11,0.4201,0.9666,0.133,5,2004
1,1,2004-05-09,2004-05-15,CENTRO OESTE,GOIAS,Produtos 1,387,R$/l,1.162,0.114,...,1.449,0.399,0.098,0.763,0.088,0.5013,1.05,0.115,5,2004
2,2,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO,Produtos 2,192,R$/l,1.389,0.097,...,1.760,0.419,0.070,0.97,0.095,0.5614,1.161,0.098,5,2004
3,3,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO DO SUL,Produtos 3,162,R$/l,1.262,0.070,...,1.509,0.432,0.055,0.83,0.119,0.5991,1.22242,0.143,5,2004
4,4,2004-05-09,2004-05-15,NORDESTE,ALAGOAS,Produtos 4,103,R$/l,1.181,0.078,...,1.400,0.24,0.066,0.941,0.077,0.7441,1.0317,0.082,5,2004

In [35]:
print(data['PRODUTO'])
print('\n')
print(data_copy_bkp)

0              Produtos 0
1              Produtos 1
2              Produtos 2
3              Produtos 3
4              Produtos 4
               ...
106818    Produtos 106818
106819    Produtos 106819
106820    Produtos 106820
106821    Produtos 106821
106822    Produtos 106822
Name: PRODUTO, Length: 106823, dtype: object


0         ETANOL HIDRATADO
1         ETANOL HIDRATADO
2         ETANOL HIDRATADO
3         ETANOL HIDRATADO
4         ETANOL HIDRATADO
                ...
106818                 GNV
106819                 GNV
106820                 GNV
106821                 GNV
106822                 GNV
Name: PRODUTO, Length: 106823, dtype: object

<p>Voltando para oque era antes de manipular</p>

In [36]:
data.head()

,Unnamed: 0,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,...,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO
0,0,2004-05-09,2004-05-15,CENTRO OESTE,DISTRITO FEDERAL,Produtos 0,127,R$/l,1.288,0.016,...,1.350,0.463,0.012,0.825,0.11,0.4201,0.9666,0.133,5,2004
1,1,2004-05-09,2004-05-15,CENTRO OESTE,GOIAS,Produtos 1,387,R$/l,1.162,0.114,...,1.449,0.399,0.098,0.763,0.088,0.5013,1.05,0.115,5,2004
2,2,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO,Produtos 2,192,R$/l,1.389,0.097,...,1.760,0.419,0.070,0.97,0.095,0.5614,1.161,0.098,5,2004
3,3,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO DO SUL,Produtos 3,162,R$/l,1.262,0.070,...,1.509,0.432,0.055,0.83,0.119,0.5991,1.22242,0.143,5,2004
4,4,2004-05-09,2004-05-15,NORDESTE,ALAGOAS,Produtos 4,103,R$/l,1.181,0.078,...,1.400,0.24,0.066,0.941,0.077,0.7441,1.0317,0.082,5,2004

In [37]:
data['PRODUTO'] = data_copy_bkp
data.head()

,Unnamed: 0,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,...,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO
0,0,2004-05-09,2004-05-15,CENTRO OESTE,DISTRITO FEDERAL,ETANOL HIDRATADO,127,R$/l,1.288,0.016,...,1.350,0.463,0.012,0.825,0.11,0.4201,0.9666,0.133,5,2004
1,1,2004-05-09,2004-05-15,CENTRO OESTE,GOIAS,ETANOL HIDRATADO,387,R$/l,1.162,0.114,...,1.449,0.399,0.098,0.763,0.088,0.5013,1.05,0.115,5,2004
2,2,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO,ETANOL HIDRATADO,192,R$/l,1.389,0.097,...,1.760,0.419,0.070,0.97,0.095,0.5614,1.161,0.098,5,2004
3,3,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO DO SUL,ETANOL HIDRATADO,162,R$/l,1.262,0.070,...,1.509,0.432,0.055,0.83,0.119,0.5991,1.22242,0.143,5,2004
4,4,2004-05-09,2004-05-15,NORDESTE,ALAGOAS,ETANOL HIDRATADO,103,R$/l,1.181,0.078,...,1.400,0.24,0.066,0.941,0.077,0.7441,1.0317,0.082,5,2004

<h1 style="color: purple">Criando novas colunas</h1>

In [38]:
data.head()

,Unnamed: 0,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,...,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO
0,0,2004-05-09,2004-05-15,CENTRO OESTE,DISTRITO FEDERAL,ETANOL HIDRATADO,127,R$/l,1.288,0.016,...,1.350,0.463,0.012,0.825,0.11,0.4201,0.9666,0.133,5,2004
1,1,2004-05-09,2004-05-15,CENTRO OESTE,GOIAS,ETANOL HIDRATADO,387,R$/l,1.162,0.114,...,1.449,0.399,0.098,0.763,0.088,0.5013,1.05,0.115,5,2004
2,2,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO,ETANOL HIDRATADO,192,R$/l,1.389,0.097,...,1.760,0.419,0.070,0.97,0.095,0.5614,1.161,0.098,5,2004
3,3,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO DO SUL,ETANOL HIDRATADO,162,R$/l,1.262,0.070,...,1.509,0.432,0.055,0.83,0.119,0.5991,1.22242,0.143,5,2004
4,4,2004-05-09,2004-05-15,NORDESTE,ALAGOAS,ETANOL HIDRATADO,103,R$/l,1.181,0.078,...,1.400,0.24,0.066,0.941,0.077,0.7441,1.0317,0.082,5,2004

In [39]:
data['nota sem noção'] = 'DEFAULT'
data.head()

,Unnamed: 0,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,...,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO,nota sem noção
0,0,2004-05-09,2004-05-15,CENTRO OESTE,DISTRITO FEDERAL,ETANOL HIDRATADO,127,R$/l,1.288,0.016,...,0.463,0.012,0.825,0.11,0.4201,0.9666,0.133,5,2004,DEFAULT
1,1,2004-05-09,2004-05-15,CENTRO OESTE,GOIAS,ETANOL HIDRATADO,387,R$/l,1.162,0.114,...,0.399,0.098,0.763,0.088,0.5013,1.05,0.115,5,2004,DEFAULT
2,2,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO,ETANOL HIDRATADO,192,R$/l,1.389,0.097,...,0.419,0.070,0.97,0.095,0.5614,1.161,0.098,5,2004,DEFAULT
3,3,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO DO SUL,ETANOL HIDRATADO,162,R$/l,1.262,0.070,...,0.432,0.055,0.83,0.119,0.5991,1.22242,0.143,5,2004,DEFAULT
4,4,2004-05-09,2004-05-15,NORDESTE,ALAGOAS,ETANOL HIDRATADO,103,R$/l,1.181,0.078,...,0.24,0.066,0.941,0.077,0.7441,1.0317,0.082,5,2004,DEFAULT

In [40]:
data['PREÇO MÉDIO REVENDA (doláres)'] = data['PREÇO MÉDIO REVENDA'] * 6.0
data.head()

,Unnamed: 0,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,...,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO,nota sem noção,PREÇO MÉDIO REVENDA (doláres)
0,0,2004-05-09,2004-05-15,CENTRO OESTE,DISTRITO FEDERAL,ETANOL HIDRATADO,127,R$/l,1.288,0.016,...,0.012,0.825,0.11,0.4201,0.9666,0.133,5,2004,DEFAULT,7.728
1,1,2004-05-09,2004-05-15,CENTRO OESTE,GOIAS,ETANOL HIDRATADO,387,R$/l,1.162,0.114,...,0.098,0.763,0.088,0.5013,1.05,0.115,5,2004,DEFAULT,6.972
2,2,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO,ETANOL HIDRATADO,192,R$/l,1.389,0.097,...,0.070,0.97,0.095,0.5614,1.161,0.098,5,2004,DEFAULT,8.334
3,3,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO DO SUL,ETANOL HIDRATADO,162,R$/l,1.262,0.070,...,0.055,0.83,0.119,0.5991,1.22242,0.143,5,2004,DEFAULT,7.572
4,4,2004-05-09,2004-05-15,NORDESTE,ALAGOAS,ETANOL HIDRATADO,103,R$/l,1.181,0.078,...,0.066,0.941,0.077,0.7441,1.0317,0.082,5,2004,DEFAULT,7.086

<h1>Indices</h1>

In [41]:
data

,Unnamed: 0,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,...,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO,nota sem noção,PREÇO MÉDIO REVENDA (doláres)
0,0,2004-05-09,2004-05-15,CENTRO OESTE,DISTRITO FEDERAL,ETANOL HIDRATADO,127,R$/l,1.288,0.016,...,0.012,0.825,0.11,0.4201,0.9666,0.133,5,2004,DEFAULT,7.728
1,1,2004-05-09,2004-05-15,CENTRO OESTE,GOIAS,ETANOL HIDRATADO,387,R$/l,1.162,0.114,...,0.098,0.763,0.088,0.5013,1.05,0.115,5,2004,DEFAULT,6.972
2,2,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO,ETANOL HIDRATADO,192,R$/l,1.389,0.097,...,0.070,0.97,0.095,0.5614,1.161,0.098,5,2004,DEFAULT,8.334
3,3,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO DO SUL,ETANOL HIDRATADO,162,R$/l,1.262,0.070,...,0.055,0.83,0.119,0.5991,1.22242,0.143,5,2004,DEFAULT,7.572
4,4,2004-05-09,2004-05-15,NORDESTE,ALAGOAS,ETANOL HIDRATADO,103,R$/l,1.181,0.078,...,0.066,0.941,0.077,0.7441,1.0317,0.082,5,2004,DEFAULT,7.086
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
106818,106818,2019-06-23,2019-06-29,NORDESTE,RIO GRANDE DO NORTE,GNV,7,R$/m3,3.574,0.065,...,0.018,2.756,0,2.756,2.756,0,6,2019,DEFAULT,21.444
106819,106819,2019-06-23,2019-06-29,SUL,RIO GRANDE DO SUL,GNV,23,R$/m3,3.401,0.129,...,0.038,2.451,0.402,1.9842,2.8661,0.164,6,2019,DEFAULT,20.406
106820,106820,2019-06-23,2019-06-29,SUL,SANTA CATARINA,GNV,24,R$/m3,2.912,0.190,...,0.065,1.998,0,1.9981,1.9981,0,6,2019,DEFAULT,17.472
106821,106821,2019-06-23,2019-06-29,SUDESTE,SAO PAULO,GNV,52,R$/m3,3.020,0.229,...,0.076,2.374,0.165,2.0179,2.5093,0.07,6,2019,DEFAULT,18.120
106822,106822,2019-06-23,2019-06-29,NORDESTE,SERGIPE,GNV,4,R$/m3,3.697,0.005,...,0.001,2.518,0,2.5175,2.5175,0,6,2019,DEFAULT,22.182

In [42]:
data.index

RangeIndex(start=0, stop=106823, step=1)

<p>Criando indices</p>

In [43]:
pesquisa_de_consoles = pd.DataFrame(
    {
    'bom' : [3.1 , 2.1 , 5.1],
    'medio' : [5.1 , 4.1 , 9.1],
    'pessimo' : [3.1 , 5.1 , 7.1]
    }, index=['Switch' , 'Xbox' , 'Playstion'])

In [44]:
pesquisa_de_consoles

           bom  medio  pessimo
Switch     3.1    5.1      3.1
Xbox       2.1    4.1      5.1
Playstion  5.1    9.1      7.1

In [45]:
pesquisa_de_consoles.index

Index(['Switch', 'Xbox', 'Playstion'], dtype='object')

<h1>Seleçao de indices</h1>

In [46]:
data

,Unnamed: 0,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,...,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO,nota sem noção,PREÇO MÉDIO REVENDA (doláres)
0,0,2004-05-09,2004-05-15,CENTRO OESTE,DISTRITO FEDERAL,ETANOL HIDRATADO,127,R$/l,1.288,0.016,...,0.012,0.825,0.11,0.4201,0.9666,0.133,5,2004,DEFAULT,7.728
1,1,2004-05-09,2004-05-15,CENTRO OESTE,GOIAS,ETANOL HIDRATADO,387,R$/l,1.162,0.114,...,0.098,0.763,0.088,0.5013,1.05,0.115,5,2004,DEFAULT,6.972
2,2,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO,ETANOL HIDRATADO,192,R$/l,1.389,0.097,...,0.070,0.97,0.095,0.5614,1.161,0.098,5,2004,DEFAULT,8.334
3,3,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO DO SUL,ETANOL HIDRATADO,162,R$/l,1.262,0.070,...,0.055,0.83,0.119,0.5991,1.22242,0.143,5,2004,DEFAULT,7.572
4,4,2004-05-09,2004-05-15,NORDESTE,ALAGOAS,ETANOL HIDRATADO,103,R$/l,1.181,0.078,...,0.066,0.941,0.077,0.7441,1.0317,0.082,5,2004,DEFAULT,7.086
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
106818,106818,2019-06-23,2019-06-29,NORDESTE,RIO GRANDE DO NORTE,GNV,7,R$/m3,3.574,0.065,...,0.018,2.756,0,2.756,2.756,0,6,2019,DEFAULT,21.444
106819,106819,2019-06-23,2019-06-29,SUL,RIO GRANDE DO SUL,GNV,23,R$/m3,3.401,0.129,...,0.038,2.451,0.402,1.9842,2.8661,0.164,6,2019,DEFAULT,20.406
106820,106820,2019-06-23,2019-06-29,SUL,SANTA CATARINA,GNV,24,R$/m3,2.912,0.190,...,0.065,1.998,0,1.9981,1.9981,0,6,2019,DEFAULT,17.472
106821,106821,2019-06-23,2019-06-29,SUDESTE,SAO PAULO,GNV,52,R$/m3,3.020,0.229,...,0.076,2.374,0.165,2.0179,2.5093,0.07,6,2019,DEFAULT,18.120
106822,106822,2019-06-23,2019-06-29,NORDESTE,SERGIPE,GNV,4,R$/m3,3.697,0.005,...,0.001,2.518,0,2.5175,2.5175,0,6,2019,DEFAULT,22.182

In [47]:
data.iloc[1]

Unnamed: 0                                      1
DATA INICIAL                           2004-05-09
DATA FINAL                             2004-05-15
REGIÃO                               CENTRO OESTE
ESTADO                                      GOIAS
PRODUTO                          ETANOL HIDRATADO
NÚMERO DE POSTOS PESQUISADOS                  387
UNIDADE DE MEDIDA                            R$/l
PREÇO MÉDIO REVENDA                         1.162
DESVIO PADRÃO REVENDA                       0.114
PREÇO MÍNIMO REVENDA                         0.89
PREÇO MÁXIMO REVENDA                        1.449
MARGEM MÉDIA REVENDA                        0.399
COEF DE VARIAÇÃO REVENDA                    0.098
PREÇO MÉDIO DISTRIBUIÇÃO                    0.763
DESVIO PADRÃO DISTRIBUIÇÃO                  0.088
PREÇO MÍNIMO DISTRIBUIÇÃO                  0.5013
PREÇO MÁXIMO DISTRIBUIÇÃO                    1.05
COEF DE VARIAÇÃO DISTRIBUIÇÃO               0.115
MÊS                                             5
ANO                                          2004
nota sem noção                            DEFAULT
PREÇO MÉDIO REVENDA (doláres)               6.972
Name: 1, dtype: object

In [48]:
data.iloc[:6]

,Unnamed: 0,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,...,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO,nota sem noção,PREÇO MÉDIO REVENDA (doláres)
0,0,2004-05-09,2004-05-15,CENTRO OESTE,DISTRITO FEDERAL,ETANOL HIDRATADO,127,R$/l,1.288,0.016,...,0.012,0.825,0.11,0.4201,0.9666,0.133,5,2004,DEFAULT,7.728
1,1,2004-05-09,2004-05-15,CENTRO OESTE,GOIAS,ETANOL HIDRATADO,387,R$/l,1.162,0.114,...,0.098,0.763,0.088,0.5013,1.05,0.115,5,2004,DEFAULT,6.972
2,2,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO,ETANOL HIDRATADO,192,R$/l,1.389,0.097,...,0.070,0.97,0.095,0.5614,1.161,0.098,5,2004,DEFAULT,8.334
3,3,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO DO SUL,ETANOL HIDRATADO,162,R$/l,1.262,0.070,...,0.055,0.83,0.119,0.5991,1.22242,0.143,5,2004,DEFAULT,7.572
4,4,2004-05-09,2004-05-15,NORDESTE,ALAGOAS,ETANOL HIDRATADO,103,R$/l,1.181,0.078,...,0.066,0.941,0.077,0.7441,1.0317,0.082,5,2004,DEFAULT,7.086
5,5,2004-05-09,2004-05-15,NORDESTE,BAHIA,ETANOL HIDRATADO,408,R$/l,1.383,0.132,...,0.095,0.957,0.128,0.5686,1.35,0.134,5,2004,DEFAULT,8.298

In [49]:
data.iloc[[1,8,9]]

,Unnamed: 0,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,...,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO,nota sem noção,PREÇO MÉDIO REVENDA (doláres)
1,1,2004-05-09,2004-05-15,CENTRO OESTE,GOIAS,ETANOL HIDRATADO,387,R$/l,1.162,0.114,...,0.098,0.763,0.088,0.5013,1.05,0.115,5,2004,DEFAULT,6.972
8,8,2004-05-09,2004-05-15,NORDESTE,PARAIBA,ETANOL HIDRATADO,125,R$/l,1.284,0.130,...,0.101,0.931,0.072,0.7577,1.2972,0.077,5,2004,DEFAULT,7.704
9,9,2004-05-09,2004-05-15,NORDESTE,PERNAMBUCO,ETANOL HIDRATADO,423,R$/l,1.224,0.141,...,0.115,0.947,0.091,0.5643,1.3541,0.096,5,2004,DEFAULT,7.344

<p>Filtrando os estados do nortes usando o iloc</p>

In [50]:
localizar_estados_nortes = data.iloc[9:101]

In [51]:
localizar_estados_nortes.head(50)

,Unnamed: 0,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,...,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO,nota sem noção,PREÇO MÉDIO REVENDA (doláres)
9,9,2004-05-09,2004-05-15,NORDESTE,PERNAMBUCO,ETANOL HIDRATADO,423,R$/l,1.224,0.141,...,0.115,0.947,0.091,0.5643,1.3541,0.096,5,2004,DEFAULT,7.344
10,10,2004-05-09,2004-05-15,NORDESTE,PIAUI,ETANOL HIDRATADO,89,R$/l,1.573,0.134,...,0.085,1.079,0.078,0.8857,1.2499,0.072,5,2004,DEFAULT,9.438
11,11,2004-05-09,2004-05-15,NORDESTE,RIO GRANDE DO NORTE,ETANOL HIDRATADO,131,R$/l,1.276,0.116,...,0.091,0.944,0.078,0.7119,1.1386,0.083,5,2004,DEFAULT,7.656
12,12,2004-05-09,2004-05-15,NORDESTE,SERGIPE,ETANOL HIDRATADO,57,R$/l,1.301,0.109,...,0.084,0.98,0.052,0.8267,1.1059,0.053,5,2004,DEFAULT,7.806
13,13,2004-05-09,2004-05-15,NORTE,ACRE,ETANOL HIDRATADO,33,R$/l,1.805,0.134,...,0.074,1.116,0.171,0.767,1.2992,0.153,5,2004,DEFAULT,10.830
14,14,2004-05-09,2004-05-15,NORTE,AMAPA,ETANOL HIDRATADO,15,R$/l,1.785,0.035,...,0.020,1.373,0.167,0.8339,1.4912,0.122,5,2004,DEFAULT,10.710
15,15,2004-05-09,2004-05-15,NORTE,AMAZONAS,ETANOL HIDRATADO,53,R$/l,1.578,0.123,...,0.078,1.137,0.068,0.9515,1.2109,0.06,5,2004,DEFAULT,9.468
16,16,2004-05-09,2004-05-15,NORTE,PARA,ETANOL HIDRATADO,104,R$/l,1.914,0.246,...,0.129,1.378,0.237,0.7564,1.8908,0.172,5,2004,DEFAULT,11.484
17,17,2004-05-09,2004-05-15,NORTE,RONDONIA,ETANOL HIDRATADO,97,R$/l,1.545,0.141,...,0.091,1.012,0.149,0.52,1.3306,0.147,5,2004,DEFAULT,9.270
18,18,2004-05-09,2004-05-15,NORTE,RORAIMA,ETANOL HIDRATADO,14,R$/l,1.300,0.000,...,0.000,1.098,0.096,0.9798,1.3577,0.087,5,2004,DEFAULT,7.800
19,19,2004-05-09,2004-05-15,NORTE,TOCANTINS,ETANOL HIDRATADO,71,R$/l,1.226,0.081,...,0.066,0.68,0.114,0.51022,1.035,0.168,5,2004,DEFAULT,7.356
20,20,2004-05-09,2004-05-15,SUDESTE,ESPIRITO SANTO,ETANOL HIDRATADO,306,R$/l,1.148,0.116,...,0.101,0.881,0.095,0.6259,1.1381,0.108,5,2004,DEFAULT,6.888
21,21,2004-05-09,2004-05-15,SUDESTE,MINAS GERAIS,ETANOL HIDRATADO,1238,R$/l,1.205,0.120,...,0.100,0.816,0.123,0.3797,1.437,0.151,5,2004,DEFAULT,7.230
22,22,2004-05-09,2004-05-15,SUDESTE,RIO DE JANEIRO,ETANOL HIDRATADO,952,R$/l,1.098,0.154,...,0.140,0.786,0.173,0.326,1.263,0.22,5,2004,DEFAULT,6.588
23,23,2004-05-09,2004-05-15,SUDESTE,SAO PAULO,ETANOL HIDRATADO,4047,R$/l,0.768,0.085,...,0.111,0.57,0.056,0.4271,1.4123,0.098,5,2004,DEFAULT,4.608
24,24,2004-05-09,2004-05-15,SUL,PARANA,ETANOL HIDRATADO,760,R$/l,0.922,0.083,...,0.090,0.667,0.105,0.4357,0.9587,0.157,5,2004,DEFAULT,5.532
25,25,2004-05-09,2004-05-15,SUL,RIO GRANDE DO SUL,ETANOL HIDRATADO,689,R$/l,1.224,0.143,...,0.117,0.892,0.09,0.644,1.2727,0.101,5,2004,DEFAULT,7.344
26,26,2004-05-09,2004-05-15,SUL,SANTA CATARINA,ETANOL HIDRATADO,506,R$/l,1.229,0.077,...,0.063,0.813,0.097,0.57,1.2348,0.119,5,2004,DEFAULT,7.374
27,27,2004-05-16,2004-05-22,CENTRO OESTE,DISTRITO FEDERAL,ETANOL HIDRATADO,144,R$/l,1.271,0.039,...,0.031,0.823,0.111,0.4094,1.1931,0.135,5,2004,DEFAULT,7.626
28,28,2004-05-16,2004-05-22,CENTRO OESTE,GOIAS,ETANOL HIDRATADO,378,R$/l,1.162,0.114,...,0.098,0.741,0.086,0.5552,1.05,0.116,5,2004,DEFAULT,6.972
29,29,2004-05-16,2004-05-22,CENTRO OESTE,MATO GROSSO,ETANOL HIDRATADO,198,R$/l,1.385,0.095,...,0.069,0.984,0.078,0.7081,1.2546,0.079,5,2004,DEFAULT,8.310
30,30,2004-05-16,2004-05-22,CENTRO OESTE,MATO GROSSO DO SUL,ETANOL HIDRATADO,174,R$/l,1.258,0.086,...,0.068,0.83,0.115,0.5958,1.2396,0.139,5,2004,DEFAULT,7.548
31,31,2004-05-16,2004-05-22,NORDESTE,ALAGOAS,ETANOL HIDRATADO,106,R$/l,1.182,0.069,...,0.058,0.925,0.065,0.7561,1.0317,0.07,5,2004,DEFAULT,7.092
32,32,2004-05-16,2004-05-22,NORDESTE,BAHIA,ETANOL HIDRATADO,424,R$/l,1.390,0.133,...,0.096,0.977,0.119,0.56,1.35,0.122,5,2004,DEFAULT,8.340
33,33,2004-05-16,2004-05-22,NORDESTE,CEARA,ETANOL HIDRATADO,277,R$/l,1.451,0.219,...,0.151,1.104,0.06,0.92,1.27,0.054,5,2004,DEFAULT,8.706
34,34,2004-05-16,2004-05-22,NORDESTE,MARANHAO,ETANOL HIDRATADO,108,R$/l,1.617,0.164,...,0.101,1.088,0.103,0.9224,1.3683,0.095,5,2004,DEFAULT,9.702
35,35,2004-05-16,2004-05-22,NORDESTE,PARAIBA,ETANOL HIDRATADO,125,R$/l,1.284,0.134,...,0.104,0.917,0.072,0.7577,1.0858,0.079,5,2004,DEFAULT,7.704
36,36,2004-05-16,2004-05-22,NORDESTE,PERNAMBUCO,ETANOL HIDRATADO,435,R$/l,1.217,0.137,...,0.113,0.931,0.078,0.682,1.2666,0.084,5,2004,DEFAULT,7.302
37,37,2004-05-16,2004-05-22,NORDESTE,PIAUI,ETANOL HIDRATADO,93,R$/l,1.571,0.133,...,0.085,1.082,0.094,0.8678,1.2499,0.087,5,2004,DEFAULT,9.426
38,38,2004-05-16,2004-05-22,NORDESTE,RIO GRANDE DO NORTE,ETANOL HIDRATADO,123,R$/l,1.279,0.115,...,0.090,0.944,0.08,0.7119,1.1386,0.085,5,2004,DEFAULT,7.674
39,39,2004-05-16,2004-05-22,NORDESTE,SERGIPE,ETANOL HIDRATADO,49,R$/l,1.302,0.110,...,0.084,0.991,0.084,0.682,1.1059,0.085,5,2004,DEFAULT,7.812
40,40,2004-05-16,2004-05-22,NORTE,ACRE,ETANOL HIDRATADO,32,R$/l,1.804,0.136,...,0.075,1.111,0.165,0.767,1.2992,0.149,5,2004,DEFAULT,10.824
41,41,2004-05-16,2004-05-22,NORTE,AMAPA,ETANOL HIDRATADO,15,R$/l,1.785,0.035,...,0.020,1.416,0.05,1.3518,1.497,0.035,5,2004,DEFAULT,10.710
42,42,2004-05-16,2004-05-22,NORTE,AMAZONAS,ETANOL HIDRATADO,56,R$/l,1.557,0.117,...,0.075,1.113,0.066,0.942,1.2109,0.059,5,2004,DEFAULT,9.342
43,43,2004-05-16,2004-05-22,NORTE,PARA,ETANOL HIDRATADO,117,R$/l,1.889,0.246,...,0.130,1.318,0.227,0.6099,1.8908,0.172,5,2004,DEFAULT,11.334
44,44,2004-05-16,2004-05-22,NORTE,RONDONIA,ETANOL HIDRATADO,96,R$/l,1.542,0.136,...,0.088,1.01,0.135,0.52,1.3306,0.134,5,2004,DEFAULT,9.252
45,45,2004-05-16,2004-05-22,NORTE,RORAIMA,ETANOL HIDRATADO,14,R$/l,1.300,0.000,...,0.000,1.098,0.096,0.9798,1.3577,0.087,5,2004,DEFAULT,7.800
46,46,2004-05-16,2004-05-22,NORTE,TOCANTINS,ETANOL HIDRATADO,71,R$/l,1.227,0.084,...,0.068,0.698,0.117,0.529,0.9832,0.168,5,2004,DEFAULT,7.362
47,47,2004-05-16,2004-05-22,SUDESTE,ESPIRITO SANTO,ETANOL HIDRATADO,307,R$/l,1.144,0.115,...,0.101,0.864,0.091,0.6259,1.1384,0.105,5,2004,DEFAULT,6.864
48,48,2004-05-16,2004-05-22,SUDESTE,MINAS GERAIS,ETANOL HIDRATADO,1235,R$/l,1.198,0.117,...,0.098,0.823,0.123,0.3797,1.4256,0.149,5,2004,DEFAULT,7.188
49,49,2004-05-16,2004-05-22,SUDESTE,RIO DE JANEIRO,ETANOL HIDRATADO,948,R$/l,1.092,0.157,...,0.144,0.808,0.175,0.3257,1.2921,0.217,5,2004,DEFAULT,6.552
50,50,2004-05-16,2004-05-22,SUDESTE,SAO PAULO,ETANOL HIDRATADO,4066,R$/l,0.766,0.083,...,0.108,0.576,0.05,0.43204,0.9724,0.087,5,2004,DEFAULT,4.596
51,51,2004-05-16,2004-05-22,SUL,PARANA,ETANOL HIDRATADO,769,R$/l,0.922,0.088,...,0.095,0.668,0.1,0.4337,0.9587,0.15,5,2004,DEFAULT,5.532
52,52,2004-05-16,2004-05-22,SUL,RIO GRANDE DO SUL,ETANOL HIDRATADO,674,R$/l,1.220,0.142,...,0.116,0.896,0.088,0.644,1.2378,0.098,5,2004,DEFAULT,7.320
53,53,2004-05-16,2004-05-22,SUL,SANTA CATARINA,ETANOL HIDRATADO,510,R$/l,1.227,0.078,...,0.064,0.827,0.102,0.57,1.235,0.123,5,2004,DEFAULT,7.362
54,54,2004-05-23,2004-05-29,CENTRO OESTE,DISTRITO FEDERAL,ETANOL HIDRATADO,129,R$/l,1.282,0.024,...,0.019,0.818,0.137,0.3879,1.0336,0.167,5,2004,DEFAULT,7.692
55,55,2004-05-23,2004-05-29,CENTRO OESTE,GOIAS,ETANOL HIDRATADO,389,R$/l,1.162,0.114,...,0.098,0.737,0.082,0.479,1.07,0.111,5,2004,DEFAULT,6.972
56,56,2004-05-23,2004-05-29,CENTRO OESTE,MATO GROSSO,ETANOL HIDRATADO,197,R$/l,1.388,0.097,...,0.070,0.97,0.095,0.5614,1.2546,0.098,5,2004,DEFAULT,8.328
57,57,2004-05-23,2004-05-29,CENTRO OESTE,MATO GROSSO DO SUL,ETANOL HIDRATADO,162,R$/l,1.257,0.072,...,0.057,0.816,0.121,0.5958,1.2396,0.148,5,2004,DEFAULT,7.542
58,58,2004-05-23,2004-05-29,NORDESTE,ALAGOAS,ETANOL HIDRATADO,103,R$/l,1.182,0.076,...,0.064,0.93,0.079,0.7561,1.0782,0.085,5,2004,DEFAULT,7.092

In [52]:
localizar_estados_nortes.iloc[9]

Unnamed: 0                                     18
DATA INICIAL                           2004-05-09
DATA FINAL                             2004-05-15
REGIÃO                                      NORTE
ESTADO                                    RORAIMA
PRODUTO                          ETANOL HIDRATADO
NÚMERO DE POSTOS PESQUISADOS                   14
UNIDADE DE MEDIDA                            R$/l
PREÇO MÉDIO REVENDA                           1.3
DESVIO PADRÃO REVENDA                         0.0
PREÇO MÍNIMO REVENDA                          1.3
PREÇO MÁXIMO REVENDA                          1.3
MARGEM MÉDIA REVENDA                        0.202
COEF DE VARIAÇÃO REVENDA                      0.0
PREÇO MÉDIO DISTRIBUIÇÃO                    1.098
DESVIO PADRÃO DISTRIBUIÇÃO                  0.096
PREÇO MÍNIMO DISTRIBUIÇÃO                  0.9798
PREÇO MÁXIMO DISTRIBUIÇÃO                  1.3577
COEF DE VARIAÇÃO DISTRIBUIÇÃO               0.087
MÊS                                             5
ANO                                          2004
nota sem noção                            DEFAULT
PREÇO MÉDIO REVENDA (doláres)                 7.8
Name: 18, dtype: object

In [53]:
estado_roraima = localizar_estados_nortes.iloc[9,4]
valor_medio_revenda = localizar_estados_nortes.iloc[9,8]

In [54]:
estado = pd.Series(estado_roraima, name='ESTADO')
valor = pd.Series(valor_medio_revenda, name='REVENDA')
valor
teste = pd.concat([estado, valor], axis=1)
teste

    ESTADO  REVENDA
0  RORAIMA      1.3

<h1>Seleção de rótulos<h1>

In [55]:
data.head()

,Unnamed: 0,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,...,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO,nota sem noção,PREÇO MÉDIO REVENDA (doláres)
0,0,2004-05-09,2004-05-15,CENTRO OESTE,DISTRITO FEDERAL,ETANOL HIDRATADO,127,R$/l,1.288,0.016,...,0.012,0.825,0.11,0.4201,0.9666,0.133,5,2004,DEFAULT,7.728
1,1,2004-05-09,2004-05-15,CENTRO OESTE,GOIAS,ETANOL HIDRATADO,387,R$/l,1.162,0.114,...,0.098,0.763,0.088,0.5013,1.05,0.115,5,2004,DEFAULT,6.972
2,2,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO,ETANOL HIDRATADO,192,R$/l,1.389,0.097,...,0.070,0.97,0.095,0.5614,1.161,0.098,5,2004,DEFAULT,8.334
3,3,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO DO SUL,ETANOL HIDRATADO,162,R$/l,1.262,0.070,...,0.055,0.83,0.119,0.5991,1.22242,0.143,5,2004,DEFAULT,7.572
4,4,2004-05-09,2004-05-15,NORDESTE,ALAGOAS,ETANOL HIDRATADO,103,R$/l,1.181,0.078,...,0.066,0.941,0.077,0.7441,1.0317,0.082,5,2004,DEFAULT,7.086

In [56]:
pesquisa_de_consoles

           bom  medio  pessimo
Switch     3.1    5.1      3.1
Xbox       2.1    4.1      5.1
Playstion  5.1    9.1      7.1

In [57]:
pesquisa_de_consoles.loc[: ,['bom' , 'pessimo']]

           bom  pessimo
Switch     3.1      3.1
Xbox       2.1      5.1
Playstion  5.1      7.1

In [58]:
pesquisa_de_consoles.loc['Switch' , ['bom' , 'pessimo']]

bom        3.1
pessimo    3.1
Name: Switch, dtype: float64

In [59]:
data.head()

,Unnamed: 0,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,...,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO,nota sem noção,PREÇO MÉDIO REVENDA (doláres)
0,0,2004-05-09,2004-05-15,CENTRO OESTE,DISTRITO FEDERAL,ETANOL HIDRATADO,127,R$/l,1.288,0.016,...,0.012,0.825,0.11,0.4201,0.9666,0.133,5,2004,DEFAULT,7.728
1,1,2004-05-09,2004-05-15,CENTRO OESTE,GOIAS,ETANOL HIDRATADO,387,R$/l,1.162,0.114,...,0.098,0.763,0.088,0.5013,1.05,0.115,5,2004,DEFAULT,6.972
2,2,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO,ETANOL HIDRATADO,192,R$/l,1.389,0.097,...,0.070,0.97,0.095,0.5614,1.161,0.098,5,2004,DEFAULT,8.334
3,3,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO DO SUL,ETANOL HIDRATADO,162,R$/l,1.262,0.070,...,0.055,0.83,0.119,0.5991,1.22242,0.143,5,2004,DEFAULT,7.572
4,4,2004-05-09,2004-05-15,NORDESTE,ALAGOAS,ETANOL HIDRATADO,103,R$/l,1.181,0.078,...,0.066,0.941,0.077,0.7441,1.0317,0.082,5,2004,DEFAULT,7.086

<p>rótulos também aceitam indices númericos

In [60]:
data.loc[1]

Unnamed: 0                                      1
DATA INICIAL                           2004-05-09
DATA FINAL                             2004-05-15
REGIÃO                               CENTRO OESTE
ESTADO                                      GOIAS
PRODUTO                          ETANOL HIDRATADO
NÚMERO DE POSTOS PESQUISADOS                  387
UNIDADE DE MEDIDA                            R$/l
PREÇO MÉDIO REVENDA                         1.162
DESVIO PADRÃO REVENDA                       0.114
PREÇO MÍNIMO REVENDA                         0.89
PREÇO MÁXIMO REVENDA                        1.449
MARGEM MÉDIA REVENDA                        0.399
COEF DE VARIAÇÃO REVENDA                    0.098
PREÇO MÉDIO DISTRIBUIÇÃO                    0.763
DESVIO PADRÃO DISTRIBUIÇÃO                  0.088
PREÇO MÍNIMO DISTRIBUIÇÃO                  0.5013
PREÇO MÁXIMO DISTRIBUIÇÃO                    1.05
COEF DE VARIAÇÃO DISTRIBUIÇÃO               0.115
MÊS                                             5
ANO                                          2004
nota sem noção                            DEFAULT
PREÇO MÉDIO REVENDA (doláres)               6.972
Name: 1, dtype: object

## Seleção de colunas/atribuito

In [61]:
data

,Unnamed: 0,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,...,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO,nota sem noção,PREÇO MÉDIO REVENDA (doláres)
0,0,2004-05-09,2004-05-15,CENTRO OESTE,DISTRITO FEDERAL,ETANOL HIDRATADO,127,R$/l,1.288,0.016,...,0.012,0.825,0.11,0.4201,0.9666,0.133,5,2004,DEFAULT,7.728
1,1,2004-05-09,2004-05-15,CENTRO OESTE,GOIAS,ETANOL HIDRATADO,387,R$/l,1.162,0.114,...,0.098,0.763,0.088,0.5013,1.05,0.115,5,2004,DEFAULT,6.972
2,2,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO,ETANOL HIDRATADO,192,R$/l,1.389,0.097,...,0.070,0.97,0.095,0.5614,1.161,0.098,5,2004,DEFAULT,8.334
3,3,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO DO SUL,ETANOL HIDRATADO,162,R$/l,1.262,0.070,...,0.055,0.83,0.119,0.5991,1.22242,0.143,5,2004,DEFAULT,7.572
4,4,2004-05-09,2004-05-15,NORDESTE,ALAGOAS,ETANOL HIDRATADO,103,R$/l,1.181,0.078,...,0.066,0.941,0.077,0.7441,1.0317,0.082,5,2004,DEFAULT,7.086
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
106818,106818,2019-06-23,2019-06-29,NORDESTE,RIO GRANDE DO NORTE,GNV,7,R$/m3,3.574,0.065,...,0.018,2.756,0,2.756,2.756,0,6,2019,DEFAULT,21.444
106819,106819,2019-06-23,2019-06-29,SUL,RIO GRANDE DO SUL,GNV,23,R$/m3,3.401,0.129,...,0.038,2.451,0.402,1.9842,2.8661,0.164,6,2019,DEFAULT,20.406
106820,106820,2019-06-23,2019-06-29,SUL,SANTA CATARINA,GNV,24,R$/m3,2.912,0.190,...,0.065,1.998,0,1.9981,1.9981,0,6,2019,DEFAULT,17.472
106821,106821,2019-06-23,2019-06-29,SUDESTE,SAO PAULO,GNV,52,R$/m3,3.020,0.229,...,0.076,2.374,0.165,2.0179,2.5093,0.07,6,2019,DEFAULT,18.120
106822,106822,2019-06-23,2019-06-29,NORDESTE,SERGIPE,GNV,4,R$/m3,3.697,0.005,...,0.001,2.518,0,2.5175,2.5175,0,6,2019,DEFAULT,22.182

In [62]:
data[['PRODUTO' , 'REGIÃO' , 'ESTADO']]

                 PRODUTO        REGIÃO               ESTADO
0       ETANOL HIDRATADO  CENTRO OESTE     DISTRITO FEDERAL
1       ETANOL HIDRATADO  CENTRO OESTE                GOIAS
2       ETANOL HIDRATADO  CENTRO OESTE          MATO GROSSO
3       ETANOL HIDRATADO  CENTRO OESTE   MATO GROSSO DO SUL
4       ETANOL HIDRATADO      NORDESTE              ALAGOAS
...                  ...           ...                  ...
106818               GNV      NORDESTE  RIO GRANDE DO NORTE
106819               GNV           SUL    RIO GRANDE DO SUL
106820               GNV           SUL       SANTA CATARINA
106821               GNV       SUDESTE            SAO PAULO
106822               GNV      NORDESTE              SERGIPE

[106823 rows x 3 columns]

In [63]:
data[data['ESTADO'] == 'RORAIMA']["PRODUTO"].unique()
# data.query('ESTADO == "RORAIMA"')

array(['ETANOL HIDRATADO', 'GASOLINA COMUM', 'GLP', 'ÓLEO DIESEL',
       'ÓLEO DIESEL S10'], dtype=object)

In [64]:
data

,Unnamed: 0,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,...,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO,nota sem noção,PREÇO MÉDIO REVENDA (doláres)
0,0,2004-05-09,2004-05-15,CENTRO OESTE,DISTRITO FEDERAL,ETANOL HIDRATADO,127,R$/l,1.288,0.016,...,0.012,0.825,0.11,0.4201,0.9666,0.133,5,2004,DEFAULT,7.728
1,1,2004-05-09,2004-05-15,CENTRO OESTE,GOIAS,ETANOL HIDRATADO,387,R$/l,1.162,0.114,...,0.098,0.763,0.088,0.5013,1.05,0.115,5,2004,DEFAULT,6.972
2,2,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO,ETANOL HIDRATADO,192,R$/l,1.389,0.097,...,0.070,0.97,0.095,0.5614,1.161,0.098,5,2004,DEFAULT,8.334
3,3,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO DO SUL,ETANOL HIDRATADO,162,R$/l,1.262,0.070,...,0.055,0.83,0.119,0.5991,1.22242,0.143,5,2004,DEFAULT,7.572
4,4,2004-05-09,2004-05-15,NORDESTE,ALAGOAS,ETANOL HIDRATADO,103,R$/l,1.181,0.078,...,0.066,0.941,0.077,0.7441,1.0317,0.082,5,2004,DEFAULT,7.086
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
106818,106818,2019-06-23,2019-06-29,NORDESTE,RIO GRANDE DO NORTE,GNV,7,R$/m3,3.574,0.065,...,0.018,2.756,0,2.756,2.756,0,6,2019,DEFAULT,21.444
106819,106819,2019-06-23,2019-06-29,SUL,RIO GRANDE DO SUL,GNV,23,R$/m3,3.401,0.129,...,0.038,2.451,0.402,1.9842,2.8661,0.164,6,2019,DEFAULT,20.406
106820,106820,2019-06-23,2019-06-29,SUL,SANTA CATARINA,GNV,24,R$/m3,2.912,0.190,...,0.065,1.998,0,1.9981,1.9981,0,6,2019,DEFAULT,17.472
106821,106821,2019-06-23,2019-06-29,SUDESTE,SAO PAULO,GNV,52,R$/m3,3.020,0.229,...,0.076,2.374,0.165,2.0179,2.5093,0.07,6,2019,DEFAULT,18.120
106822,106822,2019-06-23,2019-06-29,NORDESTE,SERGIPE,GNV,4,R$/m3,3.697,0.005,...,0.001,2.518,0,2.5175,2.5175,0,6,2019,DEFAULT,22.182

### Removendo colunas/atribuitos

In [65]:
del data['Unnamed: 0']
del data['nota sem noção']

In [66]:
del data['PREÇO MÉDIO REVENDA (doláres)']

In [67]:
data

,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO
0,2004-05-09,2004-05-15,CENTRO OESTE,DISTRITO FEDERAL,ETANOL HIDRATADO,127,R$/l,1.288,0.016,1.190,1.350,0.463,0.012,0.825,0.11,0.4201,0.9666,0.133,5,2004
1,2004-05-09,2004-05-15,CENTRO OESTE,GOIAS,ETANOL HIDRATADO,387,R$/l,1.162,0.114,0.890,1.449,0.399,0.098,0.763,0.088,0.5013,1.05,0.115,5,2004
2,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO,ETANOL HIDRATADO,192,R$/l,1.389,0.097,1.180,1.760,0.419,0.070,0.97,0.095,0.5614,1.161,0.098,5,2004
3,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO DO SUL,ETANOL HIDRATADO,162,R$/l,1.262,0.070,1.090,1.509,0.432,0.055,0.83,0.119,0.5991,1.22242,0.143,5,2004
4,2004-05-09,2004-05-15,NORDESTE,ALAGOAS,ETANOL HIDRATADO,103,R$/l,1.181,0.078,1.050,1.400,0.24,0.066,0.941,0.077,0.7441,1.0317,0.082,5,2004
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
106818,2019-06-23,2019-06-29,NORDESTE,RIO GRANDE DO NORTE,GNV,7,R$/m3,3.574,0.065,3.499,3.690,0.818,0.018,2.756,0,2.756,2.756,0,6,2019
106819,2019-06-23,2019-06-29,SUL,RIO GRANDE DO SUL,GNV,23,R$/m3,3.401,0.129,3.230,3.789,0.95,0.038,2.451,0.402,1.9842,2.8661,0.164,6,2019
106820,2019-06-23,2019-06-29,SUL,SANTA CATARINA,GNV,24,R$/m3,2.912,0.190,2.699,3.499,0.914,0.065,1.998,0,1.9981,1.9981,0,6,2019
106821,2019-06-23,2019-06-29,SUDESTE,SAO PAULO,GNV,52,R$/m3,3.020,0.229,2.699,3.490,0.646,0.076,2.374,0.165,2.0179,2.5093,0.07,6,2019
106822,2019-06-23,2019-06-29,NORDESTE,SERGIPE,GNV,4,R$/m3,3.697,0.005,3.689,3.699,1.179,0.001,2.518,0,2.5175,2.5175,0,6,2019

In [68]:
data.to_csv('/home/youx/workspace-git/youxlab-treino-git/curso_dados/data.sets/ipynb.xave/preprecoderevenda.csv', index=False)

## Seleção condicional

In [69]:
data

,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO
0,2004-05-09,2004-05-15,CENTRO OESTE,DISTRITO FEDERAL,ETANOL HIDRATADO,127,R$/l,1.288,0.016,1.190,1.350,0.463,0.012,0.825,0.11,0.4201,0.9666,0.133,5,2004
1,2004-05-09,2004-05-15,CENTRO OESTE,GOIAS,ETANOL HIDRATADO,387,R$/l,1.162,0.114,0.890,1.449,0.399,0.098,0.763,0.088,0.5013,1.05,0.115,5,2004
2,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO,ETANOL HIDRATADO,192,R$/l,1.389,0.097,1.180,1.760,0.419,0.070,0.97,0.095,0.5614,1.161,0.098,5,2004
3,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO DO SUL,ETANOL HIDRATADO,162,R$/l,1.262,0.070,1.090,1.509,0.432,0.055,0.83,0.119,0.5991,1.22242,0.143,5,2004
4,2004-05-09,2004-05-15,NORDESTE,ALAGOAS,ETANOL HIDRATADO,103,R$/l,1.181,0.078,1.050,1.400,0.24,0.066,0.941,0.077,0.7441,1.0317,0.082,5,2004
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
106818,2019-06-23,2019-06-29,NORDESTE,RIO GRANDE DO NORTE,GNV,7,R$/m3,3.574,0.065,3.499,3.690,0.818,0.018,2.756,0,2.756,2.756,0,6,2019
106819,2019-06-23,2019-06-29,SUL,RIO GRANDE DO SUL,GNV,23,R$/m3,3.401,0.129,3.230,3.789,0.95,0.038,2.451,0.402,1.9842,2.8661,0.164,6,2019
106820,2019-06-23,2019-06-29,SUL,SANTA CATARINA,GNV,24,R$/m3,2.912,0.190,2.699,3.499,0.914,0.065,1.998,0,1.9981,1.9981,0,6,2019
106821,2019-06-23,2019-06-29,SUDESTE,SAO PAULO,GNV,52,R$/m3,3.020,0.229,2.699,3.490,0.646,0.076,2.374,0.165,2.0179,2.5093,0.07,6,2019
106822,2019-06-23,2019-06-29,NORDESTE,SERGIPE,GNV,4,R$/m3,3.697,0.005,3.689,3.699,1.179,0.001,2.518,0,2.5175,2.5175,0,6,2019

In [70]:
data.shape

(106823, 20)

In [71]:
data['ESTADO'] == 'SAO PAULO'

0         False
1         False
2         False
3         False
4         False
          ...
106818    False
106819    False
106820    False
106821     True
106822    False
Name: ESTADO, Length: 106823, dtype: bool

In [72]:
# cria um valor boleano para todos os estados de são paulo 
selecao = data['ESTADO'] == 'SAO PAULO'

In [73]:
data[selecao]

,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO
23,2004-05-09,2004-05-15,SUDESTE,SAO PAULO,ETANOL HIDRATADO,4047,R$/l,0.768,0.085,0.590,1.150,0.198,0.111,0.57,0.056,0.4271,1.4123,0.098,5,2004
50,2004-05-16,2004-05-22,SUDESTE,SAO PAULO,ETANOL HIDRATADO,4066,R$/l,0.766,0.083,0.590,1.150,0.19,0.108,0.576,0.05,0.43204,0.9724,0.087,5,2004
77,2004-05-23,2004-05-29,SUDESTE,SAO PAULO,ETANOL HIDRATADO,4077,R$/l,0.823,0.071,0.620,1.199,0.209,0.086,0.614,0.063,0.34951,1.412,0.103,5,2004
104,2004-05-30,2004-06-05,SUDESTE,SAO PAULO,ETANOL HIDRATADO,4073,R$/l,0.887,0.075,0.639,1.359,0.216,0.085,0.671,0.075,0.3398,1.0669,0.112,5,2004
131,2004-06-06,2004-06-12,SUDESTE,SAO PAULO,ETANOL HIDRATADO,4082,R$/l,0.894,0.071,0.669,1.199,0.205,0.079,0.689,0.072,0.47797,1.0669,0.104,6,2004
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
106724,2019-06-23,2019-06-29,SUDESTE,SAO PAULO,ÓLEO DIESEL,863,R$/l,3.448,0.156,3.099,4.220,0.401,0.045,3.047,0.097,2.8599,3.3481,0.032,6,2019
106751,2019-06-23,2019-06-29,SUDESTE,SAO PAULO,ÓLEO DIESEL S10,1277,R$/l,3.574,0.169,3.199,4.320,0.451,0.047,3.123,0.111,2.885,3.491,0.036,6,2019
106778,2019-06-23,2019-06-29,SUDESTE,SAO PAULO,GASOLINA COMUM,1644,R$/l,4.142,0.183,3.769,4.999,0.429,0.044,3.713,0.097,3.52,4.0892,0.026,6,2019
106805,2019-06-23,2019-06-29,SUDESTE,SAO PAULO,GLP,1017,R$/13Kg,66.893,6.100,50.000,89.900,17.679,0.091,49.214,5.071,40.19,72,0.103,6,2019
106821,2019-06-23,2019-06-29,SUDESTE,SAO PAULO,GNV,52,R$/m3,3.020,0.229,2.699,3.490,0.646,0.076,2.374,0.165,2.0179,2.5093,0.07,6,2019

#### Criando uma array a partir de um metôdo com valores selecionados de um atribuito/colunas

In [74]:
# cria uma array unica para mostrar todos os estados de data 
pd.unique(data["ESTADO"])

array(['DISTRITO FEDERAL', 'GOIAS', 'MATO GROSSO', 'MATO GROSSO DO SUL',
       'ALAGOAS', 'BAHIA', 'CEARA', 'MARANHAO', 'PARAIBA', 'PERNAMBUCO',
       'PIAUI', 'RIO GRANDE DO NORTE', 'SERGIPE', 'ACRE', 'AMAPA',
       'AMAZONAS', 'PARA', 'RONDONIA', 'RORAIMA', 'TOCANTINS',
       'ESPIRITO SANTO', 'MINAS GERAIS', 'RIO DE JANEIRO', 'SAO PAULO',
       'PARANA', 'RIO GRANDE DO SUL', 'SANTA CATARINA'], dtype=object)

## Filtragem parte 2

In [75]:
data.head()

,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO
0,2004-05-09,2004-05-15,CENTRO OESTE,DISTRITO FEDERAL,ETANOL HIDRATADO,127,R$/l,1.288,0.016,1.19,1.350,0.463,0.012,0.825,0.11,0.4201,0.9666,0.133,5,2004
1,2004-05-09,2004-05-15,CENTRO OESTE,GOIAS,ETANOL HIDRATADO,387,R$/l,1.162,0.114,0.89,1.449,0.399,0.098,0.763,0.088,0.5013,1.05,0.115,5,2004
2,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO,ETANOL HIDRATADO,192,R$/l,1.389,0.097,1.18,1.760,0.419,0.070,0.97,0.095,0.5614,1.161,0.098,5,2004
3,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO DO SUL,ETANOL HIDRATADO,162,R$/l,1.262,0.070,1.09,1.509,0.432,0.055,0.83,0.119,0.5991,1.22242,0.143,5,2004
4,2004-05-09,2004-05-15,NORDESTE,ALAGOAS,ETANOL HIDRATADO,103,R$/l,1.181,0.078,1.05,1.400,0.24,0.066,0.941,0.077,0.7441,1.0317,0.082,5,2004

In [76]:
pd.unique(data['ESTADO'])

array(['DISTRITO FEDERAL', 'GOIAS', 'MATO GROSSO', 'MATO GROSSO DO SUL',
       'ALAGOAS', 'BAHIA', 'CEARA', 'MARANHAO', 'PARAIBA', 'PERNAMBUCO',
       'PIAUI', 'RIO GRANDE DO NORTE', 'SERGIPE', 'ACRE', 'AMAPA',
       'AMAZONAS', 'PARA', 'RONDONIA', 'RORAIMA', 'TOCANTINS',
       'ESPIRITO SANTO', 'MINAS GERAIS', 'RIO DE JANEIRO', 'SAO PAULO',
       'PARANA', 'RIO GRANDE DO SUL', 'SANTA CATARINA'], dtype=object)

In [77]:
# uso mais comuns ultimante
postos_sp = data.query('ESTADO == "SAO PAULO"').reset_index(drop=True)

In [78]:
postos_sp

,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO
0,2004-05-09,2004-05-15,SUDESTE,SAO PAULO,ETANOL HIDRATADO,4047,R$/l,0.768,0.085,0.590,1.150,0.198,0.111,0.57,0.056,0.4271,1.4123,0.098,5,2004
1,2004-05-16,2004-05-22,SUDESTE,SAO PAULO,ETANOL HIDRATADO,4066,R$/l,0.766,0.083,0.590,1.150,0.19,0.108,0.576,0.05,0.43204,0.9724,0.087,5,2004
2,2004-05-23,2004-05-29,SUDESTE,SAO PAULO,ETANOL HIDRATADO,4077,R$/l,0.823,0.071,0.620,1.199,0.209,0.086,0.614,0.063,0.34951,1.412,0.103,5,2004
3,2004-05-30,2004-06-05,SUDESTE,SAO PAULO,ETANOL HIDRATADO,4073,R$/l,0.887,0.075,0.639,1.359,0.216,0.085,0.671,0.075,0.3398,1.0669,0.112,5,2004
4,2004-06-06,2004-06-12,SUDESTE,SAO PAULO,ETANOL HIDRATADO,4082,R$/l,0.894,0.071,0.669,1.199,0.205,0.079,0.689,0.072,0.47797,1.0669,0.104,6,2004
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4258,2019-06-23,2019-06-29,SUDESTE,SAO PAULO,ÓLEO DIESEL,863,R$/l,3.448,0.156,3.099,4.220,0.401,0.045,3.047,0.097,2.8599,3.3481,0.032,6,2019
4259,2019-06-23,2019-06-29,SUDESTE,SAO PAULO,ÓLEO DIESEL S10,1277,R$/l,3.574,0.169,3.199,4.320,0.451,0.047,3.123,0.111,2.885,3.491,0.036,6,2019
4260,2019-06-23,2019-06-29,SUDESTE,SAO PAULO,GASOLINA COMUM,1644,R$/l,4.142,0.183,3.769,4.999,0.429,0.044,3.713,0.097,3.52,4.0892,0.026,6,2019
4261,2019-06-23,2019-06-29,SUDESTE,SAO PAULO,GLP,1017,R$/13Kg,66.893,6.100,50.000,89.900,17.679,0.091,49.214,5.071,40.19,72,0.103,6,2019
4262,2019-06-23,2019-06-29,SUDESTE,SAO PAULO,GNV,52,R$/m3,3.020,0.229,2.699,3.490,0.646,0.076,2.374,0.165,2.0179,2.5093,0.07,6,2019

In [79]:
produtos = postos_sp.query('PRODUTO == "GASOLINA COMUM"').reset_index(drop=True)
pd.unique(produtos['REGIÃO'])

array(['SUDESTE'], dtype=object)

### Filtragem parte 3

In [80]:
data

,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO
0,2004-05-09,2004-05-15,CENTRO OESTE,DISTRITO FEDERAL,ETANOL HIDRATADO,127,R$/l,1.288,0.016,1.190,1.350,0.463,0.012,0.825,0.11,0.4201,0.9666,0.133,5,2004
1,2004-05-09,2004-05-15,CENTRO OESTE,GOIAS,ETANOL HIDRATADO,387,R$/l,1.162,0.114,0.890,1.449,0.399,0.098,0.763,0.088,0.5013,1.05,0.115,5,2004
2,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO,ETANOL HIDRATADO,192,R$/l,1.389,0.097,1.180,1.760,0.419,0.070,0.97,0.095,0.5614,1.161,0.098,5,2004
3,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO DO SUL,ETANOL HIDRATADO,162,R$/l,1.262,0.070,1.090,1.509,0.432,0.055,0.83,0.119,0.5991,1.22242,0.143,5,2004
4,2004-05-09,2004-05-15,NORDESTE,ALAGOAS,ETANOL HIDRATADO,103,R$/l,1.181,0.078,1.050,1.400,0.24,0.066,0.941,0.077,0.7441,1.0317,0.082,5,2004
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
106818,2019-06-23,2019-06-29,NORDESTE,RIO GRANDE DO NORTE,GNV,7,R$/m3,3.574,0.065,3.499,3.690,0.818,0.018,2.756,0,2.756,2.756,0,6,2019
106819,2019-06-23,2019-06-29,SUL,RIO GRANDE DO SUL,GNV,23,R$/m3,3.401,0.129,3.230,3.789,0.95,0.038,2.451,0.402,1.9842,2.8661,0.164,6,2019
106820,2019-06-23,2019-06-29,SUL,SANTA CATARINA,GNV,24,R$/m3,2.912,0.190,2.699,3.499,0.914,0.065,1.998,0,1.9981,1.9981,0,6,2019
106821,2019-06-23,2019-06-29,SUDESTE,SAO PAULO,GNV,52,R$/m3,3.020,0.229,2.699,3.490,0.646,0.076,2.374,0.165,2.0179,2.5093,0.07,6,2019
106822,2019-06-23,2019-06-29,NORDESTE,SERGIPE,GNV,4,R$/m3,3.697,0.005,3.689,3.699,1.179,0.001,2.518,0,2.5175,2.5175,0,6,2019

In [81]:
data['ESTADO'].unique()

array(['DISTRITO FEDERAL', 'GOIAS', 'MATO GROSSO', 'MATO GROSSO DO SUL',
       'ALAGOAS', 'BAHIA', 'CEARA', 'MARANHAO', 'PARAIBA', 'PERNAMBUCO',
       'PIAUI', 'RIO GRANDE DO NORTE', 'SERGIPE', 'ACRE', 'AMAPA',
       'AMAZONAS', 'PARA', 'RONDONIA', 'RORAIMA', 'TOCANTINS',
       'ESPIRITO SANTO', 'MINAS GERAIS', 'RIO DE JANEIRO', 'SAO PAULO',
       'PARANA', 'RIO GRANDE DO SUL', 'SANTA CATARINA'], dtype=object)

In [82]:
estados_rj = data['ESTADO'] == 'RIO DE JANEIRO'

In [83]:
preco_minimo_revenda = data['PREÇO MÍNIMO REVENDA'] > 2

In [84]:
selecao_rj = preco_minimo_revenda & estados_rj

In [85]:
preco_revenda_do_rj = selecao_rj

In [86]:
data[preco_revenda_do_rj]

,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO
9629,2011-04-03,2011-04-09,SUDESTE,RIO DE JANEIRO,ETANOL HIDRATADO,724,R$/l,2.556,0.163,2.090,2.988,0.34,0.064,2.216,0.172,1.4549,2.5511,0.078,4,2011
9710,2011-04-24,2011-04-30,SUDESTE,RIO DE JANEIRO,ETANOL HIDRATADO,719,R$/l,2.555,0.157,2.099,2.999,0.357,0.061,2.198,0.153,1.2403,2.6296,0.07,4,2011
9737,2011-05-01,2011-05-07,SUDESTE,RIO DE JANEIRO,ETANOL HIDRATADO,722,R$/l,2.566,0.151,2.130,2.990,0.345,0.059,2.221,0.128,1.7299,2.6296,0.058,5,2011
12842,2004-11-21,2004-11-27,SUDESTE,RIO DE JANEIRO,GASOLINA COMUM,1091,R$/l,2.226,0.088,2.019,2.699,0.212,0.040,2.014,0.04,1.839,2.2402,0.02,11,2004
12869,2004-11-28,2004-12-04,SUDESTE,RIO DE JANEIRO,GASOLINA COMUM,1061,R$/l,2.286,0.103,2.030,2.749,0.24,0.045,2.046,0.049,1.8999,2.3279,0.024,11,2004
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
106718,2019-06-23,2019-06-29,SUDESTE,RIO DE JANEIRO,ÓLEO DIESEL,212,R$/l,3.569,0.166,3.179,4.059,0.467,0.047,3.102,0.119,2.886,3.5162,0.038,6,2019
106745,2019-06-23,2019-06-29,SUDESTE,RIO DE JANEIRO,ÓLEO DIESEL S10,335,R$/l,3.697,0.187,3.279,4.389,0.5,0.051,3.197,0.127,2.9772,3.5388,0.04,6,2019
106772,2019-06-23,2019-06-29,SUDESTE,RIO DE JANEIRO,GASOLINA COMUM,422,R$/l,4.928,0.165,4.599,5.859,0.538,0.033,4.39,0.097,4.2,4.618,0.022,6,2019
106799,2019-06-23,2019-06-29,SUDESTE,RIO DE JANEIRO,GLP,221,R$/13Kg,65.010,5.812,50.000,79.000,17.475,0.089,47.535,3.934,39,58.2,0.083,6,2019
106817,2019-06-23,2019-06-29,SUDESTE,RIO DE JANEIRO,GNV,124,R$/m3,3.111,0.260,2.799,3.799,0.707,0.084,2.404,0.174,2.126,2.7909,0.072,6,2019

### Filtragem parte 4

In [87]:
data

,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO
0,2004-05-09,2004-05-15,CENTRO OESTE,DISTRITO FEDERAL,ETANOL HIDRATADO,127,R$/l,1.288,0.016,1.190,1.350,0.463,0.012,0.825,0.11,0.4201,0.9666,0.133,5,2004
1,2004-05-09,2004-05-15,CENTRO OESTE,GOIAS,ETANOL HIDRATADO,387,R$/l,1.162,0.114,0.890,1.449,0.399,0.098,0.763,0.088,0.5013,1.05,0.115,5,2004
2,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO,ETANOL HIDRATADO,192,R$/l,1.389,0.097,1.180,1.760,0.419,0.070,0.97,0.095,0.5614,1.161,0.098,5,2004
3,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO DO SUL,ETANOL HIDRATADO,162,R$/l,1.262,0.070,1.090,1.509,0.432,0.055,0.83,0.119,0.5991,1.22242,0.143,5,2004
4,2004-05-09,2004-05-15,NORDESTE,ALAGOAS,ETANOL HIDRATADO,103,R$/l,1.181,0.078,1.050,1.400,0.24,0.066,0.941,0.077,0.7441,1.0317,0.082,5,2004
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
106818,2019-06-23,2019-06-29,NORDESTE,RIO GRANDE DO NORTE,GNV,7,R$/m3,3.574,0.065,3.499,3.690,0.818,0.018,2.756,0,2.756,2.756,0,6,2019
106819,2019-06-23,2019-06-29,SUL,RIO GRANDE DO SUL,GNV,23,R$/m3,3.401,0.129,3.230,3.789,0.95,0.038,2.451,0.402,1.9842,2.8661,0.164,6,2019
106820,2019-06-23,2019-06-29,SUL,SANTA CATARINA,GNV,24,R$/m3,2.912,0.190,2.699,3.499,0.914,0.065,1.998,0,1.9981,1.9981,0,6,2019
106821,2019-06-23,2019-06-29,SUDESTE,SAO PAULO,GNV,52,R$/m3,3.020,0.229,2.699,3.490,0.646,0.076,2.374,0.165,2.0179,2.5093,0.07,6,2019
106822,2019-06-23,2019-06-29,NORDESTE,SERGIPE,GNV,4,R$/m3,3.697,0.005,3.689,3.699,1.179,0.001,2.518,0,2.5175,2.5175,0,6,2019

In [88]:
data['ESTADO'].unique()

array(['DISTRITO FEDERAL', 'GOIAS', 'MATO GROSSO', 'MATO GROSSO DO SUL',
       'ALAGOAS', 'BAHIA', 'CEARA', 'MARANHAO', 'PARAIBA', 'PERNAMBUCO',
       'PIAUI', 'RIO GRANDE DO NORTE', 'SERGIPE', 'ACRE', 'AMAPA',
       'AMAZONAS', 'PARA', 'RONDONIA', 'RORAIMA', 'TOCANTINS',
       'ESPIRITO SANTO', 'MINAS GERAIS', 'RIO DE JANEIRO', 'SAO PAULO',
       'PARANA', 'RIO GRANDE DO SUL', 'SANTA CATARINA'], dtype=object)

In [89]:
selecao_1 = (data['ESTADO'] == 'SAO PAULO') | (data['ESTADO'] == 'RIO DE JANEIRO')
postos_rj_sp = data[selecao_1]
postos_rj_sp

,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO
22,2004-05-09,2004-05-15,SUDESTE,RIO DE JANEIRO,ETANOL HIDRATADO,952,R$/l,1.098,0.154,0.740,1.890,0.312,0.140,0.786,0.173,0.326,1.263,0.22,5,2004
23,2004-05-09,2004-05-15,SUDESTE,SAO PAULO,ETANOL HIDRATADO,4047,R$/l,0.768,0.085,0.590,1.150,0.198,0.111,0.57,0.056,0.4271,1.4123,0.098,5,2004
49,2004-05-16,2004-05-22,SUDESTE,RIO DE JANEIRO,ETANOL HIDRATADO,948,R$/l,1.092,0.157,0.740,1.499,0.284,0.144,0.808,0.175,0.3257,1.2921,0.217,5,2004
50,2004-05-16,2004-05-22,SUDESTE,SAO PAULO,ETANOL HIDRATADO,4066,R$/l,0.766,0.083,0.590,1.150,0.19,0.108,0.576,0.05,0.43204,0.9724,0.087,5,2004
76,2004-05-23,2004-05-29,SUDESTE,RIO DE JANEIRO,ETANOL HIDRATADO,973,R$/l,1.103,0.140,0.770,1.589,0.281,0.127,0.822,0.166,0.38909,1.1859,0.202,5,2004
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
106778,2019-06-23,2019-06-29,SUDESTE,SAO PAULO,GASOLINA COMUM,1644,R$/l,4.142,0.183,3.769,4.999,0.429,0.044,3.713,0.097,3.52,4.0892,0.026,6,2019
106799,2019-06-23,2019-06-29,SUDESTE,RIO DE JANEIRO,GLP,221,R$/13Kg,65.010,5.812,50.000,79.000,17.475,0.089,47.535,3.934,39,58.2,0.083,6,2019
106805,2019-06-23,2019-06-29,SUDESTE,SAO PAULO,GLP,1017,R$/13Kg,66.893,6.100,50.000,89.900,17.679,0.091,49.214,5.071,40.19,72,0.103,6,2019
106817,2019-06-23,2019-06-29,SUDESTE,RIO DE JANEIRO,GNV,124,R$/m3,3.111,0.260,2.799,3.799,0.707,0.084,2.404,0.174,2.126,2.7909,0.072,6,2019
106821,2019-06-23,2019-06-29,SUDESTE,SAO PAULO,GNV,52,R$/m3,3.020,0.229,2.699,3.490,0.646,0.076,2.374,0.165,2.0179,2.5093,0.07,6,2019

In [90]:
selecao_2 = postos_rj_sp['PRODUTO'] ==  'GASOLINA COMUM'
produto_gasolina_sp_rj = postos_rj_sp[selecao_2]
produto_gasolina_sp_rj

,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO
12086,2004-05-09,2004-05-15,SUDESTE,RIO DE JANEIRO,GASOLINA COMUM,1071,R$/l,2.045,0.109,1.700,2.599,0.254,0.053,1.791,0.047,1.6363,1.9594,0.026,5,2004
12087,2004-05-09,2004-05-15,SUDESTE,SAO PAULO,GASOLINA COMUM,4107,R$/l,1.891,0.101,1.570,2.399,0.235,0.053,1.656,0.064,1.38,1.944,0.039,5,2004
12113,2004-05-16,2004-05-22,SUDESTE,RIO DE JANEIRO,GASOLINA COMUM,1055,R$/l,2.040,0.113,1.700,2.599,0.252,0.055,1.788,0.049,1.5943,1.99651,0.027,5,2004
12114,2004-05-16,2004-05-22,SUDESTE,SAO PAULO,GASOLINA COMUM,4133,R$/l,1.888,0.101,1.540,2.220,0.233,0.053,1.655,0.063,1.38,1.9319,0.038,5,2004
12140,2004-05-23,2004-05-29,SUDESTE,RIO DE JANEIRO,GASOLINA COMUM,1091,R$/l,2.042,0.108,1.700,2.599,0.252,0.053,1.79,0.046,1.63596,2.2137,0.026,5,2004
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
106479,2019-06-09,2019-06-15,SUDESTE,SAO PAULO,GASOLINA COMUM,1643,R$/l,4.210,0.177,3.759,4.992,0.425,0.042,3.785,0.096,3.52,4.1007,0.025,6,2019
106623,2019-06-16,2019-06-22,SUDESTE,RIO DE JANEIRO,GASOLINA COMUM,418,R$/l,4.927,0.160,4.599,5.859,0.544,0.032,4.383,0.1,4.1972,4.6239,0.023,6,2019
106629,2019-06-16,2019-06-22,SUDESTE,SAO PAULO,GASOLINA COMUM,1635,R$/l,4.168,0.177,3.679,5.199,0.443,0.042,3.725,0.096,3.502,4.0892,0.026,6,2019
106772,2019-06-23,2019-06-29,SUDESTE,RIO DE JANEIRO,GASOLINA COMUM,422,R$/l,4.928,0.165,4.599,5.859,0.538,0.033,4.39,0.097,4.2,4.618,0.022,6,2019
106778,2019-06-23,2019-06-29,SUDESTE,SAO PAULO,GASOLINA COMUM,1644,R$/l,4.142,0.183,3.769,4.999,0.429,0.044,3.713,0.097,3.52,4.0892,0.026,6,2019

In [91]:
selecao_3  = produto_gasolina_sp_rj['PREÇO MÍNIMO REVENDA'] > 2
produto_gasolina_sp_rj_maior_revenda = produto_gasolina_sp_rj[selecao_3]
produto_gasolina_sp_rj_maior_revenda

,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO
12842,2004-11-21,2004-11-27,SUDESTE,RIO DE JANEIRO,GASOLINA COMUM,1091,R$/l,2.226,0.088,2.019,2.699,0.212,0.040,2.014,0.04,1.839,2.2402,0.02,11,2004
12869,2004-11-28,2004-12-04,SUDESTE,RIO DE JANEIRO,GASOLINA COMUM,1061,R$/l,2.286,0.103,2.030,2.749,0.24,0.045,2.046,0.049,1.8999,2.3279,0.024,11,2004
12923,2004-12-12,2004-12-18,SUDESTE,RIO DE JANEIRO,GASOLINA COMUM,1068,R$/l,2.286,0.098,2.039,2.749,0.219,0.043,2.067,0.039,1.8999,2.3079,0.019,12,2004
12977,2004-12-26,2005-01-01,SUDESTE,RIO DE JANEIRO,GASOLINA COMUM,1066,R$/l,2.293,0.101,2.050,2.749,0.212,0.044,2.081,0.04,1.9514,2.27902,0.019,12,2004
13031,2005-01-09,2005-01-15,SUDESTE,RIO DE JANEIRO,GASOLINA COMUM,1069,R$/l,2.292,0.101,2.039,2.749,0.213,0.044,2.079,0.041,1.963,2.3312,0.02,1,2005
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
106479,2019-06-09,2019-06-15,SUDESTE,SAO PAULO,GASOLINA COMUM,1643,R$/l,4.210,0.177,3.759,4.992,0.425,0.042,3.785,0.096,3.52,4.1007,0.025,6,2019
106623,2019-06-16,2019-06-22,SUDESTE,RIO DE JANEIRO,GASOLINA COMUM,418,R$/l,4.927,0.160,4.599,5.859,0.544,0.032,4.383,0.1,4.1972,4.6239,0.023,6,2019
106629,2019-06-16,2019-06-22,SUDESTE,SAO PAULO,GASOLINA COMUM,1635,R$/l,4.168,0.177,3.679,5.199,0.443,0.042,3.725,0.096,3.502,4.0892,0.026,6,2019
106772,2019-06-23,2019-06-29,SUDESTE,RIO DE JANEIRO,GASOLINA COMUM,422,R$/l,4.928,0.165,4.599,5.859,0.538,0.033,4.39,0.097,4.2,4.618,0.022,6,2019
106778,2019-06-23,2019-06-29,SUDESTE,SAO PAULO,GASOLINA COMUM,1644,R$/l,4.142,0.183,3.769,4.999,0.429,0.044,3.713,0.097,3.52,4.0892,0.026,6,2019

### Filtragem parte 5

In [92]:
data.head()

,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO
0,2004-05-09,2004-05-15,CENTRO OESTE,DISTRITO FEDERAL,ETANOL HIDRATADO,127,R$/l,1.288,0.016,1.19,1.350,0.463,0.012,0.825,0.11,0.4201,0.9666,0.133,5,2004
1,2004-05-09,2004-05-15,CENTRO OESTE,GOIAS,ETANOL HIDRATADO,387,R$/l,1.162,0.114,0.89,1.449,0.399,0.098,0.763,0.088,0.5013,1.05,0.115,5,2004
2,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO,ETANOL HIDRATADO,192,R$/l,1.389,0.097,1.18,1.760,0.419,0.070,0.97,0.095,0.5614,1.161,0.098,5,2004
3,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO DO SUL,ETANOL HIDRATADO,162,R$/l,1.262,0.070,1.09,1.509,0.432,0.055,0.83,0.119,0.5991,1.22242,0.143,5,2004
4,2004-05-09,2004-05-15,NORDESTE,ALAGOAS,ETANOL HIDRATADO,103,R$/l,1.181,0.078,1.05,1.400,0.24,0.066,0.941,0.077,0.7441,1.0317,0.082,5,2004

In [93]:
# Jeito mais pratico que achei de filtrar usando listas
listas_de_anos = [2008,2010,2013]
data.query('ANO in @listas_de_anos')

,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO
5098,2008-01-06,2008-01-12,CENTRO OESTE,DISTRITO FEDERAL,ETANOL HIDRATADO,80,R$/l,1.806,0.082,1.709,1.950,0.29,0.045,1.516,0.061,1.3892,1.6157,0.04,1,2008
5099,2008-01-06,2008-01-12,CENTRO OESTE,GOIAS,ETANOL HIDRATADO,255,R$/l,1.616,0.100,1.470,1.899,0.293,0.062,1.323,0.05,1.2242,1.6173,0.038,1,2008
5100,2008-01-06,2008-01-12,CENTRO OESTE,MATO GROSSO,ETANOL HIDRATADO,142,R$/l,1.581,0.095,1.390,1.850,0.278,0.060,1.303,0.073,1.14,1.45,0.056,1,2008
5101,2008-01-06,2008-01-12,CENTRO OESTE,MATO GROSSO DO SUL,ETANOL HIDRATADO,133,R$/l,1.831,0.046,1.680,1.910,0.382,0.025,1.449,0.044,1.3247,1.5514,0.03,1,2008
5102,2008-01-06,2008-01-12,NORDESTE,ALAGOAS,ETANOL HIDRATADO,97,R$/l,1.699,0.098,1.530,1.999,0.199,0.058,1.5,0.062,1.39,1.7689,0.041,1,2008
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
63675,2013-12-29,2014-01-04,NORDESTE,RIO GRANDE DO NORTE,GNV,17,R$/m3,1.933,0.041,1.890,1.999,0.516,0.021,1.417,0.127,1.3069,1.5262,0.09,12,2013
63676,2013-12-29,2014-01-04,SUL,RIO GRANDE DO SUL,GNV,28,R$/m3,2.150,0.096,1.969,2.399,0.558,0.045,1.592,0.185,1.3853,1.6463,0.116,12,2013
63677,2013-12-29,2014-01-04,SUL,SANTA CATARINA,GNV,40,R$/m3,2.178,0.072,1.999,2.489,0.534,0.033,1.644,0.2,1.333,1.7103,0.122,12,2013
63678,2013-12-29,2014-01-04,SUDESTE,SAO PAULO,GNV,84,R$/m3,1.700,0.172,1.499,2.890,0.333,0.101,1.367,0.158,1.0343,1.777,0.116,12,2013
63679,2013-12-29,2014-01-04,NORDESTE,SERGIPE,GNV,11,R$/m3,1.855,0.048,1.790,1.899,0.435,0.026,1.42,0.223,1.166,1.581,0.157,12,2013

#### interando com DataFrame

In [94]:
for index , rows in data.head(5).iterrows():
    print(f'indices {index} ==> {rows["ESTADO"]}')
# OBS: isso e bem importante para vai mexer com banco de dados

indices 0 ==> DISTRITO FEDERAL
indices 1 ==> GOIAS
indices 2 ==> MATO GROSSO
indices 3 ==> MATO GROSSO DO SUL
indices 4 ==> ALAGOAS

# 2 preparação de dados

In [96]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 106823 entries, 0 to 106822
Data columns (total 20 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   DATA INICIAL                   106823 non-null  object
 1   DATA FINAL                     106823 non-null  object
 2   REGIÃO                         106823 non-null  object
 3   ESTADO                         106823 non-null  object
 4   PRODUTO                        106823 non-null  object
 5   NÚMERO DE POSTOS PESQUISADOS   106823 non-null  int64
 6   UNIDADE DE MEDIDA              106823 non-null  object
 7   PREÇO MÉDIO REVENDA            106823 non-null  float64
 8   DESVIO PADRÃO REVENDA          106823 non-null  float64
 9   PREÇO MÍNIMO REVENDA           106823 non-null  float64
 10  PREÇO MÁXIMO REVENDA           106823 non-null  float64
 11  MARGEM MÉDIA REVENDA           106823 non-null  object
 12  COEF DE VARIAÇÃO REVENDA       106823 non-null  float64
 13  PREÇO MÉDIO DISTRIBUIÇÃO       106823 non-null  object
 14  DESVIO PADRÃO DISTRIBUIÇÃO     106823 non-null  object
 15  PREÇO MÍNIMO DISTRIBUIÇÃO      106823 non-null  object
 16  PREÇO MÁXIMO DISTRIBUIÇÃO      106823 non-null  object
 17  COEF DE VARIAÇÃO DISTRIBUIÇÃO  106823 non-null  object
 18  MÊS                            106823 non-null  int64
 19  ANO                            106823 non-null  int64
dtypes: float64(5), int64(3), object(12)
memory usage: 16.3+ MB

In [97]:
data_pre = data.copy()
data_pre

,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO
0,2004-05-09,2004-05-15,CENTRO OESTE,DISTRITO FEDERAL,ETANOL HIDRATADO,127,R$/l,1.288,0.016,1.190,1.350,0.463,0.012,0.825,0.11,0.4201,0.9666,0.133,5,2004
1,2004-05-09,2004-05-15,CENTRO OESTE,GOIAS,ETANOL HIDRATADO,387,R$/l,1.162,0.114,0.890,1.449,0.399,0.098,0.763,0.088,0.5013,1.05,0.115,5,2004
2,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO,ETANOL HIDRATADO,192,R$/l,1.389,0.097,1.180,1.760,0.419,0.070,0.97,0.095,0.5614,1.161,0.098,5,2004
3,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO DO SUL,ETANOL HIDRATADO,162,R$/l,1.262,0.070,1.090,1.509,0.432,0.055,0.83,0.119,0.5991,1.22242,0.143,5,2004
4,2004-05-09,2004-05-15,NORDESTE,ALAGOAS,ETANOL HIDRATADO,103,R$/l,1.181,0.078,1.050,1.400,0.24,0.066,0.941,0.077,0.7441,1.0317,0.082,5,2004
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
106818,2019-06-23,2019-06-29,NORDESTE,RIO GRANDE DO NORTE,GNV,7,R$/m3,3.574,0.065,3.499,3.690,0.818,0.018,2.756,0,2.756,2.756,0,6,2019
106819,2019-06-23,2019-06-29,SUL,RIO GRANDE DO SUL,GNV,23,R$/m3,3.401,0.129,3.230,3.789,0.95,0.038,2.451,0.402,1.9842,2.8661,0.164,6,2019
106820,2019-06-23,2019-06-29,SUL,SANTA CATARINA,GNV,24,R$/m3,2.912,0.190,2.699,3.499,0.914,0.065,1.998,0,1.9981,1.9981,0,6,2019
106821,2019-06-23,2019-06-29,SUDESTE,SAO PAULO,GNV,52,R$/m3,3.020,0.229,2.699,3.490,0.646,0.076,2.374,0.165,2.0179,2.5093,0.07,6,2019
106822,2019-06-23,2019-06-29,NORDESTE,SERGIPE,GNV,4,R$/m3,3.697,0.005,3.689,3.699,1.179,0.001,2.518,0,2.5175,2.5175,0,6,2019

In [102]:
data_pre['DATA INICIAL'] = pd.to_datetime(data_pre['DATA INICIAL'])
data_pre['DATA FINAL'] = pd.to_datetime(data_pre['DATA FINAL'])
data_pre.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 106823 entries, 0 to 106822
Data columns (total 20 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   DATA INICIAL                   106823 non-null  datetime64[ns]
 1   DATA FINAL                     106823 non-null  datetime64[ns]
 2   REGIÃO                         106823 non-null  object
 3   ESTADO                         106823 non-null  object
 4   PRODUTO                        106823 non-null  object
 5   NÚMERO DE POSTOS PESQUISADOS   106823 non-null  int64
 6   UNIDADE DE MEDIDA              106823 non-null  object
 7   PREÇO MÉDIO REVENDA            106823 non-null  float64
 8   DESVIO PADRÃO REVENDA          106823 non-null  float64
 9   PREÇO MÍNIMO REVENDA           106823 non-null  float64
 10  PREÇO MÁXIMO REVENDA           106823 non-null  float64
 11  MARGEM MÉDIA REVENDA           106823 non-null  object
 12  COEF DE VARIAÇÃO REVENDA       106823 non-null  float64
 13  PREÇO MÉDIO DISTRIBUIÇÃO       106823 non-null  object
 14  DESVIO PADRÃO DISTRIBUIÇÃO     106823 non-null  object
 15  PREÇO MÍNIMO DISTRIBUIÇÃO      106823 non-null  object
 16  PREÇO MÁXIMO DISTRIBUIÇÃO      106823 non-null  object
 17  COEF DE VARIAÇÃO DISTRIBUIÇÃO  106823 non-null  object
 18  MÊS                            106823 non-null  int64
 19  ANO                            106823 non-null  int64
dtypes: datetime64[ns](2), float64(5), int64(3), object(10)
memory usage: 16.3+ MB

In [107]:
for atribuito in ['MARGEM MÉDIA REVENDA' , 'PREÇO MÉDIO DISTRIBUIÇÃO' , 'DESVIO PADRÃO DISTRIBUIÇÃO' , 'PREÇO MÍNIMO DISTRIBUIÇÃO' , 'PREÇO MÁXIMO DISTRIBUIÇÃO' , 'COEF DE VARIAÇÃO DISTRIBUIÇÃO']:
    data_pre[atribuito] = pd.to_numeric(data_pre[atribuito] , errors='coerce')

In [109]:
data_pre.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 106823 entries, 0 to 106822
Data columns (total 20 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   DATA INICIAL                   106823 non-null  datetime64[ns]
 1   DATA FINAL                     106823 non-null  datetime64[ns]
 2   REGIÃO                         106823 non-null  object
 3   ESTADO                         106823 non-null  object
 4   PRODUTO                        106823 non-null  object
 5   NÚMERO DE POSTOS PESQUISADOS   106823 non-null  int64
 6   UNIDADE DE MEDIDA              106823 non-null  object
 7   PREÇO MÉDIO REVENDA            106823 non-null  float64
 8   DESVIO PADRÃO REVENDA          106823 non-null  float64
 9   PREÇO MÍNIMO REVENDA           106823 non-null  float64
 10  PREÇO MÁXIMO REVENDA           106823 non-null  float64
 11  MARGEM MÉDIA REVENDA           103392 non-null  float64
 12  COEF DE VARIAÇÃO REVENDA       106823 non-null  float64
 13  PREÇO MÉDIO DISTRIBUIÇÃO       103423 non-null  float64
 14  DESVIO PADRÃO DISTRIBUIÇÃO     103423 non-null  float64
 15  PREÇO MÍNIMO DISTRIBUIÇÃO      103423 non-null  float64
 16  PREÇO MÁXIMO DISTRIBUIÇÃO      103423 non-null  float64
 17  COEF DE VARIAÇÃO DISTRIBUIÇÃO  103423 non-null  float64
 18  MÊS                            106823 non-null  int64
 19  ANO                            106823 non-null  int64
dtypes: datetime64[ns](2), float64(11), int64(3), object(4)
memory usage: 16.3+ MB

In [112]:
mask = data_pre['PREÇO MÉDIO DISTRIBUIÇÃO'].isnull()
data_pre[mask]

,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO
1903,2005-09-25,2005-10-01,NORTE,PARA,ETANOL HIDRATADO,2,R$/l,1.694,0.283,1.690,2.090,NaN,0.167,NaN,NaN,NaN,NaN,NaN,9,2005
1958,2005-10-09,2005-10-15,NORTE,RORAIMA,ETANOL HIDRATADO,3,R$/l,2.000,0.000,2.000,2.000,NaN,0.000,NaN,NaN,NaN,NaN,NaN,10,2005
2012,2005-10-23,2005-10-29,NORTE,RORAIMA,ETANOL HIDRATADO,3,R$/l,2.277,0.023,2.250,2.290,NaN,0.010,NaN,NaN,NaN,NaN,NaN,10,2005
2497,2006-02-26,2006-03-04,NORTE,RORAIMA,ETANOL HIDRATADO,11,R$/l,2.182,0.040,2.100,2.200,NaN,0.018,NaN,NaN,NaN,NaN,NaN,2,2006
3199,2006-08-27,2006-09-02,NORTE,RORAIMA,ETANOL HIDRATADO,22,R$/l,2.285,0.068,1.980,2.300,NaN,0.030,NaN,NaN,NaN,NaN,NaN,8,2006
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
106664,2019-06-16,2019-06-22,SUDESTE,MINAS GERAIS,GNV,5,R$/m3,3.445,0.147,3.347,3.699,NaN,0.043,NaN,NaN,NaN,NaN,NaN,6,2019
106666,2019-06-16,2019-06-22,SUL,PARANA,GNV,7,R$/m3,3.132,0.295,3.049,3.890,NaN,0.094,NaN,NaN,NaN,NaN,NaN,6,2019
106811,2019-06-23,2019-06-29,SUDESTE,ESPIRITO SANTO,GNV,4,R$/m3,3.299,0.005,3.290,3.299,NaN,0.002,NaN,NaN,NaN,NaN,NaN,6,2019
106813,2019-06-23,2019-06-29,SUDESTE,MINAS GERAIS,GNV,6,R$/m3,3.548,0.100,3.495,3.699,NaN,0.028,NaN,NaN,NaN,NaN,NaN,6,2019
106815,2019-06-23,2019-06-29,SUL,PARANA,GNV,1,R$/m3,3.290,0.000,3.290,3.290,NaN,0.000,NaN,NaN,NaN,NaN,NaN,6,2019

In [113]:
data[mask]

,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO
1903,2005-09-25,2005-10-01,NORTE,PARA,ETANOL HIDRATADO,2,R$/l,1.694,0.283,1.690,2.090,-,0.167,-,-,-,-,-,9,2005
1958,2005-10-09,2005-10-15,NORTE,RORAIMA,ETANOL HIDRATADO,3,R$/l,2.000,0.000,2.000,2.000,-,0.000,-,-,-,-,-,10,2005
2012,2005-10-23,2005-10-29,NORTE,RORAIMA,ETANOL HIDRATADO,3,R$/l,2.277,0.023,2.250,2.290,-,0.010,-,-,-,-,-,10,2005
2497,2006-02-26,2006-03-04,NORTE,RORAIMA,ETANOL HIDRATADO,11,R$/l,2.182,0.040,2.100,2.200,-,0.018,-,-,-,-,-,2,2006
3199,2006-08-27,2006-09-02,NORTE,RORAIMA,ETANOL HIDRATADO,22,R$/l,2.285,0.068,1.980,2.300,-,0.030,-,-,-,-,-,8,2006
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
106664,2019-06-16,2019-06-22,SUDESTE,MINAS GERAIS,GNV,5,R$/m3,3.445,0.147,3.347,3.699,-,0.043,-,-,-,-,-,6,2019
106666,2019-06-16,2019-06-22,SUL,PARANA,GNV,7,R$/m3,3.132,0.295,3.049,3.890,-,0.094,-,-,-,-,-,6,2019
106811,2019-06-23,2019-06-29,SUDESTE,ESPIRITO SANTO,GNV,4,R$/m3,3.299,0.005,3.290,3.299,-,0.002,-,-,-,-,-,6,2019
106813,2019-06-23,2019-06-29,SUDESTE,MINAS GERAIS,GNV,6,R$/m3,3.548,0.100,3.495,3.699,-,0.028,-,-,-,-,-,6,2019
106815,2019-06-23,2019-06-29,SUL,PARANA,GNV,1,R$/m3,3.290,0.000,3.290,3.290,-,0.000,-,-,-,-,-,6,2019

In [114]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 106823 entries, 0 to 106822
Data columns (total 20 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   DATA INICIAL                   106823 non-null  object
 1   DATA FINAL                     106823 non-null  object
 2   REGIÃO                         106823 non-null  object
 3   ESTADO                         106823 non-null  object
 4   PRODUTO                        106823 non-null  object
 5   NÚMERO DE POSTOS PESQUISADOS   106823 non-null  int64
 6   UNIDADE DE MEDIDA              106823 non-null  object
 7   PREÇO MÉDIO REVENDA            106823 non-null  float64
 8   DESVIO PADRÃO REVENDA          106823 non-null  float64
 9   PREÇO MÍNIMO REVENDA           106823 non-null  float64
 10  PREÇO MÁXIMO REVENDA           106823 non-null  float64
 11  MARGEM MÉDIA REVENDA           106823 non-null  object
 12  COEF DE VARIAÇÃO REVENDA       106823 non-null  float64
 13  PREÇO MÉDIO DISTRIBUIÇÃO       106823 non-null  object
 14  DESVIO PADRÃO DISTRIBUIÇÃO     106823 non-null  object
 15  PREÇO MÍNIMO DISTRIBUIÇÃO      106823 non-null  object
 16  PREÇO MÁXIMO DISTRIBUIÇÃO      106823 non-null  object
 17  COEF DE VARIAÇÃO DISTRIBUIÇÃO  106823 non-null  object
 18  MÊS                            106823 non-null  int64
 19  ANO                            106823 non-null  int64
dtypes: float64(5), int64(3), object(12)
memory usage: 16.3+ MB

In [116]:
data_pre_fill = data_pre.fillna(0)
data_pre_fill

,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO
0,2004-05-09,2004-05-15,CENTRO OESTE,DISTRITO FEDERAL,ETANOL HIDRATADO,127,R$/l,1.288,0.016,1.190,1.350,0.463,0.012,0.825,0.110,0.4201,0.96660,0.133,5,2004
1,2004-05-09,2004-05-15,CENTRO OESTE,GOIAS,ETANOL HIDRATADO,387,R$/l,1.162,0.114,0.890,1.449,0.399,0.098,0.763,0.088,0.5013,1.05000,0.115,5,2004
2,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO,ETANOL HIDRATADO,192,R$/l,1.389,0.097,1.180,1.760,0.419,0.070,0.970,0.095,0.5614,1.16100,0.098,5,2004
3,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO DO SUL,ETANOL HIDRATADO,162,R$/l,1.262,0.070,1.090,1.509,0.432,0.055,0.830,0.119,0.5991,1.22242,0.143,5,2004
4,2004-05-09,2004-05-15,NORDESTE,ALAGOAS,ETANOL HIDRATADO,103,R$/l,1.181,0.078,1.050,1.400,0.240,0.066,0.941,0.077,0.7441,1.03170,0.082,5,2004
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
106818,2019-06-23,2019-06-29,NORDESTE,RIO GRANDE DO NORTE,GNV,7,R$/m3,3.574,0.065,3.499,3.690,0.818,0.018,2.756,0.000,2.7560,2.75600,0.000,6,2019
106819,2019-06-23,2019-06-29,SUL,RIO GRANDE DO SUL,GNV,23,R$/m3,3.401,0.129,3.230,3.789,0.950,0.038,2.451,0.402,1.9842,2.86610,0.164,6,2019
106820,2019-06-23,2019-06-29,SUL,SANTA CATARINA,GNV,24,R$/m3,2.912,0.190,2.699,3.499,0.914,0.065,1.998,0.000,1.9981,1.99810,0.000,6,2019
106821,2019-06-23,2019-06-29,SUDESTE,SAO PAULO,GNV,52,R$/m3,3.020,0.229,2.699,3.490,0.646,0.076,2.374,0.165,2.0179,2.50930,0.070,6,2019
106822,2019-06-23,2019-06-29,NORDESTE,SERGIPE,GNV,4,R$/m3,3.697,0.005,3.689,3.699,1.179,0.001,2.518,0.000,2.5175,2.51750,0.000,6,2019

In [117]:
data_pre_fill[mask]

,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO
1903,2005-09-25,2005-10-01,NORTE,PARA,ETANOL HIDRATADO,2,R$/l,1.694,0.283,1.690,2.090,0.0,0.167,0.0,0.0,0.0,0.0,0.0,9,2005
1958,2005-10-09,2005-10-15,NORTE,RORAIMA,ETANOL HIDRATADO,3,R$/l,2.000,0.000,2.000,2.000,0.0,0.000,0.0,0.0,0.0,0.0,0.0,10,2005
2012,2005-10-23,2005-10-29,NORTE,RORAIMA,ETANOL HIDRATADO,3,R$/l,2.277,0.023,2.250,2.290,0.0,0.010,0.0,0.0,0.0,0.0,0.0,10,2005
2497,2006-02-26,2006-03-04,NORTE,RORAIMA,ETANOL HIDRATADO,11,R$/l,2.182,0.040,2.100,2.200,0.0,0.018,0.0,0.0,0.0,0.0,0.0,2,2006
3199,2006-08-27,2006-09-02,NORTE,RORAIMA,ETANOL HIDRATADO,22,R$/l,2.285,0.068,1.980,2.300,0.0,0.030,0.0,0.0,0.0,0.0,0.0,8,2006
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
106664,2019-06-16,2019-06-22,SUDESTE,MINAS GERAIS,GNV,5,R$/m3,3.445,0.147,3.347,3.699,0.0,0.043,0.0,0.0,0.0,0.0,0.0,6,2019
106666,2019-06-16,2019-06-22,SUL,PARANA,GNV,7,R$/m3,3.132,0.295,3.049,3.890,0.0,0.094,0.0,0.0,0.0,0.0,0.0,6,2019
106811,2019-06-23,2019-06-29,SUDESTE,ESPIRITO SANTO,GNV,4,R$/m3,3.299,0.005,3.290,3.299,0.0,0.002,0.0,0.0,0.0,0.0,0.0,6,2019
106813,2019-06-23,2019-06-29,SUDESTE,MINAS GERAIS,GNV,6,R$/m3,3.548,0.100,3.495,3.699,0.0,0.028,0.0,0.0,0.0,0.0,0.0,6,2019
106815,2019-06-23,2019-06-29,SUL,PARANA,GNV,1,R$/m3,3.290,0.000,3.290,3.290,0.0,0.000,0.0,0.0,0.0,0.0,0.0,6,2019

In [119]:
data_pre_fill = data_pre.fillna(value={
    'PREÇO MÉDIO DISTRIBUIÇÃO' : 20,
    'DESVIO PADRÃO DISTRIBUIÇÃO' : 30,
    'PREÇO MÍNIMO DISTRIBUIÇÃO' : 40,
    'PREÇO MÁXIMO DISTRIBUIÇÃO' : 'vazio'
})

In [120]:
data_pre_fill[mask]

,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO
1903,2005-09-25,2005-10-01,NORTE,PARA,ETANOL HIDRATADO,2,R$/l,1.694,0.283,1.690,2.090,NaN,0.167,20.0,30.0,40.0,vazio,NaN,9,2005
1958,2005-10-09,2005-10-15,NORTE,RORAIMA,ETANOL HIDRATADO,3,R$/l,2.000,0.000,2.000,2.000,NaN,0.000,20.0,30.0,40.0,vazio,NaN,10,2005
2012,2005-10-23,2005-10-29,NORTE,RORAIMA,ETANOL HIDRATADO,3,R$/l,2.277,0.023,2.250,2.290,NaN,0.010,20.0,30.0,40.0,vazio,NaN,10,2005
2497,2006-02-26,2006-03-04,NORTE,RORAIMA,ETANOL HIDRATADO,11,R$/l,2.182,0.040,2.100,2.200,NaN,0.018,20.0,30.0,40.0,vazio,NaN,2,2006
3199,2006-08-27,2006-09-02,NORTE,RORAIMA,ETANOL HIDRATADO,22,R$/l,2.285,0.068,1.980,2.300,NaN,0.030,20.0,30.0,40.0,vazio,NaN,8,2006
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
106664,2019-06-16,2019-06-22,SUDESTE,MINAS GERAIS,GNV,5,R$/m3,3.445,0.147,3.347,3.699,NaN,0.043,20.0,30.0,40.0,vazio,NaN,6,2019
106666,2019-06-16,2019-06-22,SUL,PARANA,GNV,7,R$/m3,3.132,0.295,3.049,3.890,NaN,0.094,20.0,30.0,40.0,vazio,NaN,6,2019
106811,2019-06-23,2019-06-29,SUDESTE,ESPIRITO SANTO,GNV,4,R$/m3,3.299,0.005,3.290,3.299,NaN,0.002,20.0,30.0,40.0,vazio,NaN,6,2019
106813,2019-06-23,2019-06-29,SUDESTE,MINAS GERAIS,GNV,6,R$/m3,3.548,0.100,3.495,3.699,NaN,0.028,20.0,30.0,40.0,vazio,NaN,6,2019
106815,2019-06-23,2019-06-29,SUL,PARANA,GNV,1,R$/m3,3.290,0.000,3.290,3.290,NaN,0.000,20.0,30.0,40.0,vazio,NaN,6,2019

In [128]:
data_pre.dropna(inplace=True)
data_pre.info()

<class 'pandas.core.frame.DataFrame'>
Index: 103392 entries, 0 to 106822
Data columns (total 20 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   DATA INICIAL                   103392 non-null  datetime64[ns]
 1   DATA FINAL                     103392 non-null  datetime64[ns]
 2   REGIÃO                         103392 non-null  object
 3   ESTADO                         103392 non-null  object
 4   PRODUTO                        103392 non-null  object
 5   NÚMERO DE POSTOS PESQUISADOS   103392 non-null  int64
 6   UNIDADE DE MEDIDA              103392 non-null  object
 7   PREÇO MÉDIO REVENDA            103392 non-null  float64
 8   DESVIO PADRÃO REVENDA          103392 non-null  float64
 9   PREÇO MÍNIMO REVENDA           103392 non-null  float64
 10  PREÇO MÁXIMO REVENDA           103392 non-null  float64
 11  MARGEM MÉDIA REVENDA           103392 non-null  float64
 12  COEF DE VARIAÇÃO REVENDA       103392 non-null  float64
 13  PREÇO MÉDIO DISTRIBUIÇÃO       103392 non-null  float64
 14  DESVIO PADRÃO DISTRIBUIÇÃO     103392 non-null  float64
 15  PREÇO MÍNIMO DISTRIBUIÇÃO      103392 non-null  float64
 16  PREÇO MÁXIMO DISTRIBUIÇÃO      103392 non-null  float64
 17  COEF DE VARIAÇÃO DISTRIBUIÇÃO  103392 non-null  float64
 18  MÊS                            103392 non-null  int64
 19  ANO                            103392 non-null  int64
dtypes: datetime64[ns](2), float64(11), int64(3), object(4)
memory usage: 16.6+ MB

In [133]:
data_pre.to_csv('/home/youx/workspace-git/youxlab-treino-git/curso_dados/data.sets/ipynb.xave/xavecodingfinal.csv')

# 3 Estatísticas Descritivas

In [14]:
data_final = pd.read_csv('/home/youx/workspace-git/youxlab-treino-git/curso_dados/data.sets/ipynb.xave/xavecodingfinal.csv')
data_final

,Unnamed: 0,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,...,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO
0,0,2004-05-09,2004-05-15,CENTRO OESTE,DISTRITO FEDERAL,ETANOL HIDRATADO,127,R$/l,1.288,0.016,...,1.350,0.463,0.012,0.825,0.110,0.4201,0.96660,0.133,5,2004
1,1,2004-05-09,2004-05-15,CENTRO OESTE,GOIAS,ETANOL HIDRATADO,387,R$/l,1.162,0.114,...,1.449,0.399,0.098,0.763,0.088,0.5013,1.05000,0.115,5,2004
2,2,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO,ETANOL HIDRATADO,192,R$/l,1.389,0.097,...,1.760,0.419,0.070,0.970,0.095,0.5614,1.16100,0.098,5,2004
3,3,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO DO SUL,ETANOL HIDRATADO,162,R$/l,1.262,0.070,...,1.509,0.432,0.055,0.830,0.119,0.5991,1.22242,0.143,5,2004
4,4,2004-05-09,2004-05-15,NORDESTE,ALAGOAS,ETANOL HIDRATADO,103,R$/l,1.181,0.078,...,1.400,0.240,0.066,0.941,0.077,0.7441,1.03170,0.082,5,2004
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
103387,106818,2019-06-23,2019-06-29,NORDESTE,RIO GRANDE DO NORTE,GNV,7,R$/m3,3.574,0.065,...,3.690,0.818,0.018,2.756,0.000,2.7560,2.75600,0.000,6,2019
103388,106819,2019-06-23,2019-06-29,SUL,RIO GRANDE DO SUL,GNV,23,R$/m3,3.401,0.129,...,3.789,0.950,0.038,2.451,0.402,1.9842,2.86610,0.164,6,2019
103389,106820,2019-06-23,2019-06-29,SUL,SANTA CATARINA,GNV,24,R$/m3,2.912,0.190,...,3.499,0.914,0.065,1.998,0.000,1.9981,1.99810,0.000,6,2019
103390,106821,2019-06-23,2019-06-29,SUDESTE,SAO PAULO,GNV,52,R$/m3,3.020,0.229,...,3.490,0.646,0.076,2.374,0.165,2.0179,2.50930,0.070,6,2019
103391,106822,2019-06-23,2019-06-29,NORDESTE,SERGIPE,GNV,4,R$/m3,3.697,0.005,...,3.699,1.179,0.001,2.518,0.000,2.5175,2.51750,0.000,6,2019

In [15]:
data_final.describe()

,Unnamed: 0,NÚMERO DE POSTOS PESQUISADOS,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO
count,103392.000000,103392.000000,103392.000000,103392.000000,103392.000000,103392.000000,103392.000000,103392.000000,103392.000000,103392.000000,103392.000000,103392.000000,103392.000000,103392.000000,103392.000000
mean,52973.958682,240.511935,10.784472,0.652589,9.334931,12.458686,2.225151,0.045749,8.559322,0.559441,7.414814,9.805621,0.046640,6.485067,2011.737001
std,30968.261500,408.039174,17.685852,1.346422,15.024383,20.801190,4.375085,0.024488,13.603686,1.256914,11.681366,15.933999,0.042114,3.442155,4.410491
min,0.000000,1.000000,0.766000,0.000000,0.590000,0.999000,0.001000,0.000000,0.506000,0.000000,0.325700,0.599200,0.000000,1.000000,2004.000000
25%,25964.750000,47.000000,2.073000,0.073000,1.900000,2.330000,0.282000,0.030000,1.795000,0.047000,1.674400,1.945600,0.021000,4.000000,2008.000000
50%,52661.500000,108.000000,2.723000,0.115000,2.509000,3.000000,0.383000,0.042000,2.335000,0.077000,2.220000,2.507050,0.031000,6.000000,2012.000000
75%,79918.250000,251.000000,3.745000,0.190000,3.490000,4.150000,0.560000,0.058000,3.307000,0.151000,3.142800,3.520000,0.061000,9.000000,2016.000000
max,106822.000000,4167.000000,99.357000,10.748000,90.000000,120.000000,36.847000,0.262000,83.137000,18.385000,83.000000,94.500000,0.780000,12.000000,2019.000000

In [16]:
data_final['PREÇO MÉDIO REVENDA'].describe()

count    103392.000000
mean         10.784472
std          17.685852
min           0.766000
25%           2.073000
50%           2.723000
75%           3.745000
max          99.357000
Name: PREÇO MÉDIO REVENDA, dtype: float64

<p>tem outro jeito de fazer</p>

In [17]:
data_final.describe()['PREÇO MÉDIO REVENDA']

count    103392.000000
mean         10.784472
std          17.685852
min           0.766000
25%           2.073000
50%           2.723000
75%           3.745000
max          99.357000
Name: PREÇO MÉDIO REVENDA, dtype: float64

In [18]:
stats = data_final.describe()

In [19]:
stats[['PREÇO MÉDIO REVENDA', 'PREÇO MÁXIMO REVENDA', 'PREÇO MÉDIO DISTRIBUIÇÃO']]

       PREÇO MÉDIO REVENDA  PREÇO MÁXIMO REVENDA  PREÇO MÉDIO DISTRIBUIÇÃO
count        103392.000000         103392.000000             103392.000000
mean             10.784472             12.458686                  8.559322
std              17.685852             20.801190                 13.603686
min               0.766000              0.999000                  0.506000
25%               2.073000              2.330000                  1.795000
50%               2.723000              3.000000                  2.335000
75%               3.745000              4.150000                  3.307000
max              99.357000            120.000000                 83.137000

In [20]:
data_final[['PREÇO MÉDIO REVENDA', 'PREÇO MÁXIMO REVENDA', 'PREÇO MÉDIO DISTRIBUIÇÃO']].describe()

       PREÇO MÉDIO REVENDA  PREÇO MÁXIMO REVENDA  PREÇO MÉDIO DISTRIBUIÇÃO
count        103392.000000         103392.000000             103392.000000
mean             10.784472             12.458686                  8.559322
std              17.685852             20.801190                 13.603686
min               0.766000              0.999000                  0.506000
25%               2.073000              2.330000                  1.795000
50%               2.723000              3.000000                  2.335000
75%               3.745000              4.150000                  3.307000
max              99.357000            120.000000                 83.137000

In [21]:
stats

,Unnamed: 0,NÚMERO DE POSTOS PESQUISADOS,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO
count,103392.000000,103392.000000,103392.000000,103392.000000,103392.000000,103392.000000,103392.000000,103392.000000,103392.000000,103392.000000,103392.000000,103392.000000,103392.000000,103392.000000,103392.000000
mean,52973.958682,240.511935,10.784472,0.652589,9.334931,12.458686,2.225151,0.045749,8.559322,0.559441,7.414814,9.805621,0.046640,6.485067,2011.737001
std,30968.261500,408.039174,17.685852,1.346422,15.024383,20.801190,4.375085,0.024488,13.603686,1.256914,11.681366,15.933999,0.042114,3.442155,4.410491
min,0.000000,1.000000,0.766000,0.000000,0.590000,0.999000,0.001000,0.000000,0.506000,0.000000,0.325700,0.599200,0.000000,1.000000,2004.000000
25%,25964.750000,47.000000,2.073000,0.073000,1.900000,2.330000,0.282000,0.030000,1.795000,0.047000,1.674400,1.945600,0.021000,4.000000,2008.000000
50%,52661.500000,108.000000,2.723000,0.115000,2.509000,3.000000,0.383000,0.042000,2.335000,0.077000,2.220000,2.507050,0.031000,6.000000,2012.000000
75%,79918.250000,251.000000,3.745000,0.190000,3.490000,4.150000,0.560000,0.058000,3.307000,0.151000,3.142800,3.520000,0.061000,9.000000,2016.000000
max,106822.000000,4167.000000,99.357000,10.748000,90.000000,120.000000,36.847000,0.262000,83.137000,18.385000,83.000000,94.500000,0.780000,12.000000,2019.000000

In [22]:
stats.loc[['min', 'max', 'mean'], ['PREÇO MÉDIO REVENDA', 'PREÇO MÉDIO DISTRIBUIÇÃO']]

      PREÇO MÉDIO REVENDA  PREÇO MÉDIO DISTRIBUIÇÃO
min              0.766000                  0.506000
max             99.357000                 83.137000
mean            10.784472                  8.559322

In [23]:
data_final.head()

,Unnamed: 0,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,...,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO
0,0,2004-05-09,2004-05-15,CENTRO OESTE,DISTRITO FEDERAL,ETANOL HIDRATADO,127,R$/l,1.288,0.016,...,1.350,0.463,0.012,0.825,0.110,0.4201,0.96660,0.133,5,2004
1,1,2004-05-09,2004-05-15,CENTRO OESTE,GOIAS,ETANOL HIDRATADO,387,R$/l,1.162,0.114,...,1.449,0.399,0.098,0.763,0.088,0.5013,1.05000,0.115,5,2004
2,2,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO,ETANOL HIDRATADO,192,R$/l,1.389,0.097,...,1.760,0.419,0.070,0.970,0.095,0.5614,1.16100,0.098,5,2004
3,3,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO DO SUL,ETANOL HIDRATADO,162,R$/l,1.262,0.070,...,1.509,0.432,0.055,0.830,0.119,0.5991,1.22242,0.143,5,2004
4,4,2004-05-09,2004-05-15,NORDESTE,ALAGOAS,ETANOL HIDRATADO,103,R$/l,1.181,0.078,...,1.400,0.240,0.066,0.941,0.077,0.7441,1.03170,0.082,5,2004

In [24]:
data_final['PREÇO MÍNIMO REVENDA'].min()

np.float64(0.59)

In [25]:
mean = data_final['PREÇO MÍNIMO REVENDA'].mean()
std = data_final['PREÇO MÍNIMO REVENDA'].std()

print(f'A média dos preços mínimos de revenda é {mean:.2f} +- {std:.2f}')

A média dos preços mínimos de revenda é 9.33 +- 15.02

In [26]:
data_final['ESTADO']

0            DISTRITO FEDERAL
1                       GOIAS
2                 MATO GROSSO
3          MATO GROSSO DO SUL
4                     ALAGOAS
                 ...
103387    RIO GRANDE DO NORTE
103388      RIO GRANDE DO SUL
103389         SANTA CATARINA
103390              SAO PAULO
103391                SERGIPE
Name: ESTADO, Length: 103392, dtype: object

In [27]:
data_final['ESTADO'].unique()

array(['DISTRITO FEDERAL', 'GOIAS', 'MATO GROSSO', 'MATO GROSSO DO SUL',
       'ALAGOAS', 'BAHIA', 'CEARA', 'MARANHAO', 'PARAIBA', 'PERNAMBUCO',
       'PIAUI', 'RIO GRANDE DO NORTE', 'SERGIPE', 'ACRE', 'AMAPA',
       'AMAZONAS', 'PARA', 'RONDONIA', 'RORAIMA', 'TOCANTINS',
       'ESPIRITO SANTO', 'MINAS GERAIS', 'RIO DE JANEIRO', 'SAO PAULO',
       'PARANA', 'RIO GRANDE DO SUL', 'SANTA CATARINA'], dtype=object)

In [28]:
sorted(data_final['ESTADO'].unique())

['ACRE',
 'ALAGOAS',
 'AMAPA',
 'AMAZONAS',
 'BAHIA',
 'CEARA',
 'DISTRITO FEDERAL',
 'ESPIRITO SANTO',
 'GOIAS',
 'MARANHAO',
 'MATO GROSSO',
 'MATO GROSSO DO SUL',
 'MINAS GERAIS',
 'PARA',
 'PARAIBA',
 'PARANA',
 'PERNAMBUCO',
 'PIAUI',
 'RIO DE JANEIRO',
 'RIO GRANDE DO NORTE',
 'RIO GRANDE DO SUL',
 'RONDONIA',
 'RORAIMA',
 'SANTA CATARINA',
 'SAO PAULO',
 'SERGIPE',
 'TOCANTINS']

In [29]:
data_final['ESTADO'].value_counts()

ESTADO
BAHIA                  4263
RIO DE JANEIRO         4262
SAO PAULO              4261
RIO GRANDE DO SUL      4249
PARAIBA                4240
PERNAMBUCO             4236
SERGIPE                4202
SANTA CATARINA         4164
MINAS GERAIS           4142
ESPIRITO SANTO         4079
MATO GROSSO DO SUL     4076
ALAGOAS                4020
RIO GRANDE DO NORTE    3999
CEARA                  3964
PARANA                 3902
AMAZONAS               3713
MATO GROSSO            3703
PARA                   3477
MARANHAO               3470
ACRE                   3463
RORAIMA                3457
TOCANTINS              3453
GOIAS                  3449
RONDONIA               3441
PIAUI                  3394
DISTRITO FEDERAL       3317
AMAPA                  2996
Name: count, dtype: int64

In [30]:
data_final['ESTADO'].value_counts().to_frame()

                     count
ESTADO
BAHIA                 4263
RIO DE JANEIRO        4262
SAO PAULO             4261
RIO GRANDE DO SUL     4249
PARAIBA               4240
PERNAMBUCO            4236
SERGIPE               4202
SANTA CATARINA        4164
MINAS GERAIS          4142
ESPIRITO SANTO        4079
MATO GROSSO DO SUL    4076
ALAGOAS               4020
RIO GRANDE DO NORTE   3999
CEARA                 3964
PARANA                3902
AMAZONAS              3713
MATO GROSSO           3703
PARA                  3477
MARANHAO              3470
ACRE                  3463
RORAIMA               3457
TOCANTINS             3453
GOIAS                 3449
RONDONIA              3441
PIAUI                 3394
DISTRITO FEDERAL      3317
AMAPA                 2996

# 4 Executando funções

In [159]:
df = pd.DataFrame({ 'A': [1, 2, 3, 4], 
                    'B': [10, 20, 30, 40],
                    'C': [100, 200, 300, 400]},
                    index=['Linha 1', 'Linha 2', 'Linha 3', 'Linha 4'])

In [160]:
df

         A   B    C
Linha 1  1  10  100
Linha 2  2  20  200
Linha 3  3  30  300
Linha 4  4  40  400

In [161]:
def nossa_soma(series):
    return series.sum()

In [162]:
df['SOMA(A, B, C)'] = df.apply(nossa_soma, axis=1)
df

         A   B    C  SOMA(A, B, C)
Linha 1  1  10  100            111
Linha 2  2  20  200            222
Linha 3  3  30  300            333
Linha 4  4  40  400            444

In [163]:
df.loc['Linha 5'] = df.apply(nossa_soma, axis=0)
df

          A    B     C  SOMA(A, B, C)
Linha 1   1   10   100            111
Linha 2   2   20   200            222
Linha 3   3   30   300            333
Linha 4   4   40   400            444
Linha 5  10  100  1000           1110

In [164]:
df['MEDIA(A, B, C)'] = df[['A', 'B', 'C']].apply(lambda series: series.mean(), axis=1)
df

          A    B     C  SOMA(A, B, C)  MEDIA(A, B, C)
Linha 1   1   10   100            111            37.0
Linha 2   2   20   200            222            74.0
Linha 3   3   30   300            333           111.0
Linha 4   4   40   400            444           148.0
Linha 5  10  100  1000           1110           370.0

In [165]:
df['C * 2'] = df['C'].apply(lambda x: x * 2)
df

          A    B     C  SOMA(A, B, C)  MEDIA(A, B, C)  C * 2
Linha 1   1   10   100            111            37.0    200
Linha 2   2   20   200            222            74.0    400
Linha 3   3   30   300            333           111.0    600
Linha 4   4   40   400            444           148.0    800
Linha 5  10  100  1000           1110           370.0   2000

In [166]:
df['A * 2'] = df['A'] * 2
df

          A    B     C  SOMA(A, B, C)  MEDIA(A, B, C)  C * 2  A * 2
Linha 1   1   10   100            111            37.0    200      2
Linha 2   2   20   200            222            74.0    400      4
Linha 3   3   30   300            333           111.0    600      6
Linha 4   4   40   400            444           148.0    800      8
Linha 5  10  100  1000           1110           370.0   2000     20

In [167]:
df = pd.DataFrame({ 'A': [1, 2, 3, 4], 
                    'B': [10, 20, 30, 40],
                    'C': [100, 200, 300, 400]}, 
                     index=['Linha 1', 'Linha 2', 'Linha 3', 'Linha 4'])
df

         A   B    C
Linha 1  1  10  100
Linha 2  2  20  200
Linha 3  3  30  300
Linha 4  4  40  400

In [168]:
df.applymap(lambda x: x ** 2)

/tmp/ipykernel_9521/547004281.py:1: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df.applymap(lambda x: x ** 2)

          A     B       C
Linha 1   1   100   10000
Linha 2   4   400   40000
Linha 3   9   900   90000
Linha 4  16  1600  160000

In [169]:
df

         A   B    C
Linha 1  1  10  100
Linha 2  2  20  200
Linha 3  3  30  300
Linha 4  4  40  400

In [170]:
nomes = pd.Series(['João', 'Maria', 'Alice', 'Pedro'])
nomes

0     João
1    Maria
2    Alice
3    Pedro
dtype: object

In [171]:
nomes.map(lambda x: x.upper())

0     JOÃO
1    MARIA
2    ALICE
3    PEDRO
dtype: object

# 5 Agrupamento

In [172]:
data_final.head()

,Unnamed: 0,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,...,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO
0,0,2004-05-09,2004-05-15,CENTRO OESTE,DISTRITO FEDERAL,ETANOL HIDRATADO,127,R$/l,1.288,0.016,...,1.350,0.463,0.012,0.825,0.110,0.4201,0.96660,0.133,5,2004
1,1,2004-05-09,2004-05-15,CENTRO OESTE,GOIAS,ETANOL HIDRATADO,387,R$/l,1.162,0.114,...,1.449,0.399,0.098,0.763,0.088,0.5013,1.05000,0.115,5,2004
2,2,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO,ETANOL HIDRATADO,192,R$/l,1.389,0.097,...,1.760,0.419,0.070,0.970,0.095,0.5614,1.16100,0.098,5,2004
3,3,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO DO SUL,ETANOL HIDRATADO,162,R$/l,1.262,0.070,...,1.509,0.432,0.055,0.830,0.119,0.5991,1.22242,0.143,5,2004
4,4,2004-05-09,2004-05-15,NORDESTE,ALAGOAS,ETANOL HIDRATADO,103,R$/l,1.181,0.078,...,1.400,0.240,0.066,0.941,0.077,0.7441,1.03170,0.082,5,2004

In [173]:
grupos = data_final.groupby('REGIÃO')
grupos

In [174]:
grupos.groups

{'CENTRO OESTE': [0, 1, 2, 3, 27, 28, 29, 30, 54, 55, 56, 57, 81, 82, 83, 84, 108, 109, 110, 111, 135, 136, 137, 138, 162, 163, 164, 165, 189, 190, 191, 192, 216, 217, 218, 219, 243, 244, 245, 246, 270, 271, 272, 273, 297, 298, 299, 300, 324, 325, 326, 327, 351, 352, 353, 354, 378, 379, 380, 381, 405, 406, 407, 408, 432, 433, 434, 435, 459, 460, 461, 462, 486, 487, 488, 489, 513, 514, 515, 516, 540, 541, 542, 543, 567, 568, 569, 570, 594, 595, 596, 597, 621, 622, 623, 624, 648, 649, 650, 651, ...], 'NORDESTE': [4, 5, 6, 7, 8, 9, 10, 11, 12, 31, 32, 33, 34, 35, 36, 37, 38, 39, 58, 59, 60, 61, 62, 63, 64, 65, 66, 85, 86, 87, 88, 89, 90, 91, 92, 93, 112, 113, 114, 115, 116, 117, 118, 119, 120, 139, 140, 141, 142, 143, 144, 145, 146, 147, 166, 167, 168, 169, 170, 171, 172, 173, 174, 193, 194, 195, 196, 197, 198, 199, 200, 201, 220, 221, 222, 223, 224, 225, 226, 227, 228, 247, 248, 249, 250, 251, 252, 253, 254, 255, 274, 275, 276, 277, 278, 279, 280, 281, 282, 301, ...], 'NORTE': [13, 14, 15, 16, 17, 18, 19, 40, 41, 42, 43, 44, 45, 46, 67, 68, 69, 70, 71, 72, 73, 94, 95, 96, 97, 98, 99, 100, 121, 122, 123, 124, 125, 126, 127, 148, 149, 150, 151, 152, 153, 154, 175, 176, 177, 178, 179, 180, 181, 202, 203, 204, 205, 206, 207, 208, 229, 230, 231, 232, 233, 234, 235, 256, 257, 258, 259, 260, 261, 262, 283, 284, 285, 286, 287, 288, 289, 310, 311, 312, 313, 314, 315, 316, 337, 338, 339, 340, 341, 342, 343, 364, 365, 366, 367, 368, 369, 370, 391, 392, ...], 'SUDESTE': [20, 21, 22, 23, 47, 48, 49, 50, 74, 75, 76, 77, 101, 102, 103, 104, 128, 129, 130, 131, 155, 156, 157, 158, 182, 183, 184, 185, 209, 210, 211, 212, 236, 237, 238, 239, 263, 264, 265, 266, 290, 291, 292, 293, 317, 318, 319, 320, 344, 345, 346, 347, 371, 372, 373, 374, 398, 399, 400, 401, 425, 426, 427, 428, 452, 453, 454, 455, 479, 480, 481, 482, 506, 507, 508, 509, 533, 534, 535, 536, 560, 561, 562, 563, 587, 588, 589, 590, 614, 615, 616, 617, 641, 642, 643, 644, 668, 669, 670, 671, ...], 'SUL': [24, 25, 26, 51, 52, 53, 78, 79, 80, 105, 106, 107, 132, 133, 134, 159, 160, 161, 186, 187, 188, 213, 214, 215, 240, 241, 242, 267, 268, 269, 294, 295, 296, 321, 322, 323, 348, 349, 350, 375, 376, 377, 402, 403, 404, 429, 430, 431, 456, 457, 458, 483, 484, 485, 510, 511, 512, 537, 538, 539, 564, 565, 566, 591, 592, 593, 618, 619, 620, 645, 646, 647, 672, 673, 674, 699, 700, 701, 726, 727, 728, 753, 754, 755, 780, 781, 782, 807, 808, 809, 834, 835, 836, 861, 862, 863, 888, 889, 890, 915, ...]}

In [175]:
grupos.indices

{'CENTRO OESTE': array([     0,      1,      2, ..., 103363, 103364, 103383],
       shape=(14545,)),
 'NORDESTE': array([     4,      5,      6, ..., 103385, 103387, 103391],
       shape=(35788,)),
 'NORTE': array([    13,     14,     15, ..., 103374, 103375, 103379],
       shape=(24000,)),
 'SUDESTE': array([    20,     21,     22, ..., 103377, 103386, 103390],
       shape=(16744,)),
 'SUL': array([    24,     25,     26, ..., 103376, 103388, 103389],
       shape=(12315,))}

In [176]:
grupos.get_group('CENTRO OESTE')

,Unnamed: 0,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,...,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO
0,0,2004-05-09,2004-05-15,CENTRO OESTE,DISTRITO FEDERAL,ETANOL HIDRATADO,127,R$/l,1.288,0.016,...,1.350,0.463,0.012,0.825,0.110,0.4201,0.96660,0.133,5,2004
1,1,2004-05-09,2004-05-15,CENTRO OESTE,GOIAS,ETANOL HIDRATADO,387,R$/l,1.162,0.114,...,1.449,0.399,0.098,0.763,0.088,0.5013,1.05000,0.115,5,2004
2,2,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO,ETANOL HIDRATADO,192,R$/l,1.389,0.097,...,1.760,0.419,0.070,0.970,0.095,0.5614,1.16100,0.098,5,2004
3,3,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO DO SUL,ETANOL HIDRATADO,162,R$/l,1.262,0.070,...,1.509,0.432,0.055,0.830,0.119,0.5991,1.22242,0.143,5,2004
27,27,2004-05-16,2004-05-22,CENTRO OESTE,DISTRITO FEDERAL,ETANOL HIDRATADO,144,R$/l,1.271,0.039,...,1.300,0.448,0.031,0.823,0.111,0.4094,1.19310,0.135,5,2004
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
103359,106787,2019-06-23,2019-06-29,CENTRO OESTE,DISTRITO FEDERAL,GLP,42,R$/13Kg,73.452,4.875,...,95.000,21.509,0.066,51.943,7.877,44.0000,62.82000,0.152,6,2019
103361,106789,2019-06-23,2019-06-29,CENTRO OESTE,GOIAS,GLP,209,R$/13Kg,71.968,5.381,...,85.000,15.044,0.075,56.924,4.285,45.5700,61.60000,0.075,6,2019
103363,106791,2019-06-23,2019-06-29,CENTRO OESTE,MATO GROSSO,GLP,95,R$/13Kg,96.691,6.835,...,115.000,19.789,0.071,76.902,8.846,61.1500,90.00000,0.115,6,2019
103364,106792,2019-06-23,2019-06-29,CENTRO OESTE,MATO GROSSO DO SUL,GLP,115,R$/13Kg,72.297,8.054,...,99.000,16.707,0.111,55.590,5.109,47.0000,72.00000,0.092,6,2019
103383,106812,2019-06-23,2019-06-29,CENTRO OESTE,MATO GROSSO DO SUL,GNV,2,R$/m3,2.934,0.049,...,2.968,0.901,0.017,2.033,0.259,1.8500,2.21610,0.127,6,2019

In [177]:
grupos.describe()

             Unnamed: 0                                                       \
                  count          mean           std   min       25%      50%
REGIÃO
CENTRO OESTE    14545.0  52794.848127  31380.202472   0.0  24647.00  53023.0
NORDESTE        35788.0  53022.749022  30768.203891   4.0  26854.25  51922.5
NORTE           24000.0  52735.865958  31714.571691  13.0  23526.75  54011.5
SUDESTE         16744.0  53281.350334  30332.349374  20.0  28253.75  52127.5
SUL             12315.0  53089.777913  30437.425938  24.0  27716.50  51968.0

                                NÚMERO DE POSTOS PESQUISADOS              ...  \
                  75%       max                        count        mean  ...
REGIÃO                                                                    ...
CENTRO OESTE  80299.0  106812.0                      14545.0  144.898453  ...
NORDESTE      79910.5  106822.0                      35788.0  124.721834  ...
NORTE         80343.5  106807.0                      24000.0   67.835958  ...
SUDESTE       79401.5  106821.0                      16744.0  726.068024  ...
SUL           79332.5  106820.0                      12315.0  366.266423  ...

               MÊS            ANO                                         \
               75%   max    count         mean       std     min     25%
REGIÃO
CENTRO OESTE   9.0  12.0  14545.0  2011.773599  4.409036  2004.0  2008.0
NORDESTE      10.0  12.0  35788.0  2011.704454  4.418046  2004.0  2008.0
NORTE          9.0  12.0  24000.0  2011.812083  4.410914  2004.0  2008.0
SUDESTE        9.0  12.0  16744.0  2011.707895  4.395436  2004.0  2008.0
SUL            9.0  12.0  12315.0  2011.681608  4.408312  2004.0  2008.0


                 50%     75%     max
REGIÃO
CENTRO OESTE  2012.0  2016.0  2019.0
NORDESTE      2012.0  2016.0  2019.0
NORTE         2012.0  2016.0  2019.0
SUDESTE       2012.0  2016.0  2019.0
SUL           2012.0  2015.0  2019.0

[5 rows x 120 columns]

In [178]:
grupos.min()

,Unnamed: 0,DATA INICIAL,DATA FINAL,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO
REGIÃO,,,,,,,,,,,,,,,,,,,,
CENTRO OESTE,0,2004-05-09,2004-05-15,DISTRITO FEDERAL,ETANOL HIDRATADO,1,R$/13Kg,1.097,0.0,0.87,1.099,0.031,0.0,0.737,0.0,0.38790,0.8359,0.0,1,2004
NORDESTE,4,2004-05-09,2004-05-15,ALAGOAS,ETANOL HIDRATADO,1,R$/13Kg,0.975,0.0,0.79,0.999,0.039,0.0,0.586,0.0,0.36320,0.5992,0.0,1,2004
NORTE,13,2004-05-09,2004-05-15,ACRE,ETANOL HIDRATADO,1,R$/13Kg,1.226,0.0,1.05,1.300,0.022,0.0,0.674,0.0,0.51022,0.9612,0.0,1,2004
SUDESTE,20,2004-05-09,2004-05-15,ESPIRITO SANTO,ETANOL HIDRATADO,1,R$/13Kg,0.766,0.0,0.59,1.099,0.001,0.0,0.506,0.0,0.32570,0.7822,0.0,1,2004
SUL,24,2004-05-09,2004-05-15,PARANA,ETANOL HIDRATADO,1,R$/13Kg,0.922,0.0,0.73,1.199,0.025,0.0,0.667,0.0,0.43000,0.7044,0.0,1,2004

In [179]:
data_final.groupby('REGIÃO').min()

,Unnamed: 0,DATA INICIAL,DATA FINAL,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO
REGIÃO,,,,,,,,,,,,,,,,,,,,
CENTRO OESTE,0,2004-05-09,2004-05-15,DISTRITO FEDERAL,ETANOL HIDRATADO,1,R$/13Kg,1.097,0.0,0.87,1.099,0.031,0.0,0.737,0.0,0.38790,0.8359,0.0,1,2004
NORDESTE,4,2004-05-09,2004-05-15,ALAGOAS,ETANOL HIDRATADO,1,R$/13Kg,0.975,0.0,0.79,0.999,0.039,0.0,0.586,0.0,0.36320,0.5992,0.0,1,2004
NORTE,13,2004-05-09,2004-05-15,ACRE,ETANOL HIDRATADO,1,R$/13Kg,1.226,0.0,1.05,1.300,0.022,0.0,0.674,0.0,0.51022,0.9612,0.0,1,2004
SUDESTE,20,2004-05-09,2004-05-15,ESPIRITO SANTO,ETANOL HIDRATADO,1,R$/13Kg,0.766,0.0,0.59,1.099,0.001,0.0,0.506,0.0,0.32570,0.7822,0.0,1,2004
SUL,24,2004-05-09,2004-05-15,PARANA,ETANOL HIDRATADO,1,R$/13Kg,0.922,0.0,0.73,1.199,0.025,0.0,0.667,0.0,0.43000,0.7044,0.0,1,2004

In [180]:
data_final.head()

,Unnamed: 0,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,...,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO
0,0,2004-05-09,2004-05-15,CENTRO OESTE,DISTRITO FEDERAL,ETANOL HIDRATADO,127,R$/l,1.288,0.016,...,1.350,0.463,0.012,0.825,0.110,0.4201,0.96660,0.133,5,2004
1,1,2004-05-09,2004-05-15,CENTRO OESTE,GOIAS,ETANOL HIDRATADO,387,R$/l,1.162,0.114,...,1.449,0.399,0.098,0.763,0.088,0.5013,1.05000,0.115,5,2004
2,2,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO,ETANOL HIDRATADO,192,R$/l,1.389,0.097,...,1.760,0.419,0.070,0.970,0.095,0.5614,1.16100,0.098,5,2004
3,3,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO DO SUL,ETANOL HIDRATADO,162,R$/l,1.262,0.070,...,1.509,0.432,0.055,0.830,0.119,0.5991,1.22242,0.143,5,2004
4,4,2004-05-09,2004-05-15,NORDESTE,ALAGOAS,ETANOL HIDRATADO,103,R$/l,1.181,0.078,...,1.400,0.240,0.066,0.941,0.077,0.7441,1.03170,0.082,5,2004

In [181]:
grupos = data_final.groupby(['REGIÃO', 'PRODUTO'])
grupos

In [184]:
grupos.groups

{('CENTRO OESTE', 'ETANOL HIDRATADO'): [0, 1, 2, 3, 27, 28, 29, 30, 54, 55, 56, 57, 81, 82, 83, 84, 108, 109, 110, 111, 135, 136, 137, 138, 162, 163, 164, 165, 189, 190, 191, 192, 216, 217, 218, 219, 243, 244, 245, 246, 270, 271, 272, 273, 297, 298, 299, 300, 324, 325, 326, 327, 351, 352, 353, 354, 378, 379, 380, 381, 405, 406, 407, 408, 432, 433, 434, 435, 459, 460, 461, 462, 486, 487, 488, 489, 513, 514, 515, 516, 540, 541, 542, 543, 567, 568, 569, 570, 594, 595, 596, 597, 621, 622, 623, 624, 648, 649, 650, 651, ...], ('CENTRO OESTE', 'GASOLINA COMUM'): [11980, 11981, 11982, 11983, 12007, 12008, 12009, 12010, 12034, 12035, 12036, 12037, 12061, 12062, 12063, 12064, 12088, 12089, 12090, 12091, 12115, 12116, 12117, 12118, 12142, 12143, 12144, 12145, 12169, 12170, 12171, 12172, 12196, 12197, 12198, 12199, 12223, 12224, 12225, 12226, 12250, 12251, 12252, 12253, 12277, 12278, 12279, 12280, 12304, 12305, 12306, 12307, 12331, 12332, 12333, 12334, 12358, 12359, 12360, 12361, 12385, 12386, 12387, 12388, 12412, 12413, 12414, 12415, 12439, 12440, 12441, 12442, 12466, 12467, 12468, 12469, 12493, 12494, 12495, 12496, 12520, 12521, 12522, 12523, 12547, 12548, 12549, 12550, 12574, 12575, 12576, 12577, 12601, 12602, 12603, 12604, 12628, 12629, 12630, 12631, ...], ('CENTRO OESTE', 'GLP'): [24019, 24020, 24021, 24022, 24046, 24047, 24048, 24049, 24073, 24074, 24075, 24076, 24100, 24101, 24102, 24103, 24127, 24128, 24129, 24130, 24154, 24155, 24156, 24157, 24181, 24182, 24183, 24184, 24208, 24209, 24210, 24211, 24235, 24236, 24237, 24238, 24262, 24263, 24264, 24265, 24289, 24290, 24291, 24292, 24316, 24317, 24318, 24319, 24343, 24344, 24345, 24346, 24370, 24371, 24372, 24373, 24397, 24398, 24399, 24400, 24424, 24425, 24426, 24427, 24451, 24452, 24453, 24454, 24478, 24479, 24480, 24481, 24505, 24506, 24507, 24508, 24532, 24533, 24534, 24535, 24558, 24559, 24560, 24561, 24585, 24586, 24587, 24588, 24612, 24613, 24614, 24615, 24639, 24640, 24641, 24642, 24666, 24667, 24668, 24669, ...], ('CENTRO OESTE', 'GNV'): [35892, 35907, 35922, 35937, 35952, 35967, 35982, 35997, 36012, 36027, 36042, 36057, 36072, 36087, 36102, 36117, 36132, 36147, 36162, 36177, 36192, 36207, 36222, 36237, 36252, 36267, 36283, 36298, 36313, 36329, 36345, 36360, 36375, 36390, 36405, 36420, 36436, 36451, 36466, 36481, 36495, 36510, 36525, 36541, 36557, 36572, 36588, 36604, 36620, 36635, 36650, 36665, 36680, 36695, 36710, 36725, 36740, 36755, 36770, 36785, 36800, 36815, 36830, 36845, 36860, 36875, 36890, 36918, 36932, 36948, 36962, 36991, 37006, 37021, 37037, 37053, 37068, 37084, 37100, 37116, 37132, 37148, 37164, 37180, 37196, 37212, 37228, 37244, 37259, 37275, 37291, 37307, 37323, 37339, 37355, 37371, 37387, 37403, 37419, 37435, ...], ('CENTRO OESTE', 'ÓLEO DIESEL'): [42612, 42613, 42614, 42615, 42639, 42640, 42641, 42642, 42666, 42667, 42668, 42669, 42693, 42694, 42695, 42696, 42720, 42721, 42722, 42723, 42747, 42748, 42749, 42750, 42774, 42775, 42776, 42777, 42801, 42802, 42803, 42804, 42828, 42829, 42830, 42831, 42855, 42856, 42857, 42858, 42882, 42883, 42884, 42885, 42909, 42910, 42911, 42912, 42936, 42937, 42938, 42939, 42963, 42964, 42965, 42966, 42990, 42991, 42992, 42993, 43017, 43018, 43019, 43020, 43044, 43045, 43046, 43047, 43071, 43072, 43073, 43074, 43098, 43099, 43100, 43101, 43125, 43126, 43127, 43128, 43152, 43153, 43154, 43155, 43179, 43180, 43181, 43182, 43206, 43207, 43208, 43209, 43233, 43234, 43235, 43236, 43260, 43261, 43262, 43263, ...], ('CENTRO OESTE', 'ÓLEO DIESEL S10'): [54834, 54835, 54973, 54975, 54976, 55117, 55119, 55120, 55260, 55262, 55264, 55265, 55405, 55407, 55408, 55549, 55551, 55552, 55692, 55694, 55695, 55835, 55837, 55838, 55981, 55983, 55984, 56128, 56130, 56131, 56276, 56278, 56279, 56421, 56423, 56424, 56566, 56568, 56569, 56711, 56713, 56714, 56854, 56856, 56858, 56859, 57002, 57004, 57006, 57007, 57148, 57150, 57152, 57153, 57293, 57295, 57297, 57298, 57440, 57442, 57444, 57445, 57586, 57588, 57590, 57591, 57732, 57734, 57736, 57737, 57879, 57881, 57883, 57884, 58027, 58029, 58030, 58174, 58176, 58177, 58317, 58319, 58320, 58461, 58463, 58464, 58607, 58609, 58610, 58750, 58752, 58753, 58894, 58896, 58897, 59040, 59042, 59043, 59184, 59186, ...], ('NORDESTE', 'ETANOL HIDRATADO'): [4, 5, 6, 7, 8, 9, 10, 11, 12, 31, 32, 33, 34, 35, 36, 37, 38, 39, 58, 59, 60, 61, 62, 63, 64, 65, 66, 85, 86, 87, 88, 89, 90, 91, 92, 93, 112, 113, 114, 115, 116, 117, 118, 119, 120, 139, 140, 141, 142, 143, 144, 145, 146, 147, 166, 167, 168, 169, 170, 171, 172, 173, 174, 193, 194, 195, 196, 197, 198, 199, 200, 201, 220, 221, 222, 223, 224, 225, 226, 227, 228, 247, 248, 249, 250, 251, 252, 253, 254, 255, 274, 275, 276, 277, 278, 279, 280, 281, 282, 301, ...], ('NORDESTE', 'GASOLINA COMUM'): [11984, 11985, 11986, 11987, 11988, 11989, 11990, 11991, 11992, 12011, 12012, 12013, 12014, 12015, 12016, 12017, 12018, 12019, 12038, 12039, 12040, 12041, 12042, 12043, 12044, 12045, 12046, 12065, 12066, 12067, 12068, 12069, 12070, 12071, 12072, 12073, 12092, 12093, 12094, 12095, 12096, 12097, 12098, 12099, 12100, 12119, 12120, 12121, 12122, 12123, 12124, 12125, 12126, 12127, 12146, 12147, 12148, 12149, 12150, 12151, 12152, 12153, 12154, 12173, 12174, 12175, 12176, 12177, 12178, 12179, 12180, 12181, 12200, 12201, 12202, 12203, 12204, 12205, 12206, 12207, 12208, 12227, 12228, 12229, 12230, 12231, 12232, 12233, 12234, 12235, 12254, 12255, 12256, 12257, 12258, 12259, 12260, 12261, 12262, 12281, ...], ('NORDESTE', 'GLP'): [24023, 24024, 24025, 24026, 24027, 24028, 24029, 24030, 24031, 24050, 24051, 24052, 24053, 24054, 24055, 24056, 24057, 24058, 24077, 24078, 24079, 24080, 24081, 24082, 24083, 24084, 24085, 24104, 24105, 24106, 24107, 24108, 24109, 24110, 24111, 24112, 24131, 24132, 24133, 24134, 24135, 24136, 24137, 24138, 24139, 24158, 24159, 24160, 24161, 24162, 24163, 24164, 24165, 24166, 24185, 24186, 24187, 24188, 24189, 24190, 24191, 24192, 24193, 24212, 24213, 24214, 24215, 24216, 24217, 24218, 24219, 24220, 24239, 24240, 24241, 24242, 24243, 24244, 24245, 24246, 24247, 24266, 24267, 24268, 24269, 24270, 24271, 24272, 24273, 24274, 24293, 24294, 24295, 24296, 24297, 24298, 24299, 24300, 24301, 24320, ...], ('NORDESTE', 'GNV'): [35893, 35894, 35895, 35896, 35897, 35898, 35899, 35908, 35909, 35910, 35911, 35912, 35913, 35914, 35923, 35924, 35925, 35926, 35927, 35928, 35929, 35938, 35939, 35940, 35941, 35942, 35943, 35944, 35953, 35954, 35955, 35956, 35957, 35958, 35959, 35968, 35969, 35970, 35971, 35972, 35973, 35974, 35983, 35984, 35985, 35986, 35987, 35988, 35989, 35998, 35999, 36000, 36001, 36002, 36003, 36004, 36013, 36014, 36015, 36016, 36017, 36018, 36019, 36028, 36029, 36030, 36031, 36032, 36033, 36034, 36043, 36044, 36045, 36046, 36047, 36048, 36049, 36058, 36059, 36060, 36061, 36062, 36063, 36064, 36073, 36074, 36075, 36076, 36077, 36078, 36079, 36088, 36089, 36090, 36091, 36092, 36093, 36094, 36103, 36104, ...], ('NORDESTE', 'ÓLEO DIESEL'): [42616, 42617, 42618, 42619, 42620, 42621, 42622, 42623, 42624, 42643, 42644, 42645, 42646, 42647, 42648, 42649, 42650, 42651, 42670, 42671, 42672, 42673, 42674, 42675, 42676, 42677, 42678, 42697, 42698, 42699, 42700, 42701, 42702, 42703, 42704, 42705, 42724, 42725, 42726, 42727, 42728, 42729, 42730, 42731, 42732, 42751, 42752, 42753, 42754, 42755, 42756, 42757, 42758, 42759, 42778, 42779, 42780, 42781, 42782, 42783, 42784, 42785, 42786, 42805, 42806, 42807, 42808, 42809, 42810, 42811, 42812, 42813, 42832, 42833, 42834, 42835, 42836, 42837, 42838, 42839, 42840, 42859, 42860, 42861, 42862, 42863, 42864, 42865, 42866, 42867, 42886, 42887, 42888, 42889, 42890, 42891, 42892, 42893, 42894, 42913, ...], ('NORDESTE', 'ÓLEO DIESEL S10'): [54702, 54703, 54706, 54707, 54829, 54831, 54832, 54833, 54839, 54840, 54842, 54847, 54968, 54970, 54971, 54974, 54979, 54981, 54982, 54984, 54989, 55112, 55114, 55115, 55118, 55123, 55125, 55126, 55128, 55133, 55256, 55258, 55259, 55263, 55268, 55270, 55271, 55273, 55278, 55400, 55402, 55403, 55406, 55411, 55413, 55414, 55416, 55421, 55544, 55546, 55547, 55550, 55555, 55557, 55558, 55560, 55565, 55687, 55689, 55690, 55693, 55698, 55700, 55701, 55703, 55708, 55830, 55832, 55833, 55836, 55841, 55843, 55844, 55846, 55852, 55976, 55978, 55979, 55982, 55987, 55989, 55990, 55992, 55998, 56122, 56125, 56126, 56129, 56134, 56136, 56137, 56139, 56145, 56270, 56273, 56274, 56277, 56282, 56284, 56285, ...], ('NORTE', 'ETANOL HIDRATADO'): [13, 14, 15, 16, 17, 18, 19, 40, 41, 42, 43, 44, 45, 46, 67, 68, 69, 70, 71, 72, 73, 94, 95, 96, 97, 98, 99, 100, 121, 122, 123, 124, 125, 126, 127, 148, 149, 150, 151, 152, 153, 154, 175, 176, 177, 178, 179, 180, 181, 202, 203, 204, 205, 206, 207, 208, 229, 230, 231, 232, 233, 234, 235, 256, 257, 258, 259, 260, 261, 262, 283, 284, 285, 286, 287, 288, 289, 310, 311, 312, 313, 314, 315, 316, 337, 338, 339, 340, 341, 342, 343, 364, 365, 366, 367, 368, 369, 370, 391, 392, ...], ('NORTE', 'GASOLINA COMUM'): [11993, 11994, 11995, 11996, 11997, 11998, 11999, 12020, 12021, 12022, 12023, 12024, 12025, 12026, 12047, 12048, 12049, 12050, 12051, 12052, 12053, 12074, 12075, 12076, 12077, 12078, 12079, 12080, 12101, 12102, 12103, 12104, 12105, 12106, 12107, 12128, 12129, 12130, 12131, 12132, 12133, 12134, 12155, 12156, 12157, 12158, 12159, 12160, 12161, 12182, 12183, 12184, 12185, 12186, 12187, 12188, 12209, 12210, 12211, 12212, 12213, 12214, 12215, 12236, 12237, 12238, 12239, 12240, 12241, 12242, 12263, 12264, 12265, 12266, 12267, 12268, 12269, 12290, 12291, 12292, 12293, 12294, 12295, 12296, 12317, 12318, 12319, 12320, 12321, 12322, 12323, 12344, 12345, 12346, 12347, 12348, 12349, 12350, 12371, 12372, ...], ('NORTE', 'GLP'): [24032, 24033, 24034, 24035, 24036, 24037, 24038, 24059, 24060, 24061, 24062, 24063, 24064, 24065, 24086, 24087, 24088, 24089, 24090, 24091, 24092, 24113, 24114, 24115, 24116, 24117, 24118, 24119, 24140, 24141, 24142, 24143, 24144, 24145, 24146, 24167, 24168, 24169, 24170, 24171, 24172, 24173, 24194, 24195, 24196, 24197, 24198, 24199, 24200, 24221, 24222, 24223, 24224, 24225, 24226, 24227, 24248, 24249, 24250, 24251, 24252, 24253, 24254, 24275, 24276, 24277, 24278, 24279, 24280, 24281, 24302, 24303, 24304, 24305, 24306, 24307, 24308, 24329, 24330, 24331, 24332, 24333, 24334, 24335, 24356, 24357, 24358, 24359, 24360, 24361, 24362, 24383, 24384, 24385, 24386, 24387, 24388, 24389, 24410, 24411, ...], ('NORTE', 'GNV'): [36940, 37029, 37045, 37076, 37092, 37108, 37124, 37140, 37156, 37172, 37188, 37204, 37220, 37236, 37267, 37283, 37299, 37315, 37331, 37347, 37363, 37379, 37395, 37411, 37427, 37443, 37459, 37475, 37491, 37507, 37524, 37540, 37556, 37572, 37589, 37606, 37622, 37639, 37655, 37671, 37687, 37704, 37721, 37752, 37768, 37783, 37799, 37816, 37833, 37849, 37865, 37882, 37898, 37914, 37931, 37947, 37963, 37979, 37995, 38011, 38027, 38043, 38059, 38075, 38091, 38122, 38169, 38202, 38218, 38235, 38252, 38269, 38302, 38319, 38336, 38369, 38402, 38434, 38466, 39051, 39082, 39099, 39553, 39628, 39644, 40219, 40574, 40634, 40663, 40694, 41442, 42148, 42235, 42350, 42379, 42394, 42423, 42438, 42466, 42537, ...], ('NORTE', 'ÓLEO DIESEL'): [42625, 42626, 42627, 42628, 42629, 42630, 42631, 42652, 42653, 42654, 42655, 42656, 42657, 42658, 42679, 42680, 42681, 42682, 42683, 42684, 42685, 42706, 42707, 42708, 42709, 42710, 42711, 42712, 42733, 42734, 42735, 42736, 42737, 42738, 42739, 42760, 42761, 42762, 42763, 42764, 42765, 42766, 42787, 42788, 42789, 42790, 42791, 42792, 42793, 42814, 42815, 42816, 42817, 42818, 42819, 42820, 42841, 42842, 42843, 42844, 42845, 42846, 42847, 42868, 42869, 42870, 42871, 42872, 42873, 42874, 42895, 42896, 42897, 42898, 42899, 42900, 42901, 42922, 42923, 42924, 42925, 42926, 42927, 42928, 42949, 42950, 42951, 42952, 42953, 42954, 42955, 42976, 42977, 42978, 42979, 42980, 42981, 42982, 43003, 43004, ...], ('NORTE', 'ÓLEO DIESEL S10'): [54705, 54709, 54830, 54837, 54844, 54969, 54978, 54986, 55111, 55113, 55122, 55130, 55257, 55267, 55275, 55399, 55401, 55410, 55418, 55422, 55543, 55545, 55554, 55562, 55566, 55686, 55688, 55697, 55705, 55709, 55829, 55831, 55840, 55848, 55849, 55853, 55975, 55977, 55986, 55994, 55995, 55999, 56121, 56123, 56124, 56133, 56141, 56142, 56146, 56269, 56271, 56272, 56281, 56289, 56290, 56294, 56414, 56416, 56417, 56426, 56434, 56435, 56439, 56559, 56561, 56562, 56571, 56579, 56580, 56584, 56704, 56706, 56707, 56716, 56724, 56725, 56729, 56848, 56850, 56851, 56861, 56869, 56870, 56874, 56996, 56998, 56999, 57009, 57017, 57018, 57022, 57142, 57144, 57145, 57155, 57163, 57164, 57168, 57287, 57289, ...], ('SUDESTE', 'ETANOL HIDRATADO'): [20, 21, 22, 23, 47, 48, 49, 50, 74, 75, 76, 77, 101, 102, 103, 104, 128, 129, 130, 131, 155, 156, 157, 158, 182, 183, 184, 185, 209, 210, 211, 212, 236, 237, 238, 239, 263, 264, 265, 266, 290, 291, 292, 293, 317, 318, 319, 320, 344, 345, 346, 347, 371, 372, 373, 374, 398, 399, 400, 401, 425, 426, 427, 428, 452, 453, 454, 455, 479, 480, 481, 482, 506, 507, 508, 509, 533, 534, 535, 536, 560, 561, 562, 563, 587, 588, 589, 590, 614, 615, 616, 617, 641, 642, 643, 644, 668, 669, 670, 671, ...], ('SUDESTE', 'GASOLINA COMUM'): [12000, 12001, 12002, 12003, 12027, 12028, 12029, 12030, 12054, 12055, 12056, 12057, 12081, 12082, 12083, 12084, 12108, 12109, 12110, 12111, 12135, 12136, 12137, 12138, 12162, 12163, 12164, 12165, 12189, 12190, 12191, 12192, 12216, 12217, 12218, 12219, 12243, 12244, 12245, 12246, 12270, 12271, 12272, 12273, 12297, 12298, 12299, 12300, 12324, 12325, 12326, 12327, 12351, 12352, 12353, 12354, 12378, 12379, 12380, 12381, 12405, 12406, 12407, 12408, 12432, 12433, 12434, 12435, 12459, 12460, 12461, 12462, 12486, 12487, 12488, 12489, 12513, 12514, 12515, 12516, 12540, 12541, 12542, 12543, 12567, 12568, 12569, 12570, 12594, 12595, 12596, 12597, 12621, 12622, 12623, 12624, 12648, 12649, 12650, 12651, ...], ('SUDESTE', 'GLP'): [24039, 24040, 24041, 24042, 24066, 24067, 24068, 24069, 24093, 24094, 24095, 24096, 24120, 24121, 24122, 24123, 24147, 24148, 24149, 24150, 24174, 24175, 24176, 24177, 24201, 24202, 24203, 24204, 24228, 24229, 24230, 24231, 24255, 24256, 24257, 24258, 24282, 24283, 24284, 24285, 24309, 24310, 24311, 24312, 24336, 24337, 24338, 24339, 24363, 24364, 24365, 24366, 24390, 24391, 24392, 24393, 24417, 24418, 24419, 24420, 24444, 24445, 24446, 24447, 24471, 24472, 24473, 24474, 24498, 24499, 24500, 24501, 24525, 24526, 24527, 24528, 24551, 24552, 24553, 24554, 24578, 24579, 24580, 24581, 24605, 24606, 24607, 24608, 24632, 24633, 24634, 24635, 24659, 24660, 24661, 24662, 24686, 24687, 24688, 24689, ...], ('SUDESTE', 'GNV'): [35900, 35901, 35902, 35903, 35915, 35916, 35917, 35918, 35930, 35931, 35932, 35933, 35945, 35946, 35947, 35948, 35960, 35961, 35962, 35963, 35975, 35976, 35977, 35978, 35990, 35991, 35992, 35993, 36005, 36006, 36007, 36008, 36020, 36021, 36022, 36023, 36035, 36036, 36037, 36038, 36050, 36051, 36052, 36053, 36065, 36066, 36067, 36068, 36080, 36081, 36082, 36083, 36095, 36096, 36097, 36098, 36110, 36111, 36112, 36113, 36125, 36126, 36127, 36128, 36140, 36141, 36142, 36143, 36155, 36156, 36157, 36158, 36170, 36171, 36172, 36173, 36185, 36186, 36187, 36188, 36200, 36201, 36202, 36203, 36215, 36216, 36217, 36218, 36230, 36231, 36232, 36233, 36245, 36246, 36247, 36248, 36260, 36261, 36262, 36263, ...], ('SUDESTE', 'ÓLEO DIESEL'): [42632, 42633, 42634, 42635, 42659, 42660, 42661, 42662, 42686, 42687, 42688, 42689, 42713, 42714, 42715, 42716, 42740, 42741, 42742, 42743, 42767, 42768, 42769, 42770, 42794, 42795, 42796, 42797, 42821, 42822, 42823, 42824, 42848, 42849, 42850, 42851, 42875, 42876, 42877, 42878, 42902, 42903, 42904, 42905, 42929, 42930, 42931, 42932, 42956, 42957, 42958, 42959, 42983, 42984, 42985, 42986, 43010, 43011, 43012, 43013, 43037, 43038, 43039, 43040, 43064, 43065, 43066, 43067, 43091, 43092, 43093, 43094, 43118, 43119, 43120, 43121, 43145, 43146, 43147, 43148, 43172, 43173, 43174, 43175, 43199, 43200, 43201, 43202, 43226, 43227, 43228, 43229, 43253, 43254, 43255, 43256, 43280, 43281, 43282, 43283, ...], ('SUDESTE', 'ÓLEO DIESEL S10'): [54704, 54711, 54836, 54841, 54846, 54972, 54977, 54983, 54988, 55116, 55121, 55127, 55132, 55261, 55266, 55272, 55277, 55404, 55409, 55415, 55420, 55548, 55553, 55559, 55564, 55691, 55696, 55702, 55707, 55834, 55839, 55845, 55851, 55980, 55985, 55991, 55997, 56127, 56132, 56138, 56144, 56275, 56280, 56286, 56292, 56420, 56425, 56431, 56437, 56565, 56570, 56576, 56582, 56710, 56715, 56721, 56727, 56855, 56860, 56866, 56872, 57003, 57008, 57014, 57020, 57149, 57154, 57160, 57166, 57294, 57299, 57305, 57311, 57441, 57446, 57452, 57458, 57587, 57592, 57598, 57604, 57733, 57738, 57744, 57750, 57880, 57885, 57891, 57897, 58026, 58031, 58037, 58043, 58173, 58178, 58184, 58190, 58316, 58321, 58327, ...], ('SUL', 'ETANOL HIDRATADO'): [24, 25, 26, 51, 52, 53, 78, 79, 80, 105, 106, 107, 132, 133, 134, 159, 160, 161, 186, 187, 188, 213, 214, 215, 240, 241, 242, 267, 268, 269, 294, 295, 296, 321, 322, 323, 348, 349, 350, 375, 376, 377, 402, 403, 404, 429, 430, 431, 456, 457, 458, 483, 484, 485, 510, 511, 512, 537, 538, 539, 564, 565, 566, 591, 592, 593, 618, 619, 620, 645, 646, 647, 672, 673, 674, 699, 700, 701, 726, 727, 728, 753, 754, 755, 780, 781, 782, 807, 808, 809, 834, 835, 836, 861, 862, 863, 888, 889, 890, 915, ...], ('SUL', 'GASOLINA COMUM'): [12004, 12005, 12006, 12031, 12032, 12033, 12058, 12059, 12060, 12085, 12086, 12087, 12112, 12113, 12114, 12139, 12140, 12141, 12166, 12167, 12168, 12193, 12194, 12195, 12220, 12221, 12222, 12247, 12248, 12249, 12274, 12275, 12276, 12301, 12302, 12303, 12328, 12329, 12330, 12355, 12356, 12357, 12382, 12383, 12384, 12409, 12410, 12411, 12436, 12437, 12438, 12463, 12464, 12465, 12490, 12491, 12492, 12517, 12518, 12519, 12544, 12545, 12546, 12571, 12572, 12573, 12598, 12599, 12600, 12625, 12626, 12627, 12652, 12653, 12654, 12679, 12680, 12681, 12706, 12707, 12708, 12733, 12734, 12735, 12760, 12761, 12762, 12787, 12788, 12789, 12814, 12815, 12816, 12841, 12842, 12843, 12868, 12869, 12870, 12895, ...], ('SUL', 'GLP'): [24043, 24044, 24045, 24070, 24071, 24072, 24097, 24098, 24099, 24124, 24125, 24126, 24151, 24152, 24153, 24178, 24179, 24180, 24205, 24206, 24207, 24232, 24233, 24234, 24259, 24260, 24261, 24286, 24287, 24288, 24313, 24314, 24315, 24340, 24341, 24342, 24367, 24368, 24369, 24394, 24395, 24396, 24421, 24422, 24423, 24448, 24449, 24450, 24475, 24476, 24477, 24502, 24503, 24504, 24529, 24530, 24531, 24555, 24556, 24557, 24582, 24583, 24584, 24609, 24610, 24611, 24636, 24637, 24638, 24663, 24664, 24665, 24690, 24691, 24692, 24716, 24717, 24718, 24743, 24744, 24745, 24770, 24771, 24772, 24797, 24798, 24799, 24824, 24825, 24826, 24851, 24852, 24853, 24878, 24879, 24880, 24905, 24906, 24907, 24932, ...], ('SUL', 'GNV'): [35904, 35905, 35906, 35919, 35920, 35921, 35934, 35935, 35936, 35949, 35950, 35951, 35964, 35965, 35966, 35979, 35980, 35981, 35994, 35995, 35996, 36009, 36010, 36011, 36024, 36025, 36026, 36039, 36040, 36041, 36054, 36055, 36056, 36069, 36070, 36071, 36084, 36085, 36086, 36099, 36100, 36101, 36114, 36115, 36116, 36129, 36130, 36131, 36144, 36145, 36146, 36159, 36160, 36161, 36174, 36175, 36176, 36189, 36190, 36191, 36204, 36205, 36206, 36219, 36220, 36221, 36234, 36235, 36236, 36249, 36250, 36251, 36264, 36265, 36266, 36280, 36281, 36282, 36295, 36296, 36297, 36310, 36311, 36312, 36326, 36327, 36328, 36342, 36343, 36344, 36357, 36358, 36359, 36372, 36373, 36374, 36387, 36388, 36389, 36402, ...], ('SUL', 'ÓLEO DIESEL'): [42636, 42637, 42638, 42663, 42664, 42665, 42690, 42691, 42692, 42717, 42718, 42719, 42744, 42745, 42746, 42771, 42772, 42773, 42798, 42799, 42800, 42825, 42826, 42827, 42852, 42853, 42854, 42879, 42880, 42881, 42906, 42907, 42908, 42933, 42934, 42935, 42960, 42961, 42962, 42987, 42988, 42989, 43014, 43015, 43016, 43041, 43042, 43043, 43068, 43069, 43070, 43095, 43096, 43097, 43122, 43123, 43124, 43149, 43150, 43151, 43176, 43177, 43178, 43203, 43204, 43205, 43230, 43231, 43232, 43257, 43258, 43259, 43284, 43285, 43

In [192]:
grupos['PREÇO MÉDIO REVENDA'].mean()

REGIÃO        PRODUTO
CENTRO OESTE  ETANOL HIDRATADO     2.135670
              GASOLINA COMUM       3.077476
              GLP                 48.176747
              GNV                  1.856312
              ÓLEO DIESEL          2.481286
              ÓLEO DIESEL S10      3.294752
NORDESTE      ETANOL HIDRATADO     2.320266
              GASOLINA COMUM       3.001887
              GLP                 41.966090
              GNV                  1.881722
              ÓLEO DIESEL          2.346950
              ÓLEO DIESEL S10      3.041966
NORTE         ETANOL HIDRATADO     2.511624
              GASOLINA COMUM       3.149501
              GLP                 47.065572
              GNV                  2.084399
              ÓLEO DIESEL          2.571048
              ÓLEO DIESEL S10      3.316231
SUDESTE       ETANOL HIDRATADO     2.163621
              GASOLINA COMUM       3.000565
              GLP                 42.081544
              GNV                  1.716074
              ÓLEO DIESEL          2.339699
              ÓLEO DIESEL S10      3.056194
SUL           ETANOL HIDRATADO     2.268156
              GASOLINA COMUM       2.972569
              GLP                 43.490318
              GNV                  1.865612
              ÓLEO DIESEL          2.332293
              ÓLEO DIESEL S10      2.981775
Name: PREÇO MÉDIO REVENDA, dtype: float64

In [193]:
grupos['PREÇO MÉDIO REVENDA'].describe()

                                count       mean        std     min       25%  \
REGIÃO       PRODUTO
CENTRO OESTE ETANOL HIDRATADO  3122.0   2.135670   0.561465   1.162   1.71400
             GASOLINA COMUM    3134.0   3.077476   0.615290   1.936   2.66725
             GLP               3098.0  48.176747  15.204045  28.791  37.33300
             GNV                847.0   1.856312   0.423861   1.097   1.56900
             ÓLEO DIESEL       3134.0   2.481286   0.626930   1.435   2.03300
             ÓLEO DIESEL S10   1210.0   3.294752   0.421234   2.305   2.92425
NORDESTE     ETANOL HIDRATADO  7046.0   2.320266   0.604374   1.181   1.82500
             GASOLINA COMUM    7063.0   3.001887   0.640696   1.949   2.58400
             GLP               6410.0  41.966090  12.063743  28.367  33.22875
             GNV               5176.0   1.881722   0.522996   0.975   1.59600
             ÓLEO DIESEL       7061.0   2.346950   0.605705   1.313   1.90000
             ÓLEO DIESEL S10   3032.0   3.041966   0.441550   2.130   2.60000
NORTE        ETANOL HIDRATADO  5177.0   2.511624   0.646781   1.226   2.03300
             GASOLINA COMUM    5464.0   3.149501   0.641249   1.995   2.70475
             GLP               5327.0  47.065572  14.553748  28.086  36.32950
             GNV                243.0   2.084399   0.622229   1.399   1.39900
             ÓLEO DIESEL       5465.0   2.571048   0.650994   1.450   2.08600
             ÓLEO DIESEL S10   2324.0   3.316231   0.529044   2.193   2.88300
SUDESTE      ETANOL HIDRATADO  3137.0   2.163621   0.651486   0.766   1.69200
             GASOLINA COMUM    3140.0   3.000565   0.698573   1.888   2.50200
             GLP               3137.0  42.081544  11.524738  28.026  33.63600
             GNV               2841.0   1.716074   0.462098   0.996   1.42400
             ÓLEO DIESEL       3140.0   2.339699   0.588641   1.356   1.87600
             ÓLEO DIESEL S10   1349.0   3.056194   0.418396   2.180   2.65000
SUL          ETANOL HIDRATADO  2353.0   2.268156   0.702877   0.922   1.72100
             GASOLINA COMUM    2354.0   2.972569   0.623557   1.961   2.54300
             GLP               2343.0  43.490318  11.640755  29.440  34.79250
             GNV               1899.0   1.865612   0.490703   1.168   1.49900
             ÓLEO DIESEL       2354.0   2.332293   0.527845   1.374   1.95100
             ÓLEO DIESEL S10   1012.0   2.981775   0.365470   2.151   2.66300

                                   50%       75%     max
REGIÃO       PRODUTO
CENTRO OESTE ETANOL HIDRATADO   2.0005   2.47900   3.598
             GASOLINA COMUM     2.8565   3.45975   4.963
             GLP               42.8385  55.90425  99.357
             GNV                1.7490   2.16800   3.239
             ÓLEO DIESEL        2.2465   3.01900   4.162
             ÓLEO DIESEL S10    3.3540   3.61900   4.200
NORDESTE     ETANOL HIDRATADO   2.1860   2.67000   3.927
             GASOLINA COMUM     2.7410   3.42450   4.951
             GLP               36.8550  48.35100  79.630
             GNV                1.8005   2.01125   3.811
             ÓLEO DIESEL        2.0820   2.86700   4.010
             ÓLEO DIESEL S10    3.0865   3.33800   4.027
NORTE        ETANOL HIDRATADO   2.3390   2.89600   4.102
             GASOLINA COMUM     2.9330   3.58475   5.362
             GLP               42.3110  54.07500  87.270
             GNV                2.0600   2.65000   3.240
             ÓLEO DIESEL        2.3390   3.08200   4.774
             ÓLEO DIESEL S10    3.3155   3.65300   4.878
SUDESTE      ETANOL HIDRATADO   2.0430   2.56700   4.115
             GASOLINA COMUM     2.7930   3.45150   5.119
             GLP               38.2800  49.25900  79.192
             GNV                1.6630   1.90400   3.399
             ÓLEO DIESEL        2.0825   2.82500   3.994
             ÓLEO DIESEL S10    3.0910   3.38600   4.080
SUL          ETANOL HIDRATADO   2.1130   2.60100   4.287
             GASOLINA COMUM     2.7315   3.34225   4.953
             GLP               39.9760  48.73350  72.088
             GNV                1.7020   2.15950   3.476
             ÓLEO DIESEL        2.0900   2.78450   3.800
             ÓLEO DIESEL S10    2.9910   3.25200   3.815

In [194]:
df = pd.DataFrame([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9],
                   [None, None, None]],
                  columns=['A', 'B', 'C'])
df

     A    B    C
0  1.0  2.0  3.0
1  4.0  5.0  6.0
2  7.0  8.0  9.0
3  NaN  NaN  NaN

In [195]:
df.agg([sum, min])

/tmp/ipykernel_9521/1226331895.py:1: FutureWarning: The provided callable <built-in function sum> is currently using Series.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  df.agg([sum, min])
/tmp/ipykernel_9521/1226331895.py:1: FutureWarning: The provided callable <built-in function min> is currently using Series.min. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "min" instead.
  df.agg([sum, min])

        A     B     C
sum  12.0  15.0  18.0
min   1.0   2.0   3.0

In [196]:
grupos = data_final.groupby('REGIÃO')
grupos

In [197]:
grupos['PREÇO MÉDIO REVENDA'].agg([min, max])

/tmp/ipykernel_9521/3977787304.py:1: FutureWarning: The provided callable <built-in function min> is currently using SeriesGroupBy.min. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "min" instead.
  grupos['PREÇO MÉDIO REVENDA'].agg([min, max])
/tmp/ipykernel_9521/3977787304.py:1: FutureWarning: The provided callable <built-in function max> is currently using SeriesGroupBy.max. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "max" instead.
  grupos['PREÇO MÉDIO REVENDA'].agg([min, max])

                min     max
REGIÃO
CENTRO OESTE  1.097  99.357
NORDESTE      0.975  79.630
NORTE         1.226  87.270
SUDESTE       0.766  79.192
SUL           0.922  72.088

# 6 Ordenação

In [6]:
notas = pd.DataFrame({
    'nome': ['João', 'Maria', 'José', 'Alice'],
    'idade': [20, 21, 19, 20],
    'nota_final': [5.0, 10.0, 6.0, 10.0]
})
notas

    nome  idade  nota_final
0   João     20         5.0
1  Maria     21        10.0
2   José     19         6.0
3  Alice     20        10.0

In [7]:
notas.sort_values(by='nota_final')

    nome  idade  nota_final
0   João     20         5.0
2   José     19         6.0
1  Maria     21        10.0
3  Alice     20        10.0

In [8]:
notas.sort_values(by='nota_final', ascending=False)

    nome  idade  nota_final
1  Maria     21        10.0
3  Alice     20        10.0
2   José     19         6.0
0   João     20         5.0

In [9]:
notas.sort_values(by=['nota_final', 'nome'], ascending=[False, True])

    nome  idade  nota_final
3  Alice     20        10.0
1  Maria     21        10.0
2   José     19         6.0
0   João     20         5.0

In [10]:
notas

    nome  idade  nota_final
0   João     20         5.0
1  Maria     21        10.0
2   José     19         6.0
3  Alice     20        10.0

In [12]:
notas.sort_values(by=['nota_final', 'nome'], ascending=[False, True], inplace=True)
notas

    nome  idade  nota_final
3  Alice     20        10.0
1  Maria     21        10.0
2   José     19         6.0
0   João     20         5.0

# 7 Exercícios

In [31]:
data_final

,Unnamed: 0,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,...,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO
0,0,2004-05-09,2004-05-15,CENTRO OESTE,DISTRITO FEDERAL,ETANOL HIDRATADO,127,R$/l,1.288,0.016,...,1.350,0.463,0.012,0.825,0.110,0.4201,0.96660,0.133,5,2004
1,1,2004-05-09,2004-05-15,CENTRO OESTE,GOIAS,ETANOL HIDRATADO,387,R$/l,1.162,0.114,...,1.449,0.399,0.098,0.763,0.088,0.5013,1.05000,0.115,5,2004
2,2,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO,ETANOL HIDRATADO,192,R$/l,1.389,0.097,...,1.760,0.419,0.070,0.970,0.095,0.5614,1.16100,0.098,5,2004
3,3,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO DO SUL,ETANOL HIDRATADO,162,R$/l,1.262,0.070,...,1.509,0.432,0.055,0.830,0.119,0.5991,1.22242,0.143,5,2004
4,4,2004-05-09,2004-05-15,NORDESTE,ALAGOAS,ETANOL HIDRATADO,103,R$/l,1.181,0.078,...,1.400,0.240,0.066,0.941,0.077,0.7441,1.03170,0.082,5,2004
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
103387,106818,2019-06-23,2019-06-29,NORDESTE,RIO GRANDE DO NORTE,GNV,7,R$/m3,3.574,0.065,...,3.690,0.818,0.018,2.756,0.000,2.7560,2.75600,0.000,6,2019
103388,106819,2019-06-23,2019-06-29,SUL,RIO GRANDE DO SUL,GNV,23,R$/m3,3.401,0.129,...,3.789,0.950,0.038,2.451,0.402,1.9842,2.86610,0.164,6,2019
103389,106820,2019-06-23,2019-06-29,SUL,SANTA CATARINA,GNV,24,R$/m3,2.912,0.190,...,3.499,0.914,0.065,1.998,0.000,1.9981,1.99810,0.000,6,2019
103390,106821,2019-06-23,2019-06-29,SUDESTE,SAO PAULO,GNV,52,R$/m3,3.020,0.229,...,3.490,0.646,0.076,2.374,0.165,2.0179,2.50930,0.070,6,2019
103391,106822,2019-06-23,2019-06-29,NORDESTE,SERGIPE,GNV,4,R$/m3,3.697,0.005,...,3.699,1.179,0.001,2.518,0.000,2.5175,2.51750,0.000,6,2019

In [34]:
data_final_2019 = data_final.query('ANO != 2019')

In [43]:
data_index = data_final_2019.reset_index(drop=True)

## 7.1

In [51]:
data_produto = data_index.groupby('PRODUTO')
data_produto

In [52]:
data_produto['REGIÃO'].value_counts().to_frame()

                               count
PRODUTO          REGIÃO
ETANOL HIDRATADO NORDESTE       6821
                 NORTE          5021
                 SUDESTE        3039
                 CENTRO OESTE   3022
                 SUL            2278
GASOLINA COMUM   NORDESTE       6838
                 NORTE          5289
                 SUDESTE        3040
                 CENTRO OESTE   3034
                 SUL            2279
GLP              NORDESTE       6185
                 NORTE          5152
                 SUDESTE        3037
                 CENTRO OESTE   2998
                 SUL            2268
GNV              NORDESTE       5030
                 SUDESTE        2772
                 SUL            1847
                 CENTRO OESTE    825
                 NORTE           233
ÓLEO DIESEL      NORDESTE       6836
                 NORTE          5290
                 SUDESTE        3040
                 CENTRO OESTE   3034
                 SUL            2279
ÓLEO DIESEL S10  NORDESTE       2807
                 NORTE          2149
                 SUDESTE        1249
                 CENTRO OESTE   1110
                 SUL             937

## 7.2

In [55]:
gasolina_de_sp_2018 = data_index.query('PRODUTO == "GASOLINA COMUM" and ESTADO == "SAO PAULO" and ANO == 2018')
gasolina_de_sp_2018.head()

,Unnamed: 0,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,...,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO
92319,95351,2018-01-07,2018-01-13,SUDESTE,SAO PAULO,GASOLINA COMUM,1641,R$/l,3.988,0.156,...,4.599,0.411,0.039,3.577,0.104,2.990,3.9510,0.029,1,2018
92465,95502,2018-01-14,2018-01-20,SUDESTE,SAO PAULO,GASOLINA COMUM,1648,R$/l,4.002,0.155,...,4.499,0.412,0.039,3.590,0.102,2.990,3.9014,0.028,1,2018
92610,95654,2018-01-21,2018-01-27,SUDESTE,SAO PAULO,GASOLINA COMUM,1648,R$/l,4.006,0.160,...,4.899,0.410,0.040,3.596,0.102,2.990,3.9014,0.028,1,2018
92755,95806,2018-01-28,2018-02-03,SUDESTE,SAO PAULO,GASOLINA COMUM,1644,R$/l,4.019,0.156,...,4.699,0.423,0.039,3.596,0.107,2.924,3.9537,0.030,1,2018
92901,95958,2018-02-04,2018-02-10,SUDESTE,SAO PAULO,GASOLINA COMUM,1646,R$/l,4.004,0.157,...,4.597,0.416,0.039,3.588,0.102,2.990,3.9537,0.028,2,2018

In [56]:
gasolina_de_sp_2018.shape

(52, 21)

In [57]:
gasolina_de_sp_2018.describe()

,Unnamed: 0,NÚMERO DE POSTOS PESQUISADOS,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO
count,52.000000,52.000000,52.000000,52.000000,52.000000,52.000000,52.000000,52.000000,52.000000,52.000000,52.00000,52.000000,52.000000,52.000000,52.0
mean,99196.096154,1610.211538,4.202769,0.175500,3.671500,4.975750,0.442481,0.041750,3.760288,0.109654,3.31295,4.139454,0.029096,6.615385,2018.0
std,2279.595314,213.627432,0.180672,0.017955,0.163808,0.211198,0.063271,0.003965,0.163664,0.010712,0.26684,0.195897,0.002460,3.470627,0.0
min,95351.000000,102.000000,3.970000,0.150000,3.369000,4.499000,0.366000,0.034000,3.563000,0.087000,2.92400,3.887500,0.023000,1.000000,2018.0
25%,97281.250000,1639.000000,4.008000,0.159750,3.499000,4.899000,0.404500,0.039000,3.620250,0.102000,2.99000,3.965775,0.028000,4.000000,2018.0
50%,99196.500000,1642.000000,4.202000,0.173000,3.679000,4.999000,0.421500,0.040000,3.756500,0.108000,3.35000,4.095500,0.029000,7.000000,2018.0
75%,101116.250000,1644.000000,4.336250,0.189000,3.784000,5.099000,0.470250,0.044000,3.862250,0.116250,3.53250,4.259000,0.030000,9.250000,2018.0
max,103025.000000,1649.000000,4.512000,0.216000,3.969000,5.299000,0.640000,0.051000,4.085000,0.144000,3.76000,4.551000,0.037000,12.000000,2018.0

In [58]:
gasolina_de_sp_2018['PREÇO MÉDIO REVENDA'].describe().to_frame()

       PREÇO MÉDIO REVENDA
count            52.000000
mean              4.202769
std               0.180672
min               3.970000
25%               4.008000
50%               4.202000
75%               4.336250
max               4.512000

## 7.3

In [59]:
data_index.query('(PRODUTO == "GASOLINA COMUM" or PRODUTO == "ETANOL HIDRATADO") and ESTADO == "SAO PAULO" and ANO == 2018')

,Unnamed: 0,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,...,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO
92238,95270,2018-01-07,2018-01-13,SUDESTE,SAO PAULO,ETANOL HIDRATADO,1664,R$/l,2.833,0.139,...,3.399,0.338,0.049,2.495,0.092,2.1842,2.8833,0.037,1,2018
92319,95351,2018-01-07,2018-01-13,SUDESTE,SAO PAULO,GASOLINA COMUM,1641,R$/l,3.988,0.156,...,4.599,0.411,0.039,3.577,0.104,2.9900,3.9510,0.029,1,2018
92384,95421,2018-01-14,2018-01-20,SUDESTE,SAO PAULO,ETANOL HIDRATADO,1661,R$/l,2.868,0.134,...,3.399,0.331,0.047,2.537,0.087,2.2600,2.8471,0.034,1,2018
92465,95502,2018-01-14,2018-01-20,SUDESTE,SAO PAULO,GASOLINA COMUM,1648,R$/l,4.002,0.155,...,4.499,0.412,0.039,3.590,0.102,2.9900,3.9014,0.028,1,2018
92529,95573,2018-01-21,2018-01-27,SUDESTE,SAO PAULO,ETANOL HIDRATADO,1662,R$/l,2.874,0.135,...,3.399,0.324,0.047,2.550,0.095,1.6900,2.9722,0.037,1,2018
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99410,102724,2018-12-16,2018-12-22,SUDESTE,SAO PAULO,GASOLINA COMUM,1637,R$/l,4.129,0.201,...,5.099,0.490,0.049,3.639,0.110,3.3500,3.9892,0.030,12,2018
99472,102793,2018-12-23,2018-12-29,SUDESTE,SAO PAULO,ETANOL HIDRATADO,1662,R$/l,2.644,0.163,...,3.699,0.305,0.062,2.339,0.094,2.0067,2.7443,0.040,12,2018
99553,102874,2018-12-23,2018-12-29,SUDESTE,SAO PAULO,GASOLINA COMUM,1641,R$/l,4.129,0.201,...,4.999,0.484,0.049,3.645,0.107,3.3500,3.9892,0.029,12,2018
99617,102944,2018-12-30,2019-01-05,SUDESTE,SAO PAULO,ETANOL HIDRATADO,1661,R$/l,2.643,0.161,...,3.699,0.303,0.061,2.340,0.097,1.9072,2.7957,0.041,12,2018
99698,103025,2018-12-30,2019-01-05,SUDESTE,SAO PAULO,GASOLINA COMUM,1643,R$/l,4.113,0.201,...,4.999,0.503,0.049,3.610,0.100,3.3500,3.9585,0.028,12,2018

In [60]:
lista_de_estados = ["GASOLINA COMUM", "ETANOL HIDRATADO"]
data_index.query('PRODUTO in @lista_de_estados and ESTADO == "SAO PAULO" and ANO == 2018')

,Unnamed: 0,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,...,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO
92238,95270,2018-01-07,2018-01-13,SUDESTE,SAO PAULO,ETANOL HIDRATADO,1664,R$/l,2.833,0.139,...,3.399,0.338,0.049,2.495,0.092,2.1842,2.8833,0.037,1,2018
92319,95351,2018-01-07,2018-01-13,SUDESTE,SAO PAULO,GASOLINA COMUM,1641,R$/l,3.988,0.156,...,4.599,0.411,0.039,3.577,0.104,2.9900,3.9510,0.029,1,2018
92384,95421,2018-01-14,2018-01-20,SUDESTE,SAO PAULO,ETANOL HIDRATADO,1661,R$/l,2.868,0.134,...,3.399,0.331,0.047,2.537,0.087,2.2600,2.8471,0.034,1,2018
92465,95502,2018-01-14,2018-01-20,SUDESTE,SAO PAULO,GASOLINA COMUM,1648,R$/l,4.002,0.155,...,4.499,0.412,0.039,3.590,0.102,2.9900,3.9014,0.028,1,2018
92529,95573,2018-01-21,2018-01-27,SUDESTE,SAO PAULO,ETANOL HIDRATADO,1662,R$/l,2.874,0.135,...,3.399,0.324,0.047,2.550,0.095,1.6900,2.9722,0.037,1,2018
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99410,102724,2018-12-16,2018-12-22,SUDESTE,SAO PAULO,GASOLINA COMUM,1637,R$/l,4.129,0.201,...,5.099,0.490,0.049,3.639,0.110,3.3500,3.9892,0.030,12,2018
99472,102793,2018-12-23,2018-12-29,SUDESTE,SAO PAULO,ETANOL HIDRATADO,1662,R$/l,2.644,0.163,...,3.699,0.305,0.062,2.339,0.094,2.0067,2.7443,0.040,12,2018
99553,102874,2018-12-23,2018-12-29,SUDESTE,SAO PAULO,GASOLINA COMUM,1641,R$/l,4.129,0.201,...,4.999,0.484,0.049,3.645,0.107,3.3500,3.9892,0.029,12,2018
99617,102944,2018-12-30,2019-01-05,SUDESTE,SAO PAULO,ETANOL HIDRATADO,1661,R$/l,2.643,0.161,...,3.699,0.303,0.061,2.340,0.097,1.9072,2.7957,0.041,12,2018
99698,103025,2018-12-30,2019-01-05,SUDESTE,SAO PAULO,GASOLINA COMUM,1643,R$/l,4.113,0.201,...,4.999,0.503,0.049,3.610,0.100,3.3500,3.9585,0.028,12,2018

In [61]:
gasolina_etanol_sp_2018 = data_index.query('PRODUTO in ["GASOLINA COMUM", "ETANOL HIDRATADO"] and ESTADO == "SAO PAULO" and ANO == 2018')
gasolina_etanol_sp_2018

,Unnamed: 0,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,...,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO
92238,95270,2018-01-07,2018-01-13,SUDESTE,SAO PAULO,ETANOL HIDRATADO,1664,R$/l,2.833,0.139,...,3.399,0.338,0.049,2.495,0.092,2.1842,2.8833,0.037,1,2018
92319,95351,2018-01-07,2018-01-13,SUDESTE,SAO PAULO,GASOLINA COMUM,1641,R$/l,3.988,0.156,...,4.599,0.411,0.039,3.577,0.104,2.9900,3.9510,0.029,1,2018
92384,95421,2018-01-14,2018-01-20,SUDESTE,SAO PAULO,ETANOL HIDRATADO,1661,R$/l,2.868,0.134,...,3.399,0.331,0.047,2.537,0.087,2.2600,2.8471,0.034,1,2018
92465,95502,2018-01-14,2018-01-20,SUDESTE,SAO PAULO,GASOLINA COMUM,1648,R$/l,4.002,0.155,...,4.499,0.412,0.039,3.590,0.102,2.9900,3.9014,0.028,1,2018
92529,95573,2018-01-21,2018-01-27,SUDESTE,SAO PAULO,ETANOL HIDRATADO,1662,R$/l,2.874,0.135,...,3.399,0.324,0.047,2.550,0.095,1.6900,2.9722,0.037,1,2018
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99410,102724,2018-12-16,2018-12-22,SUDESTE,SAO PAULO,GASOLINA COMUM,1637,R$/l,4.129,0.201,...,5.099,0.490,0.049,3.639,0.110,3.3500,3.9892,0.030,12,2018
99472,102793,2018-12-23,2018-12-29,SUDESTE,SAO PAULO,ETANOL HIDRATADO,1662,R$/l,2.644,0.163,...,3.699,0.305,0.062,2.339,0.094,2.0067,2.7443,0.040,12,2018
99553,102874,2018-12-23,2018-12-29,SUDESTE,SAO PAULO,GASOLINA COMUM,1641,R$/l,4.129,0.201,...,4.999,0.484,0.049,3.645,0.107,3.3500,3.9892,0.029,12,2018
99617,102944,2018-12-30,2019-01-05,SUDESTE,SAO PAULO,ETANOL HIDRATADO,1661,R$/l,2.643,0.161,...,3.699,0.303,0.061,2.340,0.097,1.9072,2.7957,0.041,12,2018
99698,103025,2018-12-30,2019-01-05,SUDESTE,SAO PAULO,GASOLINA COMUM,1643,R$/l,4.113,0.201,...,4.999,0.503,0.049,3.610,0.100,3.3500,3.9585,0.028,12,2018

In [62]:
gasolina_etanol_sp_2018['PREÇO MÉDIO REVENDA'].describe().to_frame()

       PREÇO MÉDIO REVENDA
count           104.000000
mean              3.457337
std               0.766239
min               2.393000
25%               2.726000
50%               3.431000
75%               4.199000
max               4.512000

In [63]:
gasolina_etanol_sp_2018.groupby('PRODUTO')['PREÇO MÉDIO REVENDA'].describe()

,count,mean,std,min,25%,50%,75%,max
PRODUTO,,,,,,,,
ETANOL HIDRATADO,52.0,2.711904,0.141365,2.393,2.6315,2.720,2.83825,2.892
GASOLINA COMUM,52.0,4.202769,0.180672,3.970,4.0080,4.202,4.33625,4.512